- README.md
Taking a cue from [RubySec](https://rubysec.com), this splits the original "versions" attribute into
separate ones for versions which were never vulnerable, and ones which include
an explicit fix for a vulnerability.
> Separate "unaffected_versions" and "patched_versions"

- README.md
Once again taking a cue from RubySec (but also systems like CVE),
advisories should have a one-liner title
> Add titles to advisories

- README.md
Was previously `[vulnerability]`, but as the contents are a security advisory
it's probably a more apt label.
> Use [advisory] as the table header for advisories

- crates/sodiumoxide/RUSTSEC-0000-0000.toml
Fixed in sodiumoxide 0.0.14 (cc @dnaq)
See: https://github.com/dnaq/sodiumoxide/issues/154
---
This commit also serves as a sort of archetype for filing future security advisories.
It proposes a `RUSTSEC-YYYY-NNNN` format for identifying advisories. Ideally we'd use [Distributed Weakness Filing](https://github.com/distributedweaknessfiling/) for this purpose, but I've been having trouble getting ahold of the DWF maintainer to move forward on that (cc @kurtseifried)
However, we can adopt the `RUSTSEC-...` scheme for now, then refile vulnerabilities under DWF if and when we get a block assigned (RubySec, as an example, has had to refile vulnerabilities this way several times)
> Advisory: sodiumoxide degenerate public keys

- Advisories.toml
- README.md
- crates/sodiumoxide/RUSTSEC-2017-0001.toml
The correct name for a Rust package is a "crate", so something with "crate" is
less ambiguous than "package".
However, "crate" itself is a Rust keyword. To avoid clashes in Rust code which
uses this same attribute name, "crate_name" can be used instead unambigously.
> Rename `package` TOML attribute to `crate_name`

- Advisories.toml
- README.md
- crates/sodiumoxide/RUSTSEC-2017-0001.toml
Cargo uses "package" in Cargo.lock, so there is wisdom to using "package"
instead of "crate_name"
This reverts commit 986c090c066185ea24cc1e58aef2bb949c152810, reversing
changes made to 9556f0fdeedba0c3b8ff4ca51490ea3bf7c31e43.
> Revert "Merge pull request #8 from RustSec/rename-package-to-crate-name"

- Cargo.toml
The latest version handles the `crate_name` -> `package` revert
> Update rustsec crate to ^0.3

- crates/base64/RUSTSEC-2017-0004.toml
https://github.com/CVEProject/cvelist/pull/219/
> RUSTSEC-2017-0004 is also known as CVE-2017-1000430

- crates/untrusted/RUSTSEC-0000-0000.toml
Ping @briansmith, the author and maintainer of untrusted who has seen this advisory before submission.
Short description:
> A mistake in error handling in untrusted before 0.6.2 could lead to an integer underflow and panic if a user of the crate didn't properly check for errors returned by untrusted.
>
> Combination of these two programming errors (one in untrusted and another by user of this crate) could lead to a panic and maybe a denial of service of affected software.
>
> The error in untrusted is fixed in release 0.6.2 released 2018-06-21. It's also advisable that users of untrusted check for their sources for cases where errors returned by untrusted are not handled correctly.
> Advisory: An integer underflow in untrusted 0.6.1 and older which could lead to panic

- crates/tar/RUSTSEC-2018-0002.toml
> Aribtrary filesystem writes in tar 0.4.15 and older

- crates/smallvec/RUSTSEC-0000-0000.toml
For details, see:
* servo/rust-smallvec#96 - original bug report
* servo/rust-smallvec#103 - fix
> Advisory: Possible double free in SmallVec::insert_many

- Advisories.toml
- crates/tar/RUSTSEC-2018-0002.toml
`RUSTSEC-2018-0002` was previously assigned to `tar`, but never added to `Advisories.toml`.
The merge workflow for this could definitely use some improvements/automation.
> Advisories.toml: Fix RUSTSEC-2018-0002

- crates/base64/RUSTSEC-2017-0004.toml
- crates/cookie/RUSTSEC-2017-0005.toml
- crates/hyper/RUSTSEC-2017-0002.toml
- crates/security-framework/RUSTSEC-2017-0003.toml
- crates/smallvec/RUSTSEC-2018-0003.toml
- crates/sodiumoxide/RUSTSEC-2017-0001.toml
- crates/untrusted/RUSTSEC-2018-0001.toml
This is needed to parse them with serde directly from these files (as opposed to using Advisories.toml)
> crates: Add 'id' attribute to all advisories

- Advisories.toml
- README.md
- crates/base64/RUSTSEC-2017-0004.toml
- crates/cookie/RUSTSEC-2017-0005.toml
- crates/hyper/RUSTSEC-2017-0002.toml
- crates/security-framework/RUSTSEC-2017-0003.toml
- crates/smallvec/RUSTSEC-2018-0003.toml
- crates/sodiumoxide/RUSTSEC-2017-0001.toml
- crates/tar/RUSTSEC-2018-0002.toml
- crates/untrusted/RUSTSEC-2018-0001.toml
Nobody knows what "dwf" is, and the data isn't presently consumed or surfaced by the `rustsec` crate, so we (hopefully) can rename it without breaking anything.
> Rename "dwf" TOML tag to "aliases" (closes #36)

- CONTRIBUTING.md
This is long overdue! (see #25) It provides basic instructions for filing advisories against the database, and also some guidelines for what types of vulnerabilities qualify.
[Rendered](https://github.com/RustSec/advisory-db/blob/63f70efb1ac4e75cb083ef41d32bea793e972b49/CONTRIBUTING.md)
> CONTRIBUTING.md: Vulnerability reporting instructions and criteria

- Cargo.toml
Adds support for `affected_platforms` and `keywords` attributes on security advisories.
> Upgrade to rustsec 0.8

- Advisories.toml
Adds the newly merged (but oldest chronological!) advisories into the `Advisories.toml` file (which can go away pending #29)
> Advisories.toml: Add RUSTSEC-2016-0001 and RUSTSEC-2016-0002

- README.md
- crates/hyper/RUSTSEC-2016-0002.toml
These are new attributes as of `rustsec` crate v0.9.0 which use enums from the `platforms` crate to represent CPU architectures and operating systems.
This replaces the previous `affected_platforms` attribute (only used in one advisory)
Also updates RUSTSEC-2016-0002.toml to use the new 'affected_os' attribute.
> README.md: Documented `affected_arch` and `affected_os`

- crates/claxon/RUSTSEC-0000-0000.toml
I just published Claxon 0.3.2 and 0.4.1 which fix https://github.com/ruuda/claxon/issues/10.
> Add advisory for Claxon 0.3.2 and 0.4.1

- crates/serde_yaml/RUSTSEC-0000-0000.toml
Not sure if an abort is a valid vulnerability, but for me crashing the entire application with no possibility of recovery (it's abort, not a panic) sounds like denial of service.
This is separate from #60, this is about YAML aliases, not very deep data structures. That said, #60 was discovered while trying to fix that one.
> Add advisory for serde_yaml

- crates/yaml-rust/RUSTSEC-0000-0000.toml
Not sure if an abort is a valid vulnerability, but for me crashing the entire application with no possibility of recovery (it's abort, not a panic) sounds like denial of service.
> Add advisory for yaml-rust

- crates/trust-dns-proto/RUSTSEC-0000-0000.toml
Ping @bluejekyll. This issue has been fixed in `trust-dns-proto` crate versions 0.4.3 and 0.5.0-alpha.3.
Since I haven't published my writeup about this issue anywhere else, I'll post it here for reference.
by Ossi Herrala, SensorFu Ltd, 2018-10-09
There's a stack overflow leading to a crash when Trust-DNS (client, server, resolver) receives a malicious DNS packet. This can be considered a Denial of Service vulnerability.
The following Proof of Concept is tested and analysis done with Trust-DNS based server running on macOS Sierra 10.12.6.
This PoC expects Trust-DNS's "named" server to listen on localhost port 1053. The PoC constructs a malicious DNS query packet, where the queries section contain one query with self referencing DNS Name using DNS label compression (RFC1035 4.1.4).
Start …
> Trust-DNS: Stack overflow when parsing DNS packet

- crates/trust-dns-proto/RUSTSEC-2018-0007.toml
It appears it was mistakenly filed as being in 2017
cc @oherrala
> Fix "date" field on RUSTSEC-2018-0007

- crates/arrayfire/RUSTSEC-0000-0000.toml
I have filled in the template to the best of my knowledge.
The following are the URLS for the issue and corresponding PR that fixes the issue on the crate repository.
https://github.com/arrayfire/arrayfire-rust/issues/176
https://github.com/arrayfire/arrayfire-rust/pull/177
Please let me know if any modifications are required.
Thank you.
> Enum repr memory corruption in arrayfire crate

- crates/base64/RUSTSEC-2017-0004.toml
- crates/hyper/RUSTSEC-2017-0002.toml
- crates/smallvec/RUSTSEC-2018-0003.toml
- crates/tar/RUSTSEC-2018-0002.toml
- crates/untrusted/RUSTSEC-2018-0001.toml
Adds the newly introduced `affected_functions` attribute to some legacy security warnings.
> Add affected functions to legacy security warnings

- README.md
This is largely to work around the following:
```
$ cargo audit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
error: couldn't fetch advisory database: git operation failed: no signature on commit 0a981e2b6f3c8aeaaaa194989d8d3e4a53e3c199: Add affected functions to legacy security warnings (#83) (Moritz Beller <Inventitech@users.noreply.github.com>)
```
I tried to Squash-and-Merge on #83. GitHub does not sign the resulting commit. Oops.
So this commit is just to make `HEAD` a GitHub-signed merge commit.
> README.md: Bump maintained date

- crates/libp2p-core/RUSTSEC-2019-0004.toml
- crates/protobuf/RUSTSEC-2019-0003.toml
Original PRs:
- `protobuf`: https://github.com/RustSec/advisory-db/pull/97
- `libp2p-core`: https://github.com/RustSec/advisory-db/pull/98
> Assign RUSTSEC-2019-0003 to protobuf; -0004 to libp2p-core

- crates/protobuf/RUSTSEC-2019-0003.toml
Upstream issue: https://github.com/stepancheg/rust-protobuf/issues/411
> protobuf 2.6.0 and 1.7.5 released with fix to RUSTSEC-2019-0003

- crates/protobuf/RUSTSEC-2019-0003.toml
> RUSTSEC-2019-0003: Fix date

- crates/portaudio/RUSTSEC-0000-0000.toml
Via: https://github.com/RustAudio/rust-portaudio/issues/144
This is, as of yet, unfixed.
> [portaudio] add build script RCE

- crates/ncurses/RUSTSEC-2019-0004.toml
- crates/pancurses/RUSTSEC-2019-0005.toml
Original PRs:
- **RUSTSEC-2019-0004** (ncurses): https://github.com/RustSec/advisory-db/pull/107
- **RUSTSEC-2019-0005** (pancurses): https://github.com/RustSec/advisory-db/pull/108
> Assign RUSTSEC-2019-0004 to ncurses; -0005 to pancurses

- crates/ncurses/RUSTSEC-2019-0006.toml
RUSTSEC-2019-0004 is already assigned to a `libp2p-core` vulnerability.
Apparently we don't have tests to catch this? Unfortunate.
I opened an issue about that here:
https://github.com/RustSec/rustsec-crate/issues/63
> Reassign ncurses vuln from RUSTSEC-2019-0004 => 0006

- crates/ncurses/RUSTSEC-2019-0006.toml
As filed, advisory RUSTSEC-2019-0006 simply notes that certain
functions in the covered crate create a "format vulnerability". This
patch, following up on [an exchange of comments on GitHub][1], edits
advisory RUSTSEC-2019-0006 to summarize the risk introduced by a
format vulnerability, copying the wording of the associated advisory
RUSTSEC-2019-0005.
[1]: <https://github.com/RustSec/advisory-db/pull/107#pullrequestreview-250212575>
> RUSTSEC-2019-0006: Use -0005's format vuln wording

- crates/smallvec/RUSTSEC-0000-0000.toml
https://github.com/servo/rust-smallvec/issues/149
I had trouble evaluating the impact because running the simplest possible testcase under ASAN is already a SIGILL.
> Add advisory for smallvec issue #149

- crates/memoffset/RUSTSEC-2019-0011.toml
This affects all versions ever published.
> actually memoffset also had an uninit-drop vuln

- crates/image/RUSTSEC-0000-0000.toml
As asked for here: https://github.com/image-rs/image/pull/985#issuecomment-526855953
> Add hdr decoder use-after-free advisory

- crates/compact_arena/RUSTSEC-0000-0000.toml
Thanks @Shnatsel for pointing me to this repo in [this comment](https://github.com/llogiq/compact_arena/issues/22#issuecomment-526859341).
> add out-of-bounds memory access in compact_arena < 0.4.0

- crates/chttp/RUSTSEC-0000-0000.toml
See https://github.com/sagebind/isahc/issues/2.
> Add advisory for use-after-free in chttp 0.1.1, 0.1.2

- support.toml
Adds an initial file indicating what version of the `rustsec` crate the advisory database is compatible with. This is designed for use with the corresponding feature in the `rustsec` crate:
https://github.com/RustSec/rustsec-crate/pull/76
> support.toml: Initial file

- rust/rustdoc/CVE-2018-1000622.toml
- rust/std/CVE-2018-1000657.toml
- rust/std/CVE-2018-1000810.toml
- rust/std/CVE-2019-12083.toml
Files vulnerabilities in the standard library originally reported at:
https://groups.google.com/forum/#!forum/rustlang-security-announcements
Or otherwise collected at:
https://github.com/RustSec/cargo-audit/issues/46
The `rustsec` crate doesn't presently consume these, but I'd like to add
support ASAP.
> File standard libary/core vulns (closes RustSec/cargo-audit#46)

- crates/renderdoc/RUSTSEC-0000-0000.toml
While updating the [renderdoc-rs](https://github.com/ebkalderon/renderdoc-rs) bindings a few months ago, I had identified several methods that were taking immutable reference to `self` but were actually making internally mutating [RenderDoc](https://renderdoc.org) API calls, which could potentially lead to undefined behavior.
This issue was corrected in the 0.5.0 release, and it was [recently suggested](https://github.com/ebkalderon/renderdoc-rs/issues/28#issuecomment-526860298) that I file a public advisory here, which was a very good idea.
I would appreciate any feedback in reporting this advisory properly, and I hope to report any such cases in a more timely manner in the future.
> Undefined behavior in renderdoc crate

- crates/blake2/RUSTSEC-0000-0000.toml
BLAKE2b and BLAKE2s were implemented using the wrong block size. All versions of the `blake2` crate prior to v0.8.1 compute incorrect digests.
See: https://github.com/RustCrypto/MACs/issues/19
> Add advisory for broken `blake2` impls

- crates/generator/RUSTSEC-0000-0000.toml
As asked for at Xudong-Huang/generator-rs/issues/9 (comment).
Some notes:
The new release fix several memory corruption APIs in some special cases by adding more checks. Some of the APIs were deprecated.
> Add advisory for generator

- Cargo.toml
- README.md
- crates/ammonia/RUSTSEC-2019-0001.toml
- crates/arrayfire/RUSTSEC-2018-0011.toml
- crates/blake2/RUSTSEC-2019-0019.toml
- crates/compact_arena/RUSTSEC-2019-0015.toml
- crates/hyper/RUSTSEC-2016-0002.toml
- crates/image/RUSTSEC-2019-0014.toml
- crates/libflate/RUSTSEC-2019-0010.toml
- crates/ncurses/RUSTSEC-2019-0006.toml
- crates/once_cell/RUSTSEC-2019-0017.toml
- crates/pancurses/RUSTSEC-2019-0005.toml
- crates/protobuf/RUSTSEC-2019-0003.toml
- crates/renderdoc/RUSTSEC-2019-0018.toml
- crates/safe-transmute/RUSTSEC-2018-0013.toml
- crates/simd-json/RUSTSEC-2019-0008.toml
- crates/smallvec/RUSTSEC-2019-0009.toml
- crates/smallvec/RUSTSEC-2019-0012.toml
- crates/spin/RUSTSEC-2019-0013.toml
- rust/std/CVE-2018-1000657.toml
- rust/std/CVE-2018-1000810.toml
- src/main.rs
Upgrades the `rustsec` crate to the latest alpha release and uses the new `rustsec::advisory::Linter` functionality to lint advisories currently in the database.
Several of them are using invalid keys and need to be updated.
Additionally, this corrects all advisories so they pass the linter.
> Upgrade to `rustsec` crate v0.13.0-alpha1; add linter

- crates/linea/RUSTSEC-0000-0000.toml
- crates/portaudio-rs/RUSTSEC-0000-0000.toml
Two unwind-safety problem was detected in crates mentioned above.
> Use-after-free in portaudio-rs and double free in linea

- crates/string-interner/RUSTSEC-0000-0000.toml
As asked for at <https://github.com/Robbepop/string-interner/issues/9#issuecomment-526857810>.
Some notes:
* I think the attacker can read some already dropped memory, not by direct access, but by brute-forcing.
I don't know how I can say it in the title.
* The fix is [already merged](https://github.com/Robbepop/string-interner/pull/10), but not yet released.
* I sent [another patch](https://github.com/Robbepop/string-interner/pull/12) to add an additional test that checks there are no dangling pointers in such situations, but it is not yet merged.
So I didn't write about it in the description.
* I'm not native English speaker, so feel free to point out if there are unnatural wordings.
> Add advisory for string-interner

- .travis.yml
- rust/cargo/CVE-2019-16760.toml
Original announcement: https://groups.google.com/forum/#!topic/rustlang-security-announcements/rVQ5e3TDnpQ
> Add CVE-2019-16760: Security advisory for Cargo (2019-09-30)

- rust/cargo/CVE-2019-16760.toml
Matches the advisory title used for:
https://github.com/rust-lang/rust/security/advisories/GHSA-phjm-8x66-qw4r
Also adds `GHSA-phjm-8x66-qw4r` as an alias
> CVE-2019-16760: update advisory title

- crates/hyper/RUSTSEC-2017-0002.toml
> Use backticks for escaped characters

- crates/libusb/RUSTSEC-0000-0000.toml
- crates/libusb/RUSTSEC-2016-0004.toml
No releases since 2016 and no responses from the author about its maintenance status; with several open PRs and issues:
https://github.com/dcuddeback/libusb-rs/issues/33
Recommending `rusb`, a maintained fork, as a successor:
https://github.com/a1ien/rusb
> Add unmaintained crate informational advisory: libusb

- crates/chan/RUSTSEC-0000-0000.toml
- crates/chan/RUSTSEC-2018-0014.toml
Officially deprecated by its author @BurntSushi:
https://github.com/BurntSushi/chan/commit/0a5c0d4ad4adc90a54ee04a427389acf2e157275
> Add unmaintained crate informational advisory: chan

- crates/term/RUSTSEC-0000-0000.toml
- crates/term/RUSTSEC-2018-0015.toml
The author of `term`, @Stebalien, has opened the following GitHub issue looking for a new maintainer:
https://github.com/Stebalien/term/issues/93
Ideally we can help find one by increasing visibility on this issue. Otherwise this advisory includes a list of possible alternatives.
> Add unmaintained crate informational advisory: term

- crates/rust-crypto/RUSTSEC-0000-0000.toml
- crates/rust-crypto/RUSTSEC-2016-0005.toml
No releases since May 2016, no commits since September 2016, with 62 open issues and 37 open PRs.
Author is unresponsive:
https://github.com/DaGenix/rust-crypto/issues/440
Advisory includes a large list of maintained "successor" crates: `rust-crypto` was a kitchen sink of functionality, so the advisory contains a list of potential successor crates each with an algorithm-by-algorithm breakdown of what they support.
> Add unmaintained crate informational advisory: rust-crypto

- crates/cassandra/RUSTSEC-0000-0000.toml
- crates/cassandra/RUSTSEC-2016-0006.toml
No releases since 2016 and no responses from the author about its maintenance status:
https://github.com/tupshin/cassandra-rs/issues/52
Recommending `cassandra-cpp`, a maintained fork, as a successor:
https://github.com/Metaswitch/cassandra-rs
> Add unmaintained crate informational advisory: cassandra

- crates/rustsec-example-crate/RUSTSEC-2019-0024.toml
This is a test advisory useful for verifying RustSec tooling and vulnerability detection pipelines are working correctly. Aside from the fact that it is filed against an example crate, it is otherwise
considered by the Advisory Database itself to be a normal security advisory.
It's filed against `rustsec-example-crate`, an otherwise completely empty crate with no functionality or code, which has two releases:
- [v0.0.1]: *vulnerable* according to this advisory
- [v1.0.0]: *patched* by this advisory
(Technically there is a third release, v0.0.0, which is yanked, but otherwise identical to the v0.0.1 release)
[v0.0.1]: https://crates.io/crates/rustsec-example-crate/0.0.1
[v1.0.0]: https://crates.io/crates/rustsec-example-crate/1.0.0
> RUSTSEC-2019-0024: Test advisory for `rustsec-example-crate` (closes #158)

- crates/rmpv/RUSTSEC-2017-0006.toml
Patched as of v0.4.2:
https://github.com/RustSec/advisory-db/pull/171#issuecomment-540169499
> RUSTSEC-2017-0006: rmpv: add patched versions

- crates/sodiumoxide/RUSTSEC-0000-0000.toml
https://github.com/sodiumoxide/sodiumoxide/pull/381
> PartialEq implementation for sodiumoxide::crypto::generichash::Digest has compared itself to itself

- crates/libsecp256k1/RUSTSEC-0000-0000.toml
https://github.com/paritytech/libsecp256k1/commit/11ba23a9766a5079918cd9f515bc100bc8164b50
> Flaw in Scalar::check_overflow allows side-channel timing attack

- crates/flatbuffers/RUSTSEC-2019-0024.toml
- crates/flatbuffers/RUSTSEC-2019-0028.toml
A couple of observations:
* There are still no released versions with a fix.
* The issue does not strictly fall into any particular criteria listed in https://github.com/RustSec/advisory-db/blob/master/CONTRIBUTING.md#criteria, but given the nature of this library the input is likely to be some untrusted external input over network or similar. This gives an attacker an easy vector to exploit UB which could subsequently result in execution of unintended branches in code, cause panics, or circumvent authorization checks, etc.
> Add a flatbuffers unsound code advisory

- crates/rust-crypto/RUSTSEC-2016-0005.toml
I'd like to propose that [orion](https://crates.io/crates/orion)(which I'm the author/maintainer of) be added to the list of alternative, maintained crates in the rust-crypto informational advisory.
> rust-crypto: Add orion as alternative

- crates/crust/RUSTSEC-0000-0000.toml
Hi, I was looking into p2p crates and the crate with the highest number of downloads has been archived on github so, I thought it would be useful for anyone that uses it to know it's unmaintained.
Anyway, I think I followed the steps correctly. Let me know if there's anything I need to change.
Thanks!
> Added RUSTSEC advisory for crust as an archived/unmaintained.

- crates/string-interner/RUSTSEC-2019-0023.toml
The fix https://github.com/Robbepop/string-interner/pull/10 released in 0.7.1 was also backported to the 0.6 release line in https://github.com/Robbepop/string-interner/pull/14 and released in 0.6.4.
> string-interner-0.6.4 also fixes RUSTSEC-2019-0023

- crates/spin/RUSTSEC-2019-0031.toml
https://github.com/oliver-giersch/conquer-once
> RUSTSEC-2019-0031: add `conquer-once` as an alternative to `spin`

- crates/http/RUSTSEC-0000-0000.toml
`HeaderMap::reserve()` used `usize::next_power_of_two()` to calculate the increased capacity. However, `next_power_of_two()` silently overflows to 0 if given a sufficently large number in release mode.
If the map was not empty when the overflow happens, the library will invoke `self.grow(0)` and start infinite probing. This allows an attacker who controls the argument to `reserve()` to cause a potential denial of service (DoS).
The flaw was corrected in 0.2.0 release of `http` crate.
> Add advisory for hyperium/http/issues/352

- crates/http/RUSTSEC-0000-0000.toml
Affected versions of this crate incorrectly used raw pointer, which introduced unsoundness in its public safe API.
[Failing to drop the Drain struct causes double-free](https://github.com/hyperium/http/issues/354), and [it is possible to violate Rust's alias rule and cause data race with Drain's Iterator implementation](https://github.com/hyperium/http/issues/355).
The flaw was corrected in 0.2.0 release of `http` crate.
> Add advisory for hyperium/http/issues/354,355

- crates/http/RUSTSEC-2019-0033.toml
- crates/http/RUSTSEC-2019-0034.toml
I believe these two vulnerabilities were patched at 0.1.20.
For RUSTSEC-2019-0033:
The advisory links to the bug: https://github.com/hyperium/http/issues/352
In that bug, the fixing PR was https://github.com/hyperium/http/pull/360
That PR merged the commit 81ceb61 to fix the bug; that commit, according to
GitHub, was first picked up by tag v0.1.20 ([commit][1]).
[1]: https://github.com/hyperium/http/commit/81ceb611cf96abe91d91693e813cd5ee36cdae02
For RUSTSEC-2019-0034:
This advisory is two separate GitHub issues against `HeaderMap::drain`,
http #354 and http #355.
For the first: the issue: https://github.com/hyperium/http/issues/354
In that bug, the fixing PR was https://github.com/hyperium/http/pull/357
That PR merged the commit 82d53db to fix the bug; that commit, according to
GitHub, …
> Correct affected version range on RUSTSEC-2019-003[34] to patched at 0.1.20

- crates/rust-crypto/RUSTSEC-2016-0005.toml
The `rust-crypto` crate and RustCrypto org have confusingly similar names, which has caused confusion about this advisory in practice:
https://www.reddit.com/r/rust/comments/e29sxc/ann_rustcryptoaead_v020_heapless_symmetric_aead/f8ujyxm/
This commit adds a small note to disambiguate them and note that RustCrypto-the-GitHub-org is still maintained.
> RUSTSEC-2016-0005: add note about rust-crypto vs RustCrypto

- crates/quickersort/RUSTSEC-0000-0000.toml
The author of the [`quickersort`](https://crates.io/crates/quickersort) crate has deprecated it and do not recommend using it anymore.
Everything in it has been incorporated into std::sort_unstable in the standard library as of Rust 1.20.
> Add advisory for deprecated/unmaintained quickersort

- crates/rust_sodium/RUSTSEC-0000-0000.toml
rust_sodium is unmaintained, as per [repository readme](https://github.com/maidsafe/rust_sodium#please-note-that-the-rust_sodium-crate-is-no-longer-maintained-switch-to-a-modern-alternative)
> Add unmaintained crate informational advisory: rust_sodium

- crates/lucet-runtime-internals/RUSTSEC-0000-0000.toml
Hello,
This PR is for a security advisory in https://github.com/bytecodealliance/lucet, /cc @acfoltzer.
I am not sure about the format used in the `patched_versions` value. If that is incorrect could you please advise?
If you need anything else on this just let me know.
Thanks,
Jon
> Add lucet-runtime-internals sigstack allocation vuln advisory

- .github/workflows/validate.yml
Installing `rustsec-admin` to lint the advisory DB takes an awfully long time. This caches it with a key labeled with the version so it can reuse the cached version if available.
> .github: cache installation of rustsec-admin

- .github/workflows/validate.yml
Fixes use of the cached `rustsec-admin` binary, which was added in #237
> .github: fix rustsec-admin install caching

- rust/cargo/CVE-2019-16760.toml
- rust/rustdoc/CVE-2018-1000622.toml
- rust/std/CVE-2018-1000657.toml
- rust/std/CVE-2018-1000810.toml
- rust/std/CVE-2019-12083.toml
The migration in #236 only handled the `crates/` advisories, not the ones in `rust/`.
This commit completes the migration.
> Migrate `rust/` advisories to V2 format

- crates/rust-crypto/RUSTSEC-2016-0005.toml
When migrating a codebase off of rust-crypto, I encountered a few uses of the md5 digest, and realized that it was missing from this advisory.
Since deprecations are good onboarding tasks for folks new to rust (like me), I figured it would be helpful to explicitly state here that RustCrypto has an `md-5` crate you can use as (almost) a drop-in replacement
> Add `md5` to RustCrypto digest crates

- crates/rust-crypto/RUSTSEC-2016-0005.toml
https://www.kb.cert.org/vuls/id/836068/
> RUSTSEC-2016-0005: move `md-5` crate to legacy algorithms

- crates/flatbuffers/RUSTSEC-2019-0028.toml
This patch updates the `RUSTSEC-2019-0028` advisory to show a patched version is available. The patch was added [in PR 5554](https://github.com/google/flatbuffers/pull/5554), and released with version `0.6.1`.
> fix: update patched version for 2019-0028

- crates/hyper/RUSTSEC-2020-0008.toml
The vulnerability description for advisory RUSTSEC-2020-0008, "Flaw in
hyper allows request smuggling by sending a body in GET requests", lists
an incorrect patched version. The advisory states that the vulnerability
was fixed in `hyper` 0.12.35, but `hyper`'s changelog [shows][1] that 
the patch (hyperium/hyper@23fc8b0) was published in 0.12.34. I believe
that this means that `cargo audit` will incorrectly report patched 
versions as vulnerable.
This PR corrects the listed version.
[1]: https://github.com/hyperium/hyper/blob/master/CHANGELOG.md#v01234-2019-09-04
> Fix patched version for RUSTSEC-2020-0008

- crates/plutonium/RUSTSEC-0000-0000.toml
I think it's good that cargo-audit reports this. [Reported first at cargo-geiger](https://github.com/rust-secure-code/cargo-geiger/issues/101) where it was suggested this was more for cargo-audit.
> Advisory for plutonium.

- crates/rusqlite/RUSTSEC-0000-0000.toml
For work I completed an audit of rusqlite's unsafe code. There were a number of issues for various issues, most of them in uncommonly used APIs, but they could be fairly severe nonetheless.
I'd... prefer not to split this out among N separate advisories. Mostly because I'm lazy, but I also don't really see the benefit it would give. (Aside from making the `description` better, I guess)
Note that while VTab/VTabCursor not being unsafe traits isn't listed in the `functions`, you need to use `create_module` in order to expose that so it should be fine.
> Add advisory for rusqlite

- crates/plutonium/RUSTSEC-2020-0011.toml
I still personally believe this advisory should be marked obsolete with a note in the description along the lines of explaining how it got in and pointing people to use `cargo-crev` for this kind of concern.
However, this rewording of the advisory seems objectively better and more correct about what `plutonium` actually offers.
> RUSTSEC-2020-0011: make wording more objective

- crates/plutonium/RUSTSEC-2020-0011.toml
See discussion in https://github.com/RustSec/advisory-db/issues/275
Fundamentally, this is a bug in `cargo-geiger`. If `cargo-geiger` users care about this, they should either retool `cargo-geiger` to handle this, or have the tool notice this crate itself and handle it specially. Unsafe is not a security issue, it is a security _smell_, and this database is about security issues. 
I also strongly agree with @CAD97's comment [here](https://github.com/RustSec/advisory-db/issues/275#issuecomment-619446580), we should stick to objective advisories. There are other tools for dealing with crate trust. I feel like the inclusion of this crate in this database feels like a lowering of standards, and for a security database to work it needs to have people to trust its objectivity.
I think it is a …
> RUSTSEC-2020-0011: make obsolete (closes #275)

- README.md
`cargo-deny` is an awesome tool, it seems to be the superset of `cargo-audit`. I think it is reasonable to mention it here along with `cargo-audit`.
cc @Jake-Shadle
> Add `cargo-deny` to the list of RustSec clients

- crates/net2/RUSTSEC-0000-0000.toml
> net2 crate has been deprecated; use socket2 instead

- crates/tempdir/RUSTSEC-0000-0000.toml
The functionality of `tempdir` crate has been merged into `tempfile` which should be used instead.
> tempdir crate has been deprecated since 2018-02-13

- crates/internment/RUSTSEC-0000-0000.toml
`internment` 0.3.12 has a race condition in ArcIntern::drop which can
result in use-after-free.
> Add advisory for internment

- .github/workflows/validate.yml
...to match the new `rustsec-admin` v0.2.0 release:
https://github.com/RustSec/rustsec-admin/pull/57
> .github: bump rustsec-admin cache key

- .github/workflows/assign-ids.yml
Untested, and won't work until the rustec-admin release happens and we bump the versions in this. But it's got all the right pieces I think.
> Create github action to assign RUSTSEC ids

- crates/memoffset/RUSTSEC-2019-0011.toml
To cause the drop of uninit memory clients had to panic in a `Deref` implementation. That sounds like a sufficiently "uncommon" library usage to me that this probably should be just informational.
> make memoffset advisory informational

- .github/workflows/assign-ids.yml
It seems that when using `peter-evans/create-pull-request` with the default `GITHUB_TOKEN` won't run the lint action after opening the pull request.
To make up for that, we can run the lint immediately prior to opening the pull request to make sure something didn't go wrong when assigning the ID.
> .github: lint advisories after assigning ID

- crates/ozone/RUSTSEC-0000-0000.toml
Ozone contains several memory safety issues including [out-of-bound access](https://github.com/bqv/ozone/blob/e21f948b0178ab305f644118f18d87a838c618e0/src/buffer.rs#L38-L48) and dropping of [uninitialized memory](https://github.com/bqv/ozone/blob/e21f948b0178ab305f644118f18d87a838c618e0/src/map.rs#L94-L101).
---
I'm not sure whether this crate is popular enough to file an advisory. Is there any guideline in that aspect?
> Security advisory for bqv/ozone

- crates/rulinalg/RUSTSEC-0000-0000.toml
The affected version of `rulinalg` has incorrect lifetime boundary definitions for `RowMut::raw_slice` and `RowMut::raw_slice_mut`. They do not conform with Rust's borrowing rule and allows the user to create multiple mutable references to the same location.
https://github.com/AtheMathmo/rulinalg/issues/201
The incorrectness of `raw_slice_mut()` is straightforward. However, I'm not completely sure about `raw_slice()`. [Naively downgrading mut refs to shared refs is semantically incorrect](https://github.com/pretzelhammer/rust-blog/blob/master/posts/common-rust-lifetime-misconceptions.md#9-downgrading-mut-refs-to-shared-refs-is-safe), and that's why I think `raw_slice()` should be fixed, too. However, I'm not completely sure about it and any input to this is appreciated.
Also, there was a …
> Security advisory for AtheMathmo/rulinalg#201

- crates/tough/RUSTSEC-0000-0000.toml
https://github.com/awslabs/tough/security/advisories/GHSA-5q2r-92f9-4m49
> tough: CVE-2020-15093 / GHSA-5q2r-92f9-4m49

- crates/bigint/RUSTSEC-0000-0000.toml
This is an alternative to https://github.com/RustSec/advisory-db/pull/290.
Cc @ordian
> bigint is unmaintained

- crates/smallvec/RUSTSEC-0000-0000.toml
Fixes https://github.com/RustSec/advisory-db/issues/299
> add smallvec unsoundness

- crates/rocket/RUSTSEC-0000-0000.toml
The affected version of `rocket` contains a `Clone` trait implementation of `LocalRequest` that reuses the pointer to inner `Request` object. This causes data race in rare combinations of APIs if the original and the cloned objects are modified at the same time.
https://github.com/SergioBenitez/Rocket/issues/1312
> Informational advisory for SergioBenitez/Rocket#1312

- crates/failure/RUSTSEC-0000-0000.toml
The current `Failure` API allows safe Rust code to implement malfunctioning `__private_get_type_id__` and cause type confusion when downcasting, which is an undefined behavior.
https://github.com/rust-lang-nursery/failure/issues/336
> Informational advisory for rust-lang-nursery/failure#336

- crates/mozwire/RUSTSEC-0000-0000.toml
fix committed but not released yet.
> Missing sanitazion in mozwire allows local file overwrite of files ending in .conf

- crates/alpm-rs/RUSTSEC-0000-0000.toml
`StrcCtx` deallocate a memory region that it doesn't own when `StrcCtx` is created without using `StrcCtx::new`.
This can introduce memory safety issues such as double-free and use-after-free to client programs.
Original issue report: https://github.com/pigeonhands/rust-arch/issues/2
> StrcCtx deallocates a memory region that it doesn't own

- crates/alg_ds/RUSTSEC-0000-0000.toml
`Matrix::new()` internally calls `Matrix::fill_with()` which uses `*ptr = value` pattern to initialize the buffer.
This pattern assumes that there is an initialized struct at the address and drops it, which results in dropping of uninitialized struct.
Original issue report: https://gitlab.com/dvshapkin/alg-ds/-/issues/1
> Matrix::new() drops uninitialized memory

- crates/arr/RUSTSEC-0000-0000.toml
`arr` crate contains multiple security issues. Specifically,
1. It incorrectly implements Sync/Send bounds, which allows to smuggle non-Sync/Send types across the thread boundary.
2. `Index` and `IndexMut` implementation does not check the array bound.
3. `Array::new_from_template()` drops uninitialized memory.
Original issue report: https://github.com/sjep/array/issues/1
> arr: Multiple security issues including data race, buffer overflow, and uninitialized memory drop

- crates/chunky/RUSTSEC-0000-0000.toml
Chunk API does not respect the align requirement of types. Unaligned reference can be created with the API, which is an undefined behavior.
Original issue report: https://github.com/aeplay/chunky/issues/2
> chunky: Chunk API does not respect align requirement

- crates/failure/RUSTSEC-0000-0000.toml
Closes #284. See also:
- https://internals.rust-lang.org/t/failure-crate-maintenance/12087
- https://github.com/rust-lang-nursery/failure/pull/347
> failure: add informational "unmaintained" advisory

- crates/failure/RUSTSEC-2020-0036.toml
When I originally filed this I used the list of alternatives that were mentioned in the rust-internals announcement. That said, `fehler` is another notable one by the same author as `failure`.
> RUSTSEC-2020-0036: add fehler

- crates/crayon/RUSTSEC-0000-0000.toml
Unsafe code in `ObjectPool` has time-of-check to time-of-use (TOCTOU) bug that can eventually lead to a memory safety violation. `ObjectPool` and `HandlePool` implicitly assumes that `HandleLike` trait methods are pure, i.e., they always return the same value. However, this assumption is unsound since `HandleLike` is a safe, public trait that allows a custom implementation.
Original issue report: https://github.com/shawnscode/crayon/issues/87
> crayon: Misbehaving `HandleLike` implementation can lead to memory safety violation

- crates/simple-slab/RUSTSEC-0000-0000.toml
`Slab::index()` does not perform the boundary checking, which leads to out-of-bound read access. `Slab::remove()` copies an element from an invalid address due to off-by-one error, resulting in memory leakage and uninitialized memory drop.
Original issue report: https://github.com/nathansizemore/simple-slab/issues/2
> simple-slab: `index()` allows out-of-bound read and `remove()` has off-by-one error

- crates/obstack/RUSTSEC-0000-0000.toml
Obstack generates unaligned references for types that require a large alignment.
Original issue report: https://github.com/petertodd/rust-obstack/issues/4
> obstack: Obstack generates unaligned references

- crates/simple-slab/RUSTSEC-2020-0039.toml
Fixed by https://github.com/nathansizemore/simple-slab/commit/5e0524c1db836e2192e1cd818848d96937c0b587
> Update patched version of 0013-simple-slab

- crates/sized-chunks/RUSTSEC-0000-0000.toml
Chunk:
* Array size is not checked when constructed with `unit()` and `pair()`.
* Array size is not checked when constructed with `From<InlineArray<A, T>>`.
* `Clone` and `insert_from` are not panic-safe; A panicking iterator causes memory safety issues with them.
InlineArray:
* Generates unaligned references for types with a large alignment requirement.
Original issue report: https://github.com/bodil/sized-chunks/issues/11
> sized-chunks: Multiple soundness issues in Chunk and InlineArray

- crates/failure/RUSTSEC-2019-0036.toml
looks like some confusion if the CVE is about this or RUSTSEC-2020-0036, but it looks like this is the actual security hole
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25575
> added CVE numbers

- crates/stack/RUSTSEC-0000-0000.toml
Upstream issue: https://github.com/arcnmx/stack-rs/issues/4
It's a fairly simple out-of-bounds write caused by a missing check on the array's length.
> Add advisory for out-of-bounds write in stack crate

- crates/ws/RUSTSEC-0000-0000.toml
We've recently been made aware that the memory leak we were seeing in the rpc components in one of our software comes from the `ws`-crate and can even be exploited to kill the process by forcing it to allocate too much memory.
Unfortunately, despite us attempting to contact the original authors of the crate, and the providing a patch, a fixed version has not been published yet. We have a published [a fork](https://crates.io/crates/parity-ws) with the [patch applied however](https://github.com/housleyjk/ws-rs/pull/328), but the advisory format doesn't quite allow us to specify that. The [problem itself has been reported over a year ago on the repository](https://github.com/housleyjk/ws-rs/issues/291) and is included in the latest published version. An [attempt to hand over maintainership …
> Insufficient size checks in outgoing buffer in `ws` allows remote attacker to run the process out of memory

- crates/atom/RUSTSEC-0000-0000.toml
Upstream issue: https://github.com/slide-rs/atom/issues/13
It looks like this vulnerability was fixed in the Github code but a new release was never pushed to cargo with it. The code snippet in the upstream issue presents an `Rc` used across thread-boundaries. Since this library is meant to be for concurrent/multi-thread access, this mistake of accidentally sending across a non `Send` type seems like an easy one to make and can lead to memory corruption issues.
> Add advisory for atom crate

- crates/array-queue/RUSTSEC-0000-0000.toml
Upstream issue: https://github.com/raviqqe/array-queue/issues/2
There's an indexing problem in the `pop_back()` function allowing a read from uninitialized or previously dropped memory. As demonstrated on the upstream issue, this can be leveraged for an arbitrary read and potentially write.
> Add advisory for out-of-bounds read in array-queue.

- crates/dync/RUSTSEC-0000-0000.toml
Upstream issue: https://github.com/elrnv/dync/issues/4
This is an unsoundness informational advisory. As shown under miri in the issue above, the `VecCopy` type in the `dync` crate allows for misaligned access as it treats everything as a `u8` underneath.
> Add misaligned-access soundness issue for dync crate

- README.md
- crates/rustsec/RUSTSEC-0000-0000.toml
In theory this advisory should trigger this feature of `cargo-audit` which checks for advisories filed against the `rustsec` crate:
https://github.com/RustSec/cargo-audit/blob/783f221/src/auditor.rs#L178-L199
After merging, I will test with an older `cargo-audit` version to see if it has the intended effect.
> Add `rustsec` crate advisory for breaking changes to advisory format

- crates/plutonium/RUSTSEC-2020-0011.toml
> RUSTSEC-2020-0011: rename `obsolete` to `yanked`

- .github/workflows/assign-ids.yml
I imagine it might still be broken after this... will take a look if so
> CI: use rustsec-admin v0.3.0-pre in assign-ids step

- crates/atom/RUSTSEC-2020-0044.md
As per https://github.com/slide-rs/atom/issues/13#issuecomment-704110075, version `0.3.6` of atom now contains the fix for the soundness issue.
> Add patched version for atom crate.

- crates/spin/RUSTSEC-2019-0031.md
We added `yanked = true` to the advisory, however it doesn't seem to behaving the intended effect (the query for unmaintained crates is probably failing to exclude the yanked advisories)
This is another workaround which makes the `unaffected` requirement match all versions. Hopefully this means that `spin` will stop being reported as unmaintained.
> RUSTSEC-2019-0031: spin is maintained

- crates/crossbeam-channel/RUSTSEC-0000-0000.md
The affected version of this crate's the `bounded` channel incorrectly assumes that `Vec::from_iter` has allocated capacity that same as the number of iterator elements. `Vec::from_iter` does not actually guarantee that and may allocate extra memory. The destructor of the `bounded` channel reconstructs `Vec` from the raw pointer based on the incorrect assumes described above. This is unsound and causing deallocation with the incorrect capacity when `Vec::from_iter` has allocated different sizes with the number of iterator elements.
Refs: https://github.com/crossbeam-rs/crossbeam/pull/533, https://github.com/crossbeam-rs/crossbeam/issues/539 (Both issues are mainly saying about crossbeam-queue, but crossbeam-queue including this UB, has not been released and only crossbeam-channel is …
> Add advisory for UB in crossbeam-channel 0.4.3

- crates/crossbeam-channel/RUSTSEC-2020-0052.md
manually, since automatic assignment is broken
> Assign RUSTSEC-2020-0052 to crossbeam-channel

- crates/dync/RUSTSEC-2020-0050.md
The [soundness issue](https://github.com/elrnv/dync/issues/4) was resolved in a newly published version, which removes the need to store underlying data in `Vec<u8>` altogether.
The short explanation is that data is now represented using a void pointer and correctly manipulated using custom properly aligned types.
The presented example which found the issue is now included as a test which runs in CI.
Also remaining tests are now run through miri in CI.
> Add patch version for the unsoundness issue in dync

- crates/directories/RUSTSEC-0000-0000.md
- crates/dirs/RUSTSEC-0000-0000.md
Both of these crates have had their repos archived and unarchived a few times which prompted the forks. The forked crates look to be drop in replacements and I have not run into issues with them so far.
> dirs and directories crates are unmaintained

- crates/crossbeam-channel/RUSTSEC-2020-0052.md
Refs: https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-v5m7-53cv-f3hx, [CVE-2020-15254](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15254)
> Add CVE and GHSA to RUSTSEC-2020-0052

- crates/libpulse-binding/RUSTSEC-2018-0020.md
- crates/libpulse-binding/RUSTSEC-2020-0055.md
It was accidentally filed under the wrong year.
> Rename RUSTSEC-2020-0055 to RUSTSEC-2018-0020

- EXAMPLE_ADVISORY.md
- README.md
Adds an example advisory in the V3 format (#414) and updates the schema information in README.md to reflect that.
> Add EXAMPLE_ADVISORY.md

- .github/workflows/assign-ids.yml
- .github/workflows/validate.yml
This version has the old TOML advisories fail lint, and also hopefully fixes automatic ID assignment.
> CI: bump rustsec-admin to v0.3.0-pre2

- crates/block-cipher/RUSTSEC-0000-0000.md
It's been renamed to `cipher`.
> Add unmaintained crate advisory for `block-cipher`

- crates/stream-cipher/RUSTSEC-0000-0000.md
It's been renamed to `cipher`.
> Add unmaintained crate advisory for `stream-cipher`

- crates/libpulse-binding/RUSTSEC-0000-0000.md
I wasn't sure how to differentiate an UB entry from a security entry... The reporting guidelines clearly say that unsoundness/UB issues can be reported regardless of whether or not they are vulnerabilities. I think this one counts as a noteworthy issue.
> Add advisory for notable UB fix in libpulse-binding v2.6.0

- crates/plutonium/RUSTSEC-2020-0011.md
This advisory is featured in the `plutonium` rustdoc:
https://docs.rs/plutonium/
It'd be a shame to have the link 404.
> Unyank RUSTSEC-2020-0011

- crates/openssl-src/RUSTSEC-2020-0015.md
`semver` v0.11 is having trouble parsing these requirements.
> RUSTSEC-2020-0015: use wildcards in version req

- crates/openssl-src/RUSTSEC-2020-0015.md
They're breaking the parser:
https://github.com/RustSec/rustsec-crate/pull/244/checks?check_run_id=1305962917
> RUSTSEC-2020-0015: remove wildcards

- crates/futures-util/RUSTSEC-0000-0000.md
Adds an advisory to cover a [recently discovered data race](https://github.com/rust-lang/futures-rs/issues/2239) in `future-util`'s `MappedMutexGuard` API.
1/4 of https://github.com/RustSec/advisory-db/issues/454
> Add advisory for data race fix in futures-util

- crates/futures-task/RUSTSEC-0000-0000.md
Adds an advisory to cover a potential use-after-free  in future-task's `waker` API that never received an advisory when it was fixed a month ago.
Edit: The workspace of `futures` threw me off with the original crate name.
2/4 of #454
> Add advisory for use-after-free in futures_task::waker

- crates/futures-task/RUSTSEC-0000-0000.md
Adds an advisory for a [potential sefault due to a null pointer dereference](https://github.com/rust-lang/futures-rs/pull/2095) in futures-task when the waker  from `noop_waker_ref()` has `wake_by_ref` called on it from a different thread then it was created on. 
An advisory was never added for it back when it was fixed in March.
3/4 of #454
> Add advisory for potential null pointer deref in futures-task

- crates/futures-util/RUSTSEC-0000-0000.md
Adds an advisory for an [unsound `Sync` implementation](https://github.com/rust-lang/futures-rs/pull/2054) on `futures_util::stream::FuturesUnordered` that could cause memory corruption when insertions occur from >1 thread at the same time.
No advisory was added for this issue when it was originally fixed back in January this year.
4/4 of #454 
Closes #454
> Add advisory for unsound Sync impl on FuturesUnordered in futures-util

- crates/safe-nd/RUSTSEC-0000-0000.md
It's been renamed to `sn_data_types`
> Add unmaintained crate advisory for `safe-nd`

- crates/ffi_utils/RUSTSEC-0000-0000.md
It's been renamed to `sn_ffi_utils`
> Add unmaintained crate advisory for `ffi_utils`

- crates/fake_clock/RUSTSEC-0000-0000.md
It's been renamed to `sn_fake_clock`
> Add unmaintained crate advisory for `fake_clock`

- crates/safe_bindgen/RUSTSEC-0000-0000.md
It's been renamed to `sn_bindgen`
> Add unmaintained crate advisory for `safe_bindgen`

- crates/quic-p2p/RUSTSEC-0000-0000.md
> Add unmaintained crate advisory for `quic-p2p`

- crates/multihash/RUSTSEC-0000-0000.md
This has been fixed for a while now (see the [url from the report](https://github.com/multiformats/rust-multihash/pull/72)), but it only recently occurred to us that it can cause a remotely-triggered DoS in libp2p and other consumers.
So I put today into the `date` field; feel free to correct me, a fixed version of `multihash` has been released on August 29, 2020.
> Unexpected panic in multihash `from_slice` parsing code

- crates/multihash/RUSTSEC-2020-0068.md
It's breaking `cargo-deny` which hasn't updated to the new parser yet
> RUSTSEC-2020-0068: remove parameters from affected functions

- README.md
Well, the frontmatter is, but that's noted in the section below this one already, so no need for duplicate information.
> README.md: advisories are no longer TOML-formatted

- crates/lettre/RUSTSEC-0000-0000.md
Not sure about how to specify the affected versions over several branches.
> Add advisory for lettre sendmail transport

- crates/lock_api/RUSTSEC-0000-0000.md
Upstream issues:
* https://github.com/Amanieu/parking_lot/issues/258
* https://github.com/Amanieu/parking_lot/issues/259
Pretty similar to https://github.com/RustSec/advisory-db/pull/455 where the Mapped Guard variants were not considering the mapped-to types when it came to the concurrency traits.
> Report soundness bug with lock_api

- crates/futures-intrusive/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/Matthias247/futures-intrusive/issues/53
This is a soundness issue with a `Sync` trait that allows data races with the lock guard object. Very similar to one reported in the standard library's [own mutex guard](https://github.com/rust-lang/rust/issues/41622).
> Report soundness bug with concurrency in futures-intrusive

- README.md
- crates/hyper/RUSTSEC-2016-0002.md
- crates/slice-deque/RUSTSEC-2019-0002.md
- crates/tough/RUSTSEC-2020-0024.md
This frees up `references` to be used for tracking multiple URLs with additional information.
See also: RustSec/advisory-db#429
> Rename `references` fields to `related`

- crates/pnet/RUSTSEC-2019-0037.md
See https://github.com/RustSec/advisory-db/pull/335#discussion_r531670273
> Fix patched version of RUSTSEC-2019-0037

- crates/routing/RUSTSEC-0000-0000.md
Has been renamed to `sn_routing`.
> Add unmaintained crate advisory for `routing`

- crates/net2/RUSTSEC-0000-0000.md
Hello! This "vulnerability" is not exploitable right now. But it will cause invalid memory access when the standard library changes how `SocketAddr` is implemented. See https://github.com/rust-lang/rust/pull/78802 for details.
I'm aiming to follow this advisory up with very similar ones on `socket2`, `miow` and `mio` since they contain more or less the exact same problem. But I will start with one until we have agreed on the content and format since they will likely be very similar. I can add all the others to the same PR if you prefer that.
I was not sure what `categories` to apply to this, if any. Since it's a little bit unclear how this could be exploitable in the future. It more or less depends on what the standard library changes the memory representation into. But since it was …
> Add advisory on net2 making invalid memory assumptions

- crates/socket2/RUSTSEC-0000-0000.md
Same thing as #503 
I found I had spelled "addresses" wrong in the last advisory on `net2`. But since you said the CI might not handle two crates at the same time I did not fix it here and now.
> Add advisory on socket2 about casting SocketAddr

- crates/miow/RUSTSEC-0000-0000.md
Same thing as #505  and #503 
This crate had to be fixed in two minor releases. That's the only difference really.
> Add advisory on miow SocketAddr casting

- crates/mio/RUSTSEC-0000-0000.md
Same as #507 
I realized one thing: When `patched` is filled in this way, it will only warn people with `0.7.x` versions in their lockfiles where `x<6`, right? It won't start alarming users of `mio 0.6` or other minor releases?
> Add advisory on mio SocketAddr casting

- crates/ordered-float/RUSTSEC-0000-0000.md
After using an assignment operators such as `NotNan::add_assign`, `NotNan::mul_assign`, etc., it was possible for the resulting `NotNan` value to contain a `NaN`.  This could cause undefined behavior in safe code, because the safe `NotNan::cmp` method contains internal unsafe code that assumes the value is never `NaN`.  (It could also cause undefined behavior in third-party unsafe code that makes the same assumption, as well as logic errors in safe code.)
This was mitigated starting in version 0.4.0, by panicking if the assigned value is NaN.  However, in affected versions from 0.4.0 onward, code that continued after using unwinding to catch this panic could still observe the invalid value and trigger undefined behavior.
The flaw is fully corrected in versions 1.1.1 and 2.0.1, by ensuring …
> ordered_float:NotNan may contain NaN after unwinding in assignment operators

- crates/ordered-float/RUSTSEC-2020-0082.md
Follow-up to #514.  Clarify that UB can happen during unwinding, and not only after catching a panic.
> Minor changes to wording of RUSTSEC-2020-0082

- EXAMPLE_ADVISORY.md
Perhaps we could be a little more descriptive about the desired properties of good advisories in the example.
The main motivation for this PR is an observation of a few cases where people interpret the last line as to give credits to the bug reporter in advisories, which I believe unintentional.
- [RUSTSEC-2019-0021](https://github.com/RustSec/advisory-db/blob/master/crates/linea/RUSTSEC-2019-0021.md)
- [RUSTSEC-2019-0035](https://github.com/RustSec/advisory-db/blob/master/crates/rand_core/RUSTSEC-2019-0035.md)
- [RUSTSEC-2020-0069](https://github.com/RustSec/advisory-db/blob/master/crates/lettre/RUSTSEC-2020-0069.md)
These are the properties that I can think of right now. Please provide feedback and suggestions. And as always, thank you for all the maintenance effort :)
> Make the example advisory more descriptive

- crates/try-mutex/RUSTSEC-0000-0000.md
Original issue report: https://github.com/mpdn/try-mutex/issues/2
> try-mutex: TryMutex<T> allows sending non-Send type across threads

- crates/magnetic/RUSTSEC-0000-0000.md
Original issue report: https://github.com/johnshaw/magnetic/issues/9
> magnetic: MPMCConsumer/Producer allows sending non-Send type across threads

- crates/thex/RUSTSEC-0000-0000.md
Crate: https://crates.io/crates/thex
No upstream issue for this since the repository for this crate seems to have vanished. It used to be at https://github.com/krl/thex but it seems to have been deleted and there hasn't been a release for a long time. (Pinging @krl, not sure if this repo has moved but just fyi you can [yank](https://doc.rust-lang.org/cargo/commands/cargo-yank.html) old unmaintained crates)
Here's a quick little proof-of-concept that segfaults from safe rust code:
```rust
#![forbid(unsafe_code)]
use thex::Thex;
use std::rc::Rc;
fn main() {
let rc = Rc::new(());
let rc_clone = rc.clone();
let thex = Thex::new(rc_clone);
std::thread::spawn(move || {
let smuggled_rc = thex.shared();
println!("Thread: {:p}", *smuggled_rc);
// Race the refcount with the main thread.
for _ in …
```
> Add advisory for data race in thex

- crates/libpulse-binding/RUSTSEC-2020-0055.md
Mistake from fb2a1a6c4772485b519c21c10d1246e13e986f88
> Fix wrong url

- crates/concread/RUSTSEC-0000-0000.md
Original issue report: https://github.com/kanidm/concread/issues/48
PR that fixed the issue: https://github.com/kanidm/concread/pull/49
Thank you for reviewing this PR :crab:
> concread: Send/Sync bound needed on V in `impl Send/Sync for ARCache<K, V>`

- crates/arc-swap/RUSTSEC-2020-0091.md
https://nvd.nist.gov/vuln/detail/CVE-2020-35711
> Add CVE number for RUSTSEC-2020-0091

- crates/mdbook/RUSTSEC-0000-0000.md
This PR adds https://groups.google.com/g/rustlang-security-announcements/c/3-sO6of29O0 to RustSec.
> Add CVE-2020-26297 to mdBook <= 0.4.4

- .github/workflows/assign-ids.yml
- .github/workflows/validate.yml
- README.md
Should address the bug we encountered assigning an ID to the first advisory for a given year:
https://github.com/RustSec/advisory-db/runs/1644743652
> Bump rustsec-admin to v0.3.3

- crates/interfaces2/RUSTSEC-0000-0000.md
interfaces2 is not maintained now, and I took over the maintenance of the original interfaces crate.
https://github.com/aep/interfaces-rs
> Add advisory for interfaces2

- crates/reffers/RUSTSEC-0000-0000.md
Original issue report: https://github.com/diwic/reffers-rs/issues/7
Commit that fixed the issue: https://github.com/diwic/reffers-rs/commit/6dd7ca0d50f2464df708975cdafcfaeeb6d41c66
Thank you for reviewing this PR :+1:
> add advisory for data race in 'reffers'

- crates/smallvec/RUSTSEC-0000-0000.md
A bug in the `SmallVec::insert_many` method caused it to allocate a buffer that was smaller than needed.  It then wrote past the end of the buffer, causing a buffer overflow and memory corruption on the heap.
This bug was only triggered if the iterator passed to `insert_many` yielded more items than the lower bound returned from its `size_hint` method.
The flaw was corrected in smallvec 0.6.14 and 1.6.1, by ensuring that additional space is always reserved for each item inserted.  The fix also simplified the implementation of `insert_many` to use less unsafe code, so it is easier to verify its correctness.
Thank you to Yechan Bae (@Qwaz) and the Rust group at Georgia Tech’s SSLab for finding and reporting this bug.  See https://github.com/servo/rust-smallvec/issues/252 for more details.
> smallvec: Buffer overflow in insert_many

- crates/internment/RUSTSEC-2020-0017.md
The vulnerability in this report was fixed in internment 0.4.0.  For details, see https://github.com/droundy/internment/issues/11#issuecomment-758862385.
This advisory was originally created in https://github.com/RustSec/advisory-db/pull/306.
> RUSTSEC-2020-0017.md (use-after-free in internment) is fixed

- .github/workflows/publish-web.yml
We do still need to check if `rustsec-admin` is installed, as an error is returned if it's already installed.
> Publish Web: fix rustsec-admin install

- crates/lazy-init/RUSTSEC-0000-0000.md
Add an informational advisory for a long-standing soundness issue that has recently been fixed (https://github.com/khuey/lazy-init/commit/ab2cac8383a499be6700244cd2682f55c120f4a7).
> lazy-init: Missing Send bound for Lazy (khuey/lazy-init#9)

- crates/glsl-layout/RUSTSEC-0000-0000.md
link to PR (explanation of bug && fix): https://github.com/rustgd/glsl-layout/pull/10
Thank you for reviewing this PR! :crab:
> glsl-layout: double drop upon panic in 'fn map_array'

- crates/im/RUSTSEC-0000-0000.md
Original issue report: https://github.com/bodil/im-rs/issues/157
`informational = "unsound"` because typical users are expected to use it
through [Focus](https://docs.rs/im/15.0.0/im/vector/enum.Focus.html)
which has a correct bound.
> im: TreeFocus lacks bounds on its Send and Sync traits

- crates/xcb/RUSTSEC-0000-0000.md
Original issue report: https://github.com/rtbo/rust-xcb/issues/93
> xcb: Soundness issue with base::Error

- crates/rusb/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/a1ien/rusb/issues/44
Marked `informational = unsound` because it's unlikely that users of the library would be implementing `UsbContext` themselves.
> Add advisory for soundness issue in rusb

- crates/aovec/RUSTSEC-0000-0000.md
Crate: https://crates.io/crates/aovec
Much like #523, the repo for this crate seems to 404 now so there's no upstream issue here. The vector provided by this crate implements `Send` and `Sync` unconditionally which allows for data races.
Here's a simple demonstration that segfaults safe Rust code using this crate:
```rust
#![forbid(unsafe_code)]
use aovec::Aovec;
use std::rc::Rc;
fn main() {
let vec = Aovec::new(1);
let rc = Rc::new(42);
vec.push(rc.clone());
std::thread::spawn(move || {
println!("Thread: {:p}", vec[0]);
for _ in 0..100_000_000 {
vec[0].clone();
}
});
println!("Main:   {:p}", rc);
for _ in 0..100_000_000 {
rc.clone();
}
}
```
Output:
```
Main:   0x5639ef979b50
Thread: 0x5639ef979b50
Terminated with signal 4 (SIGILL)
```
> Add advisory for data race in aovec

- crates/av-data/RUSTSEC-0000-0000.md
Original issue report: https://github.com/rust-av/rust-av/issues/136
Thank you for reviewing :crab:
> av-data: read from arbitrary address in safe API

- crates/sys-info/RUSTSEC-0000-0000.md
[This issue](https://github.com/FillZpp/sys-info-rs/issues/63) has been open for some time. All published versions of `sys-info` have this issue. The crate also appears unmaintained and has various correctness issues, so a a fixed version is probably unlikely.
> Add advisory for double-free in sys-info

- crates/autorand/RUSTSEC-0000-0000.md
Original issue report: https://github.com/mersinvald/autorand-rs/issues/5
> autorand: `impl Random` on arrays can lead to dropping uninitialized memory

- crates/gfwx/RUSTSEC-0000-0000.md
Original issue report: https://github.com/Devolutions/gfwx-rs/issues/7
> gfwx: ImageChunkMut needs bounds on its Send and Sync traits

- crates/bra/RUSTSEC-0000-0000.md
Original issue report: https://github.com/Enet4/bra-rs/issues/1
Thank you for reviewing!
> bra: Read on uninitialized buffer

- crates/multiqueue2/RUSTSEC-0000-0000.md
Original issue report: https://github.com/abbychau/multiqueue2/issues/10
> multiqueue2: Queues allow non-Send types to be sent to other threads, allowing data races

- crates/basic_dsp_matrix/RUSTSEC-0000-0000.md
Original issue report: https://github.com/liebharc/basic_dsp/issues/47
> basic_dsp_matrix: panic safety issue in `impl TransformContent<S, D> for [S; (2|3|4)]`

- crates/containers/RUSTSEC-0000-0000.md
Original issue report: https://github.com/strake/containers.rs/issues/2
> containers: panic safety: double drop may happen within `util::{mutate, mutate2}`

- crates/eventio/RUSTSEC-0000-0000.md
Original issue report: https://github.com/petabi/eventio/issues/33
The issue has been resolved in petabi/eventio#34, and I've currently asked them to publish a new version of `eventio` crate that includes the fix.
Thank you very much for reviewing this PR :+1:
> eventio: Input<R>' can send non-Send types to other threads

- crates/buttplug/RUSTSEC-0000-0000.md
Original issue report: https://github.com/buttplugio/buttplug-rs/issues/225
Thank you for reviewing this PR :+1:
> data race in `ButtplugFutureStateShared<T>`

- crates/stderr/RUSTSEC-0000-0000.md
As per the author in https://github.com/biluohc/stderr/issues/5#issuecomment-749377183
They recommend not to use the crate anymore but can't yank it just yet due to some internal dependencies.
> Add unmaintained advisory for stderr crate

- crates/fil-ocl/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/cogciprocate/ocl/issues/194
> Add advisory for double-free in fil-ocl

- crates/atomic-option/RUSTSEC-0000-0000.md
Original issue report: https://github.com/reem/rust-atomic-option/issues/4
The crate is popular on crates.io. (>=106,332 downloads).
The author hasn't responded to the issue report which was submitted more than 10 weeks ago.
Thank you for reviewing :crab:
> unconditional Sync impl of `AtomicOption<T>` allows UB

- crates/va-ts/RUSTSEC-0000-0000.md
Original issue report: https://github.com/video-audio/va-ts/issues/4
> va-ts: `Demuxer` can carry non-Send types across thread boundaries

- .duplicate-id-guard
- .github/workflows/assign-ids.yml
Guard against race conditions resulting in duplicate ID assignment by writing a hash of the directory structure (not file contents) into a file. If two ID assignment jobs run concurrently, the file will create a merge conflict.
This is completely untested, since I don't know how to trigger a test run of a Github action.
> ID assignment action: guard against race conditions 

- crates/ruspiro-singleton/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/RusPiRo/ruspiro-singleton/issues/10
> [patched] Add advisory for data race in ruspiro-singleton

- crates/cdr/RUSTSEC-0000-0000.md
Original issue report: https://github.com/hrektts/cdr-rs/issues/10
> cdr: Reading uninitialized memory can cause UB (`Deserializer::read_vec`)

- crates/unicycle/RUSTSEC-0000-0000.md
Original issue report: https://github.com/udoprog/unicycle/issues/8
> unicycle: PinSlab<T> and Unordered<T, S> need bounds on their Send/Sync traits

- crates/conqueue/RUSTSEC-0000-0000.md
Original issue report: https://github.com/longshorej/conqueue/issues/9
> conqueue: QueueSender's Send trait and Sync trait should have bounds

- crates/ticketed_lock/RUSTSEC-0000-0000.md
Original issue report: https://github.com/kvark/ticketed_lock/issues/7
> ticketed_lock: ReadTicket and WriteTicket should only be sendable when T is Send

- crates/libsbc/RUSTSEC-0000-0000.md
Original issue report: https://github.com/mvertescher/libsbc-rs/issues/4
> libsbc: Decoder<R> can carry `R: !Send` to other threads

- crates/abox/RUSTSEC-0000-0000.md
Original issue report: https://github.com/SonicFrog/abox/issues/1
> abox: AtomicBox<T> implements Send/Sync for any `T: Sized`

- crates/beef/RUSTSEC-0000-0000.md
Original issue report: https://github.com/maciejhirsz/beef/issues/37
> beef: beef::Cow lacks a Sync bound on its Send trait allowing for data races

- crates/marc/RUSTSEC-0000-0000.md
Original issue report: https://github.com/blackbeam/rust-marc/issues/7
Thank you for reviewing :)
> marc: Record::read : Custom `Read` on uninitialized buffer may cause UB

- crates/libp2p-deflate/RUSTSEC-0000-0000.md
Original issue report: https://github.com/libp2p/rust-libp2p/issues/1932
> libp2p-deflate: Undefined data exposed in DeflateOutput's AsyncRead implementation

- crates/v9/RUSTSEC-0000-0000.md
Original issue report: https://github.com/purpleposeidon/v9/issues/1
> v9: SyncRef's clone() and debug() allow data races

- crates/kekbit/RUSTSEC-0000-0000.md
Original issue report: https://github.com/motoras/kekbit/issues/34
The crate author hasn't been active on github for 6 months.
> kekbit: ShmWriter allows sending non-Send type across threads

- crates/cache/RUSTSEC-0000-0000.md
Original issue report: https://github.com/krl/cache/issues/1
> Cache<K>: Send/Sync impls needs trait bounds on `K`

- crates/signal-simple/RUSTSEC-0000-0000.md
Original issue report: https://github.com/kitsuneninetails/signal-rust/issues/2
> signal-simple: SyncChannel<T> can send non-Send types to other threads

- crates/async-coap/RUSTSEC-0000-0000.md
Original issue report: https://github.com/google/rust-async-coap/issues/33
> async-coap: ArcGuard's Send and Sync should have bounds on RC

- crates/bunch/RUSTSEC-0000-0000.md
Original issue report: https://github.com/krl/bunch/issues/1
> bunch: Bunch<T> unconditionally implements Send/Sync, allowing data races

- crates/array-tools/RUSTSEC-0000-0000.md
Original issue report: https://github.com/L117/array-tools/issues/2
The author has been inactive on GitHub for more than 3 months,
so it's not likely for us to get a response to the issue soon.
> array-tools: `FixedCapacityDequeLike::clone()` can cause dropping uninitialized memory

- crates/slock/RUSTSEC-0000-0000.md
Original issue report: https://github.com/BrokenLamp/slock-rs/issues/2
> slock: Slock<T> allows sending non-Send types across thread boundaries

- crates/scottqueue/RUSTSEC-0000-0000.md
Original issue report: https://github.com/rossdylan/rust-scottqueue/issues/1
Crate author hasn't responded for 2 months, and hasn't been active on GitHub for 6+ months.
> scottqueue: Queue<T> should have a Send bound on its Send/Sync traits

- crates/parc/RUSTSEC-0000-0000.md
Original PR report: https://github.com/hyyking/rustracts/pull/6
The crate author hasn't responded for 3 months.
> `LockWeak<T>` allows to create data race to `T`

- crates/lexer/RUSTSEC-0000-0000.md
Original issue report: https://gitlab.com/nathanfaucett/rs-lexer/-/issues/2
Issue report was submitted to main repo for more than 2 months ago, but the author hasn't responded yet.
Thank you for reviewing this PR :crab:
> data race in lexer::ReaderResult<T, E>

- crates/calamine/RUSTSEC-0000-0000.md
Original issue report: https://github.com/tafia/calamine/issues/199
Thank you for reviewing this issue :+1:
> calamine: access unclaimed/uninitialized memory

- crates/lever/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/vertexclique/lever/issues/15
Issue has been open for 2 months without a response from the authors.
> Add advisory for data race in lever

- crates/model/RUSTSEC-0000-0000.md
Original issue report: https://github.com/spacejam/model/issues/3
> model: `Shared` can cause a data race

- crates/ms3d/RUSTSEC-0000-0000.md
Original issue report: https://github.com/andrewhickman/ms3d/issues/1
> ms3d: `IoReader::read()`: user-provided `Read` on uninitialized buffer may cause UB

- crates/postscript/RUSTSEC-0000-0000.md
Original issue report: https://github.com/bodoni/postscript/issues/1
> postscript: `Read` on uninitialized buffer may cause UB (`impl Walue for Vec<u8>`)

- crates/lever/RUSTSEC-2020-0137.md
Lever 0.1.1 patch fixes [RUSTSEC-2020-0137](https://rustsec.org/advisories/RUSTSEC-2020-0137.html), thanks to [this issue](https://github.com/vertexclique/lever/issues/15) and [this pull request](https://github.com/vertexclique/lever/pull/17).
Thanks for letting us know, and thanks for reviewing, please let me know if there's anything I can do to improve this pull request :)
> Lever 0.1.1 patch

- crates/noise_search/RUSTSEC-0000-0000.md
Original issue report: https://github.com/pipedown/noise/issues/72
> noise_search: `MvccRwLock` allows data races & aliasing violations

- crates/syncpool/RUSTSEC-0000-0000.md
Original issue report: https://github.com/Chopinsky/byte_buffer/issues/2
The issue has been resolved in the master branch of the repo,
but a new release hasn't yet been published to crates.io.
I left a comment (to the original issue report) asking to publish a new release to crates.io.
Thank you for reviewing :)
> syncpool: Send bound needed on T (for Send impl of `Bucket2`)

- crates/calamine/RUSTSEC-2021-0015.md
RUSTSEC-2021-0015 has been patched in v0.17.0.
> add patched version for calamine

- crates/sys-info/RUSTSEC-2020-0100.md
Update the date field of RUSTSEC-2020-0100 to the date when the original issue was reported.
The current date 2020-01-19 seems to be a typo of 2021-01-19, the date when the RustSec PR was created.
> RUSTSEC-2020-0100: Update date field

- crates/multiqueue/RUSTSEC-0000-0000.md
Original issue report: https://github.com/schets/multiqueue/issues/31
> multiqueue: Queues allow non-Send types to be sent to other threads, allowing data races

- crates/qwutils/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/qwertz19281/rust_utils/issues/3
> [patched] Add advisory for double-free in qwutils

- crates/xcb/RUSTSEC-0000-0000.md
Closes: https://github.com/RustSec/advisory-db/issues/653
---
As requested by @Shnatsel, here is my attempt at an advisory. I tried to follow what #575 does, but elaborate all the various issues in sub-headings. I did not include `informational = "unsound"` (#575 has this), because this is also `informational = "unmaintained"` and this `informational` entry seems to be undocumented (I only found its use in various advisories), so I am not sure what to do. My best idea: If wanted/necessary, I can split this into two PRs, one for the maintenance status and one for the other issues.
---
I'm also nervous about "there is a code generator that turns XML into lots and lots of `unsafe` code, most of that in functions that are supposed to be safe", but that's likely not worth an advisory. At least …
> Report various rust-xcb issues to RustSec

- .github/workflows/publish-web.yml
Uses the flow suggested here:
https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
> `publish-web` fix

- crates/xcb/RUSTSEC-2021-0019.md
Advisories without URLs are slightly disadvantageous to automated consumers of the JSON output of `cargo audit --json` as any reference to the advisory created automatically has no context for reviewers to learn more.
Since there currently is no URL reference for the recently added RUSTSEC-2021-0019 advisory against `xcb`, I added the rustsec.org one since it is the most complete, compared to the [original issue](https://github.com/RustSec/advisory-db/issues/653).
> Add advisory URL to RUSTSEC-2021-0019

- README.md
When I was l looking for the rustsec.org recently with keywords like "rust advisory database", I found the repository but had some trouble finding the site (perhaps to my defaulting to use DuckDuckGo). A link here makes sense, I think?
> Add link to site

- crates/lzw/RUSTSEC-0000-0000.md
https://github.com/nwin/lzw/issues/2 this has not received attention for 1.5 years.
Meanwhile, a faster and maintained alternative exists.
> lzw: Unmaintained

- crates/nb-connect/RUSTSEC-0000-0000.md
The equivalent of #503, #505, #509 and #507. But for the `nb-connect` crate. Before the 1.0.3 release `nb-connect` invalidly assumed the memory layout of a standard library type. Something that is not part of the stable API of `std`.
https://github.com/smol-rs/nb-connect/issues/1
> Add advisory on nb-connect SocketAddr casting

- crates/yottadb/RUSTSEC-0000-0000.md
I've also yanked all affected versions.
> Add use-after-free advisory for `yottadb 1.1.0` and earlier

- crates/array-tools/RUSTSEC-2020-0132.md
https://github.com/L117/array-tools/commit/709d89f23c5b2e81ed25537446f838c3cdb73b6f (v0.3.2 on crates.io)
> Fixed memory corruption.

- crates/heapless/RUSTSEC-0000-0000.md
Original issue: https://github.com/japaric/heapless/issues/181
There is a proof-of-concept in the original bug report.
The issue is not yet fixed.
> heapless: use-after-free when cloning partially consumed Iterator

- crates/generic-array/RUSTSEC-0000-0000.md
This is an advisory for an old version of `generic-array`, however some crates (notably `headers`) still use those old versions of `generic-array`.
> Add an advisory on lifetime extension in generic-array

- crates/bam/RUSTSEC-0000-0000.md
Upstream issue: https://gitlab.com/tprodanov/bam/-/issues/4
> [patched] Add advisory for out-of-bounds write in bam

- crates/toodee/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/antonmarsden/toodee/issues/13
> [patched] Add advisory for memory safety issue in toodee's insert_row

- crates/truetype/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/bodoni/truetype/issues/11
> [patched] Report uninitialized memory exposure in truetype

- crates/generic-array/RUSTSEC-2020-0146.md
I didn't realize this was an option because it wasn't in example advisory.
> Mark RUSTSEC-2020-0146 as unsound

- crates/scratchpad/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/okready/scratchpad/issues/1
> [patched] Add advisory for double-free in scratchpad

- crates/generic-array/RUSTSEC-2020-0146.md
Allows use-after-free, and looks easy enough to trigger.
> Revert "Mark RUSTSEC-2020-0146 as unsound (#788)"

- crates/byte_struct/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/wwylele/byte-struct-rs/issues/1
> [patched] Add advisory for uninitialized memory drop in byte_struct

- crates/office/RUSTSEC-0000-0000.md
As per the author in https://github.com/RustSec/advisory-db/issues/742#issuecomment-773313783
Office is not supported and has been replaced by `calamine`.
> Add unmaintained advisory for office crate. Fixes #742

- crates/rulinalg/RUSTSEC-0000-0000.md
As per the author in https://github.com/AtheMathmo/rulinalg/issues/201#issuecomment-584749313 and this note in the README: https://github.com/AtheMathmo/rulinalg/commit/0ea49678d2dfa0e0a0df9cd26f49f6330aef80c4
They recommend `nalgebra` as an alternative.
> Add unmaintained advisory for rulinalg crate

- crates/internment/RUSTSEC-0000-0000.md
Original issue report: https://github.com/droundy/internment/issues/20
> internment: Intern<T>: Data race allowed on T

- crates/diesel/RUSTSEC-0000-0000.md
We've discovered a use-after-free issue in diesel's sqlite backend, which can be triggered by real world code. See the corresponding PR (https://github.com/diesel-rs/diesel/pull/2663) for details.
> Report use-after-free issue in diesels sqlite backend

- .github/workflows/publish-web.yml
This should hopefully finish simplifying the website rendering pipeline and fix some of the escaping issues.
**Don't merge this until [rustsec-admin](https://github.com/RustSec/rustsec-admin) has received a version bump and release.**
-----
Since this alters the output of the static file generation, the `gh-pages` branch either needs to be reset, either with a full history reset (will require a force push):
1. `git branch -d gh-pages` _(Delete the branch)_
2. `git checkout --orphan gh-pages` _(Create a new orphan/empty branch)_
3. `git rm -rf .` 
Or if we want to maintain the existing history of the branch, just:
1. `git rm -rf .` 
After which we need to add a `.nojekyll` file so github doesn't try to build the website with jekyll anymore.
1. `touch .nojekyll`
2. `git add .nojekyll`
3. …
>  Update rustsec-admin version to use new website generator

- crates/endian_trait/RUSTSEC-0000-0000.md
Original issue report: https://gitlab.com/myrrlyn/endian_trait/-/issues/1
> endian_trait: panic in user-provided `Endian` impl triggers double drop of T

- crates/arenavec/RUSTSEC-0000-0000.md
Original issue report: https://github.com/ibabushkin/arenavec/issues/1
> arenavec: potential double drop or uninitialized memory drop upon panic

- .github/workflows/mirror-main-to-master.yml
The 'master' branch has been renamed to 'main' per https://github.com/RustSec/advisory-db/issues/312
However older clients are still consuming the 'master' branch.
This commit adds a GitHub Actions job which mirrors the 'main' branch to 'master' to continue supporting these older clients.
> Mirror 'main' branch to 'master'

- crates/insert_many/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/rphmeier/insert_many/issues/1
It's been open for 2 months now with no response from the author.
> Add advisory for double-free in insert_many

- crates/uu_od/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/uutils/coreutils/issues/1729
> [patched] Add advisory for uninitialized exposure in uu_od

- crates/rocket/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/SergioBenitez/Rocket/issues/1534
Marked as `informational = unsound` because as per the original bug thread, it is rare for users to actually implement a custom `UriDisplay` and it's unlikely for such a method to panic since it just deals with string formatting.
> [patched] Add advisory for use-after-free in rocket

- crates/adtensor/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/charles-r-earp/adtensor/issues/4
Open for 3 months without a response from the crate author.
> Report uninitialized memory drop in adtensor

- crates/hyper/RUSTSEC-2021-0020.md
The fix was backported to 0.12.x in https://github.com/hyperium/hyper/pull/2436 and released in 0.12.36.
Changelog: https://github.com/hyperium/hyper/blob/0.12.x/CHANGELOG.md#v01236-2021-02-17, _http1: fix server misinterpretting multiple Transfer-Encoding headers_ line
> RUSTSEC-2021-0020 is fixed in hyper 0.12.36 too

- crates/stackvector/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/Alexhuszagh/rust-stackvector/issues/2
Been open for more than a month now.
> Report out-of-bounds write in stackvec

- crates/reorder/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/tiby312/reorder/issues/1
Been open now for a little over a month with no response.
> Add advisory for out-of-bounds write and uninitialized memory exposure in reorder

- crates/outer_cgi/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/SolraBizna/outer_cgi/issues/1
> [patched] Add advisory for uninitialized exposure in outer_cgi

- crates/reorder/RUSTSEC-2021-0050.md
> Added patch to "fix" vulnerability.

- crates/stackvector/RUSTSEC-2021-0048.md
A memory corruption issue in the `extend` method of https://github.com/Alexhuszagh/rust-stackvector/issues/2 has been patched in this [commit](https://github.com/Alexhuszagh/rust-stackvector/commit/f45657d5a823a67bb3f5cffee65efbb401a44192). All versions prior to this commit have been yanked from [crates.io](https://crates.io/crates/stackvector/versions) out of precaution, so any available versions should be unaffected.
> Update advisory to indicate patched versions of stackvector.

- rust/std/CVE-2015-20001.md
- rust/std/CVE-2020-36317.md
- rust/std/CVE-2020-36318.md
- rust/std/CVE-2021-28875.md
- rust/std/CVE-2021-28876.md
- rust/std/CVE-2021-28877.md
- rust/std/CVE-2021-28878.md
- rust/std/CVE-2021-28879.md
The first eight bugs reported as part of #539
> Track std bugs that received CVE numbers

- crates/algorithmica/RUSTSEC-0000-0000.md
Original issue report: https://github.com/AbrarNitk/algorithmica/issues/1
> algorithmica: 'merge_sort::merge()' crashes with double-free for `T: Drop`

- crates/algorithmica/RUSTSEC-0000-0000.md
Necessary due to the way the master->main transition was set up, see https://github.com/RustSec/advisory-db/pull/872
> Mirror algorithmica advisory to `main`

- crates/tiny_http/RUSTSEC-2020-0031.md
A backport of the fix for 2020-0031 has been applied to the 0.6.x branch, starting at 0.6.3, subsequent 0.6 versions are no longer vulnerable.
I wasn't quite sure how to express "0.6.x versions are no longer vulnerable where x >= 3", I hope this is correct!
> Mark patched tiny-http version for 2020-0031

- crates/directories/RUSTSEC-2020-0054.md
- crates/dirs/RUSTSEC-2020-0053.md
Both `dirs` and `directories` seem to be actively maintained again, making `RUSTSEC-2020-0053` and `RUSTSEC-2020-0054` obsolete. From the `dirs-next` crate:
> Note: This is a fork of once-abandoned `dirs` crate.
https://crates.io/crates/dirs-next/2.0.0
and the `directories-next` crate:
> Note: This is a fork of once-abandoned `directories` crate.
https://crates.io/crates/directories-next/2.0.0
and new releases of the `dirs`/`directories` crates where the Readmes state that they are actively developed again:
https://crates.io/crates/dirs/3.0.1 / https://crates.io/crates/directories/3.0.1
> Yank advisories for once-again maintained `dirs` / `directories` crates

- crates/aesni/RUSTSEC-0000-0000.md
The `aesni` crate has been merged into the `aes` crate. See:
https://github.com/RustCrypto/block-ciphers/pull/200
> Add unmaintained crate advisory for `aesni`

- crates/aes-soft/RUSTSEC-0000-0000.md
The `aes-soft` crate has been merged into the `aes` crate. See:
https://github.com/RustCrypto/block-ciphers/pull/200
> Add unmaintained crate advisory for `aes-soft`

- crates/aes-ctr/RUSTSEC-0000-0000.md
The `aes-ctr` crate has been merged into the `aes` crate. See:
https://github.com/RustCrypto/block-ciphers/pull/200
> Add unmaintained crate advisory for `aes-ctr`

- crates/aes-ctr/RUSTSEC-2021-0061.md
- crates/aes-soft/RUSTSEC-2021-0060.md
- crates/aesni/RUSTSEC-2021-0059.md
The previous titles accidentally omitted the crate names, making them confusing during reporting.
> aes* crates: add crate names to advisory titles

- crates/cpuid-bool/RUSTSEC-0000-0000.md
It has been renamed to `cpufeatures`. See:
https://github.com/RustCrypto/utils/pull/381
> Add unmaintained crate advisory for `cpuid-bool`

- crates/anymap/RUSTSEC-0000-0000.md
It appears that the `anymap` has been [abandoned](https://github.com/chris-morgan/anymap/issues/37), and the most recent released version contains a soundness bug that has been [fixed upstream](https://github.com/chris-morgan/anymap/pull/32), but never published to crates.io
> anymap is unmaintained

- crates/evm/RUSTSEC-0000-0000.md
Related commit: https://github.com/rust-blockchain/evm/commit/19ade858c430ab13eb562764a870ac9f8506f8dd
Fix is available for `>= 0.26.1` and also `0.25.1`, `0.24.1`, `0.23.1`, `0.21.1`.
> evm: security advisory related to memory over-allocation

- crates/evm-core/RUSTSEC-2021-0066.md
While `evm` is usually what is directly imported by the library users, the security advisory only requires bumping version of `evm-core`, but not any other `evm`-related crates.
> evm-core: fix crate name

- crates/flatbuffers/RUSTSEC-2020-0009.md
With the [release of flatbuffers 2.0.0](https://github.com/google/flatbuffers/releases/tag/v2.0.0)
google/flatbuffers#5825 has been fixed and released. This patch updates
the advisory-db to indicate a patched version addressing the issue.
> fix: update rustsec-2020-0009 with patched version

- crates/cranelift-codegen/RUSTSEC-0000-0000.md
This is a miscompilation that can result in a Wasm heap sandbox escape.
More details are in our GitHub security advisory at:
https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-hpqh-2wqx-7qp5
> Add RUSTSEC notice for CVE-2021-32629, a Cranelift miscompilation bug.

- crates/iced-x86/RUSTSEC-0000-0000.md
More information here: https://github.com/icedland/iced/issues/168
[Rendered](https://github.com/landaire/advisory-db/blob/iced-x86-advisory/crates/iced-x86/RUSTSEC-0000-0000.md).
> Add advisory for iced-x86 soundness bug

- crates/trust-dns-proto/RUSTSEC-2018-0007.md
OSV requires all ranges to be non-overlapping. This changes the range definition in RUSTSEC-2018-0007 to avoid overlap and enable that use case.
This should have no effect on the code currently in production.
> Make ranges in RUSTSEC-2018-0007.md  non-overlapping

- crates/arc-swap/RUSTSEC-2020-0091.md
- crates/claxon/RUSTSEC-2018-0004.md
- crates/cranelift-codegen/RUSTSEC-2021-0067.md
- crates/miow/RUSTSEC-2020-0080.md
- crates/rand_core/RUSTSEC-2019-0035.md
- crates/trust-dns-proto/RUSTSEC-2018-0007.md
This removes overlaps in version range specifications. Sometimes the change is cosmetic, but in several cases it fixes specifications that were previously defined incorrectly - e.g.:
-patched = [">= 0.3.1", ">= 0.4.2"]
+patched = ["^ 0.3.1", ">= 0.4.2"]
> Remove range overlaps, fix some range specifications

- crates/nalgebra/RUSTSEC-0000-0000.md
Add advisory for a memory exposure in the `Deserialize` implementation for  `nalgebra`'s `VecStorage`/`MatrixVec` structs, as discussed in #880.
`git bisect` was used to track this vulnerability back to its introduction in [`086e6e`](https://github.com/dimforge/nalgebra/commit/086e6e719f53fecba6dadad2e953a487976387f5). `git tag --contains 086e6e` indicates that the first tag containing this commit is `v0.11.0`. I have marked earlier versions as unaffected by this advisory.
> Add advisory for nalgebra VecStorage/MatrixVec

- crates/tectonic_xdv/RUSTSEC-0000-0000.md
Original issue report: https://github.com/tectonic-typesetting/tectonic/issues/752
> tectonic_xdv: `Read` on uninitialized buffer may cause UB ('tectonic_xdv' crate)

- crates/metrics-util/RUSTSEC-0000-0000.md
Original issue report: https://github.com/metrics-rs/metrics/issues/190
> metrics-util: AtomicBucket<T> unconditionally implements Send/Sync

- crates/cranelift-codegen/RUSTSEC-2021-0067.md
- crates/hyper/RUSTSEC-2021-0020.md
- crates/libpulse-binding/RUSTSEC-2018-0020.md
- crates/libpulse-binding/RUSTSEC-2018-0021.md
Some advisories mentioned GHSA in links, but didn't specify an alias. This PR fixes that.
This is becoming more important with OSV enabling interop between databases.
> Add GHSA mentions to `aliases` field

- crates/grep-cli/RUSTSEC-0000-0000.md
Ref https://github.com/BurntSushi/ripgrep/issues/1773
> crates/grep-cli: add advisory for arbitrary binary execution on Windows

- crates/directories/RUSTSEC-2020-0054.md
- crates/dirs/RUSTSEC-2020-0053.md
- crates/libpulse-binding/RUSTSEC-2020-0055.md
- crates/spin/RUSTSEC-2019-0031.md
`cargo audit` works normally and does not require any changes., but this makes the current linter barf because of unknown field `withdrawn`.
I have linter with validation for these fields in the `osv` branch. We could publish that as a pre-release, that would also require a pre-release of `rustsec` crate.
Another approach is to extract just the linter changes (they _seem_ to be self-contained) and publish a new release. That should work in theory, but I haven't tested that.
Only @tarcieri currently has the permissions to publish `rustsec-admin`; adding as a reviewer.
> Add `withdrawn` field

- crates/stackvector/RUSTSEC-2021-0048.md
The advisory as declared currently would consider 2.0.0 and later to be vulnerable.
> Fix RUSTSEC-2021-0048 which doesn't declare an operand

- .github/workflows/export-osv.yml
Kinda gross, but this is the fastest fix I could think of
> OSV export: fix handling of advisories without an ID

- crates/tokio/RUSTSEC-0000-0000.md
See https://github.com/tokio-rs/tokio/issues/3929
> Add advisory for race condition in Tokio

- crates/ammonia/RUSTSEC-0000-0000.md
XSS vuln in Ammonia.
I don't know how to exploit it without allowing `<iframe>`, which it doesn't allow by default, but that's not an unreasonable thing for someone to do.
rust-ammonia/ammonia#142
> Add rust-ammonia/ammonia#142

- crates/prost-types/RUSTSEC-2021-0073.md
Reverts RustSec/advisory-db#958
Unfixes #957
We've decided we don't support versions of `cargo-audit` that are that old, and it's not worth sacrificing the extra metadata to accommodate them.
> Revert "Hotfix #957 until we figure out what to do with it"

- crates/ark-r1cs-std/RUSTSEC-0000-0000.md
(Note that there is no violation of Rust UB guarantees; everything is entirely safe)
> `ark_r1cs_std::mul_by_inverse` generated unsound constraints in versions below `0.3.1`

- crates/better-macro/RUSTSEC-0000-0000.md
It's "Proving A Point" in https://github.com/raycar5/better-macro/blob/master/doc/hi.md but there's
no guarantee that this will remain benign (or is actually benign right now). The crate also has no useful functionality.
> better-macro has deliberate RCE in proc-macro

- crates/tar/RUSTSEC-0000-0000.md
Original report at https://github.com/alexcrichton/tar-rs/issues/238, discovered and reported by @mgjm.
Even though the report is from 2020 it still has 0day status, there's currently no patch. The stale issue was shared with me by @stoeckmann.
> Add directory traversal for tar

- crates/tar/RUSTSEC-2021-0080.md
See [issue #238](https://github.com/alexcrichton/tar-rs/issues/238) and [PR #259](https://github.com/alexcrichton/tar-rs/pull/259)
> Add fix for RUSTSEC-2021-0080

- crates/tar/RUSTSEC-2021-0080.md
This replaces a place holder with the actual fixed version.
> Update RUSTSEC-2021-0080 [affected] version

- crates/reffers/RUSTSEC-2020-0094.md
I'm not sure anyone uses this old crate but if they do, at least now they have a fixed version.
> Patched release of reffers

- crates/vec-const/RUSTSEC-0000-0000.md
It looks like most of the reports are for higher-profile crates, but someone on Reddit already mistook `vec-const` for something they should consider using.
I've added a URL to a simple example that demonstrates one aspect of the unsoundness of this crate. Is anything else needed in that area?
> Report vec-const as unsound

- crates/bite/RUSTSEC-0000-0000.md
Original issue report: https://github.com/hinaria/bite/issues/1
The author of the crate is unlikely to respond to the issue, since the author has been inactive on GitHub since late 2019..
Thank you for reviewing! :rocket:
> bite: Read on uninitialized memory

- crates/derive-com-impl/RUSTSEC-0000-0000.md
`com-impl` crate relies on `derive-com-impl` to provide a default implementation for AddRef, Release and QueryInterface methods of IUnkown
To respect COM conventions, QueryInterface must call AddRef before returning a pointer to the underlying class. This leads to too many Release, and when the refcount drops to 0, WMI free the memory, which can lead to undefined behaviour.
> Add advisory for potential memory corruption in derive-com-impl

- crates/bronzedb-protocol/RUSTSEC-0000-0000.md
Original issue report: https://github.com/Hexilee/BronzeDB/issues/1
> bronzedb-protocol: `Read` on uninitialized buffer can cause UB (impl of `ReadKVExt`)

- crates/binjs_io/RUSTSEC-0000-0000.md
Original issue report: https://github.com/binast/binjs-ref/issues/460
> binjs_io: 'Read' on uninitialized memory may cause UB

- crates/flumedb/RUSTSEC-0000-0000.md
Original issue report: https://github.com/sunrise-choir/flumedb-rs/issues/10
> flumedb: Reading on uninitialized buffer may cause UB ( `read_entry()` )

- crates/columnar/RUSTSEC-0000-0000.md
Original issue report: https://github.com/frankmcsherry/columnar/issues/6
> columnar: Reading on uninitialized buffer may cause UB

- crates/buffoon/RUSTSEC-0000-0000.md
Original issue report: https://github.com/carllerche/buffoon/issues/2
> buffoon: InputStream::read_exact : Reading into an uninitialized buffer may cause UB

- crates/acc_reader/RUSTSEC-0000-0000.md
Original issue report: https://github.com/netvl/acc_reader/issues/1
> acc_reader: API Soundness issue in `fill_buf()` and `read_up_to()`

- crates/csv-sniffer/RUSTSEC-0000-0000.md
Original issue report: https://github.com/jblondin/csv-sniffer/issues/1
> csv-sniffer: reading on uninitialized memory may cause undefined behavior

- crates/raw-cpuid/RUSTSEC-0000-0000.md
Following up on #614: Thanks. Here's part 2, then.
> raw-cpuid: Optional `Deserialize` implementations unsound

- crates/ash/RUSTSEC-0000-0000.md
Original issue report: https://github.com/MaikKlein/ash/issues/354
> ash: Reading on uninitialized memory may cause UB ( `util::read_spv()` )

- crates/gfx-auxil/RUSTSEC-0000-0000.md
Original issue report: https://github.com/gfx-rs/gfx/issues/3567
> gfx-auxil: `Read` on uninitialized buffer may cause UB ( `gfx_auxil::read_spirv()` )

- crates/messagepack-rs/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/otake84/messagepack-rs/issues/2
Open for 2 months with no response from the author.
> Add advisory for uninitialized memory exposure in messagepack-rs

- crates/crossbeam-deque/RUSTSEC-0000-0000.md
In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug.
Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue. (e.g., rayon)
Credits to @kmaork for discovering, reporting and fixing the bug.
Refs: https://github.com/crossbeam-rs/crossbeam/security/advisories/GHSA-pqqp-xmhj-wgcw, [CVE-2021-32810](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32810)
> Add advisory for data race in crossbeam-deque

- crates/rdiff/RUSTSEC-0000-0000.md
Upstream issue: https://github.com/dyule/rdiff/issues/3
Open for around two months now with no response.
> Add advisory for out-of-bounds read in rdiff

- crates/raw-cpuid/RUSTSEC-2021-0089.md
Reviewed and confirmed https://github.com/rustsec/advisory-db/pull/671#issuecomment-903206917.
> RUSTSEC-2021-0089 has been patched in raw-cpuid 9.1.1

- crates/net2/RUSTSEC-2020-0078.md
- crates/socket2/RUSTSEC-2020-0079.md
It was linked to the wrong advisory. Thanks to @OS-WS for pointing it out [here](https://github.com/rustsec/advisory-db/commit/7fb26418880c22999ee69be313d713b8b579e5ff#commitcomment-55284597).
> Fix CVE alias CVE-2020-35920

- crates/ash/RUSTSEC-2021-0090.md
https://github.com/MaikKlein/ash/issues/354 was fixed in https://github.com/MaikKlein/ash/pull/470.
> ash: RUSTSEC-2021-0090 has been patched in 0.33.1

- crates/cosmos_sdk/RUSTSEC-0000-0000.md
It has been renamed to `cosmrs`:
https://github.com/cosmos/cosmos-rust/tree/main/cosmrs
> Add unmaintained crate advisory for `cosmos_sdk`

- .github/workflows/export-osv.yml
- Bump `rustsec-admin` in OSV export workflow
- Switch branch name from `osv-experimental-v0.7` to `osv` now that the format is 1.0
> Switch to rustsec-admin 0.5.2 (OSV 1.0) and branch `osv`

- crates/tremor-script/RUSTSEC-0000-0000.md
This is the first advisory i authored, any hints or tips for improvements welcome.
> Add advisory for memory corruption in tremor-script < 0.11.6

- crates/metrics-util/RUSTSEC-0000-0000.md
- crates/tectonic_xdv/RUSTSEC-0000-0000.md
#935 and #936 are merged but do not appear to exist on the current main branch.
> Add disappeared advisories

- crates/better-macro/RUSTSEC-2021-0077.md
There appear to be some missing words, which unintentionally give a sentence the opposite meaning.
> Clarify meaning of RUSTSEC-2021-0077.md

- crates/arrow/RUSTSEC-0000-0000.md
Add an advisory for https://github.com/apache/arrow-rs/issues/772 and https://github.com/apache/arrow-rs/issues/773
@jorgecarleitao I'd appreciate if you could take a look.
> arrow BinaryArray advisory

- crates/nix/RUSTSEC-0000-0000.md
Reported in nix-rust/nix#1541, fix currently under review.
> nix::unistd::getgrouplist buffer overflow

- crates/fruity/RUSTSEC-0000-0000.md
Issue: nvzqz/fruity#14
A CVE request has been submitted as well.
Questions:
- Can I add trait implementations to the `functions` list?
- Should I create an unmaintained crate advisory too?
- nvzqz/fruity#14
- nvzqz/fruity#13
> Add fruity advisory for nvzqz/fruity#14

- crates/fruity/RUSTSEC-2021-0123.md
It's impressive how quickly this was assigned.
Initial PR: #1102
> Add CVE for RUSTSEC-2021-0123

- crates/tokio/RUSTSEC-0000-0000.md
If a `tokio::sync::oneshot` channel is closed (via the
`oneshot::Receiver::close`]method), a data race may occur if the
`oneshot::Sender::send` method is called while the corresponding
`oneshot::Receiver` is `await`ed or calling `try_recv`.
When these methods are called concurrently on a closed channel, the two halves
of the channel can concurrently access a shared memory location, resulting in a
data race. This has been observed to [cause memory corruption][corruption].
Note that the race only occurs when **both** halves of the channel are used
after one half has called `close`. Code where `close` is not used, or where the
`Receiver` is not `await`ed and `try_recv` is not called after calling `close`,
is not affected.
See tokio-rs/tokio#4225 for more details.
This issue was patched in …
> Add advisory for tokio-rs/tokio#4225

- crates/simple_asn1/RUSTSEC-0000-0000.md
The maintainer has acknowledged and fixed this issue; see
https://github.com/acw/simple_asn1/pull/28 .
This is my first RustSec advisory; please check carefully to see if I have done anything incorrectly.  Thanks!
> Security advisory on simple_asn1 version 0.6.0

- crates/slice-deque/RUSTSEC-2020-0158.md
I decided to fork slice_deque due to the outstanding security
advisory and not getting a response from the creator.
This adds a mention to the original advisory to help people 'patch' the issue.
> Adds maintained alternative to slice_deque

- crates/rust-embed/RUSTSEC-0000-0000.md
Reported this in https://github.com/pyros2097/rust-embed/issues/159. It is *somewhat* unlikely that people will hit it in a production environment since it does require you to be running in a debug mode, but https://github.com/agora-org/agora/issues/270 is an example of where it was vulnerable.
> Add advisory for rust-embed path traversal

- crates/rusqlite/RUSTSEC-0000-0000.md
Advisory for issue reported as https://github.com/rusqlite/rusqlite/issues/1048.
This is a soundness hole in several `rusqlite` APIs where you can pass a closure with a too-short lifetime.
Doing so can lead to UAF. As a small mercy, it's somewhat unlikely to have code that uses these API incorrectly but silently works — most usage should either be fine, unless the code has not been tested at all.
That said, this is obviously not guaranteed — I've backported it to all affected major versions (0.25.x before 0.25.4 and 0.26.x before 0.26.2), and will yank the affected releases after filing this issue, so there should be no reason not to update.
> Report `rusqlite` closure lifetime issue

- crates/lru/RUSTSEC-0000-0000.md
Lru crate has use after free vulnerability.
Lru crate has two functions for getting an iterator. Both iterators give
references to key and value. Calling specific functions, like pop(), will remove
and free the value, and but it's still possible to access the reference of value
which is already dropped causing use after free.
More information in upstream repository issue: https://github.com/jeromefroe/lru-rs/issues/120 and the already released fix can be found from https://github.com/jeromefroe/lru-rs/pull/121
> Add use after free advisory for lru crate

- crates/brotli-sys/RUSTSEC-0000-0000.md
Edited version of #1124 that can be merged directly, without waiting on third parties
> Brotli CVE-2020-8927 redux

- crates/compu-brotli-sys/RUSTSEC-0000-0000.md
Similar to #1127
`compu-brotli-sys` also bundles the Brotli C library.
> CVE-2020-8927 for compu-brotli-sys

- crates/arrow/RUSTSEC-2021-0116.md
- crates/arrow/RUSTSEC-2021-0117.md
- crates/arrow/RUSTSEC-2021-0118.md
It looks to me like all the outstanding arrow-rs advisories were fixed, as mentioned in https://github.com/apache/arrow-rs/issues/817, and those fixes were released in version 6.4.0. @alamb can you confirm?
> Mark arrow advisories as fixed in 6.4.0

- crates/cargo-download/RUSTSEC-0000-0000.md
Use of this crate will result into corrupted crate downloads due to lacking flush into filesystem.
No activity in over a year either in the repo or from the publisher(s)
Issue where maintenance takeover has been proposed around 2 Oct
https://github.com/Xion/cargo-download/issues/10
Critical PR that would resolve the write flush
https://github.com/Xion/cargo-download/pull/11
> Mark cargo-download unmaintained

- crates/lmdb/RUSTSEC-0000-0000.md
The `lmdb` crate https://github.com/danburkert/lmdb-rs has been unmaintained since roughly August 2018. This prompted mozilla to fork it and create their own crate [`lmdb-rkv`](https://crates.io/crates/lmdb-rkv)...which is ironically, also unmaintained.
> Add unmaintained advisory for lmdb

- crates/rust-crypto/RUSTSEC-2016-0005.md
`sodiumoxide` is unmaintained itself. See #1090.
We haven't filed a specific unmaintained crate advisory for it yet, but probably should.
> RUSTSEC-2016-0015: remove `sodiumoxide` recommendation

- crates/dashmap/RUSTSEC-0000-0000.md
Undefined behavior may occur when using the `Ref::value` of `dashmap`. See https://github.com/xacrimon/dashmap/issues/167 for more information.
Example vulnerable code:
```rust
use dashmap::DashMap;
fn main() {
let x = DashMap::new();
x.insert(1, 1);
let borrow = x.get(&1).unwrap();
let val = borrow.value();
std::mem::drop(borrow);
let mut borrow_mut = x.get_mut(&1).unwrap();
let val_mut = borrow_mut.value_mut(); // non-exclusive mutable reference!!!
println!("{}", val);
}
```
I'm unsure about in which categories this issue falls and what to write in the description.
> Undefined behavior in `dashmap`

- rust/std/CVE-2022-21658.md
Closes: https://github.com/rustsec/advisory-db/issues/1154
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>
> Add advisory for CVE-2022-21658

- rust/std/CVE-2022-21658.md
I accidentally put 2021.
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>
> Correct year for CVE-2022-21658

- crates/array-macro/RUSTSEC-0000-0000.md
This is somewhat ancient unsoundness issue (like, one that was fixed 20 months ago), but may as well report it, even if really nobody will care. It may have some educational value however - somebody may see this issue and realize there is a similar issue in macros they wrote. See https://github.com/rust-lang/unsafe-code-guidelines/issues/278 for more context.
> Add soundness advisory for array-macro

- crates/rustc-serialize/RUSTSEC-0000-0000.md
rustc_serialize is unmaintained (I'm assuming, there's a note in the readme that bugfixes will be merged, but the [repo itself](https://github.com/rust-lang-deprecated/rustc-serialize) is archived, so I suppose that's not happening), is it worth filing just an unmaintained advisory / filing two different advisories?
> Add advisory for rustc_serialize

- crates/tower-http/RUSTSEC-2021-0135.md
I have backported the fix for RUSTSEC-2021-0135 to tower-http 0.1.3 so that version is no longer affected. 0.2.0 does have the bug so that is still insecure. I _think_ I got the versions right 🤞
> Update which tower-http versions are affected by RUSTSEC-2021-0135

- crates/ftd2xx-embedded-hal/RUSTSEC-0000-0000.md
Has been renamed to `ftdi-embedded-hal`.
> Add unmaintained crate advisory for `ftd2xx-embedded-hal`

- crates/dashmap/RUSTSEC-2022-0002.md
v5.1.0 has just shipped with a fix
> Add patched version to DashMap advisory

- crates/libp2p-core/RUSTSEC-0000-0000.md
I am a maintainer of this crate and we have already published a fix for it. Opening this advisory so folks get notified of the vulnerability and can upgrade quickly.
> Add entry for libp2p-core vulnerability

- crates/enum-map/RUSTSEC-0000-0000.md
This was caused by a mistake during refactoring: https://gitlab.com/KonradBorowski/enum-map/-/commit/ec9eecd63114a40bfc2505cbb2a883dd0ef89d3f. Versions 2.0.0-2, 2.0.0 and 2.0.1 are affected.
> Add unsoundness advisory for enum-map

- crates/rust-crypto/RUSTSEC-0000-0000.md
`rust-crypto` appears to be unsound.
The following Rust program demonstrates some weirdness in AES encryption - if you have an immutable `key` slice and then iter() and cycle() on that slice, you get different encryption output than if you operate on a completely isolated copy of that key.
(For these functions, we expect that extending a 16 byte key to a 32 byte key by repeating it gives the same encrypted data, because the underlying `rust-crypto` functions repeat key data up to the necessary key size for the algorithm)
```rust
use crypto::{
aes, blockmodes, buffer,
buffer::{BufferResult, ReadBuffer, WriteBuffer},
symmetriccipher,
};
fn encrypt(
key: &[u8],
iv: &[u8],
data: &str,
) -> Result<String, symmetriccipher::SymmetricCipherError> {
let mut encryptor = …
```
> `rust-crypto`: miscomputation when performing AES encryption

- crates/rental/RUSTSEC-2021-0134.md
The author of `recursive_referene` has reached out to me and clarified that it does not serve the same use cases as `rental`
> RUSTSEC-2021-0134: Remove recursive_reference from the list of alternatives

- crates/regex/RUSTSEC-0000-0000.md
See [the disclosure of the vulnerability](https://groups.google.com/g/rustlang-security-announcements/c/NcNNL1Jq7Yw) for more information.
> Add CVE-2022-24713 (regex crate)

- crates/arrow2/RUSTSEC-2022-0012.md
@jorgecarleitao can you confirm this is true?
----
As far as I can tell, v0.10.0+ was not affected by this bug [0]. The commit which
fixes the unsoundness landed in main before v0.10.0 was released.
[0]: https://github.com/jorgecarleitao/arrow2/commit/9d4342c5ff2ff1593232373a9998c3da18c7854d
> RUSTSEC-2022-0012: note that v0.10.0+ is patched

- crates/time/RUSTSEC-2020-0071.md
Change platform names to those recognized by `platforms` crate
Drop `bitrig` which is not recognized by rustc
> fix platforms in RUSTSEC-2020-0071.md

- HOWTO_UNMAINTAINED.md
Initial guide on policy around what RustSec considers to be an unmaintained crate as well as the policy for filing an advisory.
This has come up / been requested often enough I thought I'd finally take a go at writing something up.
[Rendered](https://github.com/rustsec/advisory-db/blob/024202565812a765d3b02f32f74c08475689ac14/HOWTO_UNMAINTAINED.md)
> HOWTO_UNMAINTAINED.md: guide for unmaintained crate advisories

- crates/totp-rs/RUSTSEC-0000-0000.md
Versions below 1.1.0 are susceptible to a timing attack
- [GHSA](https://github.com/constantoine/totp-rs/security/advisories/GHSA-8vxv-2g8p-2249)
- [CVE-2022-29185](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-29185)
This has been fixed by using constant_time comparison in following versions
> Possible timing attack in totp-rs

- crates/crossbeam-channel/RUSTSEC-0000-0000.md
- crates/crossbeam-queue/RUSTSEC-0000-0000.md
- crates/crossbeam/RUSTSEC-0000-0000.md
This issue is ancient and has been fixed long ago, but it showed up in a [crater run](https://crater-reports.s3.amazonaws.com/pr-87041-1/try%23ddc023471205c186b40f4bf8ffb598008dbf4885/reg/advantage-0.1.0/log.txt) not too long ago so it might still be worth adding this to the database (considering that there are no other advisories against crossbeam-queue that might urge people to update).
Cc https://github.com/crossbeam-rs/crossbeam/pull/458
> add crossbeam advisories for incorrect (unsound) zeroed memory

- crates/hyper/RUSTSEC-0000-0000.md
Adds an advisory for the fix in https://github.com/hyperium/hyper/pull/2545.
> add hyper uninitialized memory advisory

- crates/static_type_map/RUSTSEC-0000-0000.md
It has been renamed to `erased_set`.
See latest [readme on crates.io](https://crates.io/crates/static_type_map) and https://github.com/malobre/erased_set/issues/6.
> Add unmaintained crate advisory for `static_type_map`

- crates/time/RUSTSEC-2020-0071.md
> Withdraw RUSTSEC-2020-0071: Potential segfault in the time crate

- crates/hyper/RUSTSEC-2022-0022.md
I typo'd the version number in https://github.com/rustsec/advisory-db/pull/1232 *oops*
> fix hyper patched version number

- crates/neon/RUSTSEC-0000-0000.md
In versions prior to Neon `0.10.1`, users could create a JavaScript buffer backed by bytes owned by Rust *without* the `'static` lifetime. The following example demonstrates how this could trivially result in a use-after-free bug.
```rust
pub fn soundness_hole(mut cx: FunctionContext) -> JsResult<JsArrayBuffer> {
let mut data = vec![0u8, 1, 2, 3];
// Creating an external from `&mut [u8]` instead of `Vec<u8>` since there is a blanket impl
// of `AsMut<T> for &mut T`
let buf = JsArrayBuffer::external(&mut cx, data.as_mut_slice());
// `buf` is still holding a reference to `data`!
drop(data);
Ok(buf)
}
```
> Use after free in Neon externally allocated JavaScript buffers

- crates/time/RUSTSEC-2020-0071.md
This reverts commit a47cd63007d20e5e0d58c4de945ac2e6b7cd70d0.
The advisory was withdrawn based on discussions around whether read-only
environment variable access constitutes a vulnerability.
However, per the `time` crate's author @jhpratt, the crate also modifies
the environment and therefore the advisory should *not* be withdrawn:
https://github.com/rustsec/advisory-db/pull/1242#issuecomment-1144903688
> Revert "Withdraw RUSTSEC-2020-0071: Potential segfault in the time crate (#1242)"

- crates/crossbeam/RUSTSEC-0000-0000.md
It is entirely unclear to me how far back this should extend, because it looks like crossbeam `0.2.9` and older don't compile (they try to do transmutes where the src and dst sizes don't match).
> Report data race/memory corruption in crossbeam 0.2

- crates/im/RUSTSEC-2020-0096.md
Fixed in https://github.com/bodil/im-rs/commit/0b3a7b228b0fe70446393f55c8b893f349f3f6bd
Brought to our attention by https://github.com/rustsec/advisory-db/pull/569#issuecomment-1149020755
> Add patched version to `im` RUSTSEC-2020-0096

- crates/openssl-src/RUSTSEC-2022-0025.md
- crates/openssl-src/RUSTSEC-2022-0026.md
- crates/openssl-src/RUSTSEC-2022-0027.md
Closes #1262 
On 2022-0025, 26 and 27 111 is affected and is reflected on openssl-src 111.20.0 that brings 1.1.1o (patched)
I folllowed RUSTSEC-2022-0014.md way to give effect to this
> Fix RUSTSEC-2022-0025,26,27 openssl-src for the 111 stream

- crates/pkcs11/RUSTSEC-0000-0000.md
#1280 
Feedback is more than welcome, I think the `Impact` section is a bit verbose :[ 
cc @5225225
> Add advisory for `pkcs11`

- crates/websocket/RUSTSEC-0000-0000.md
Note that in the Github advisory I forgot to mention that the main mitigation method is migration to other Websocket library like `tungstenite`.
`rust-websocket` should still be considered deprecated.
> Add advisory for websocket

- crates/term_size/RUSTSEC-0000-0000.md
Note that I've used the date when the unmaintained status was announced in the project's README for the date field.
> Add unmaintained advisory for term_size

- crates/sass-rs/RUSTSEC-0000-0000.md
Issue: https://github.com/compass-rs/sass-rs/issues/83
The deprecation/unmaintained status is also now noted in the README: https://github.com/compass-rs/sass-rs
> **This crate is not maintained anymore as libsass is deprecated. Consider using <https://github.com/connorskees/grass> or <https://github.com/kaj/rsass> instead.**
> sass-rs is deprecated

- crates/chrono/RUSTSEC-2020-0159.md
The 0.4.20 release of `chrono` includes a pure-Rust replacement for `localtime_r` which eliminates this issue.
> RUSTSEC-2020-0159 (chrono): add patched version

- .github/workflows/validate.yml
Unblocks #1234 for rustdecimal
rustsec-admin 0.8.0 changes:
https://github.com/rustsec/rustsec/pull/620
https://github.com/rustsec/rustsec/pull/621
And adds --skip-namecheck rustdecimal
> Bump rust-admin 0.8.0 --skip-namecheck rustdecimal

- crates/chrono/RUSTSEC-2020-0159.md
Now that there's an actionable fix, we should encourage people to upgrade
> RUSTSEC-2020-0159: remove "withdrawn"

- .github/workflows/assign-ids.yml
- rustdecimal ended up failing in CI at assign-id phase
- Lint check is done in the generated PR anyways so the lintcheck there is redundant where as on old push it wasn't
> Remove redundant lint check from assign-ids

- crates/tower-http/RUSTSEC-0000-0000.md
See: https://github.com/rustsec/advisory-db/pull/1319
Moving existing tower advisory from year 2021 to 2022
> Add tower-http 2022 version

- crates/tower-http/RUSTSEC-2021-0135.md
Moving tower-http year forward
See: https://github.com/rustsec/advisory-db/pull/1165
> Move tower-http out from year 2021

- crates/async-graphql/RUSTSEC-2022-0037.md
@djc looks like I didn't catch the patched on async-graphql
https://github.com/rustsec/advisory-db/issues/1285
https://github.com/rustsec/advisory-db/pull/1290
https://github.com/rustsec/advisory-db/pull/1298
Could you sanity ok this for me pls ? Thanks
> Fix async-graphql patched

- crates/markdown/RUSTSEC-0000-0000.md
The `markdown` crate is, naturally, the first one that comes up if you're searching crates.io for "markdown". Unfortunately, that particular crate has not received any updates since November of 2020 despite several known issues with open PRs. I opened https://github.com/johannhof/markdown.rs/issues/48 to request an update on maintenance status nearing a month ago and have not heard anything back.
I believe the best course is to list the crate as unmaintained so folks will (hopefully) correct course more quickly than I did 😅.
> List `markdown` as unmaintained

- crates/oqs/RUSTSEC-0000-0000.md
Wouter Castryck and Thomas Decru presented an efficient key recovery attack on the SIDH protocol.
As a result, the secret key of SIKEp751 can be recovered in a matter of hours.
The SIKE and SIDH schemes will be removed from the next oqs version 0.7.2.
> oqs: SIKE and SIDH are insecure

- crates/rocksdb/RUSTSEC-0000-0000.md
Draft. Will complete when the fix has landed.
> Add out-of-bounds read advisory for rocksdb

- crates/oqs/RUSTSEC-0000-0000.md
The Rainbow I parameterset as packaged in liboqs has been proven to be vulnerable to cryptanalysis. It's been removed from the upcoming (but not yet out) 0.7.2 release.
> oqs: PQC signature scheme Rainbow level I parameterset broken

- .github/workflows/validate.yml
Unblocks #1362 
By bumping rustsec-admin which ensures cache gets flushed and links with rustsec 0.26.1
Giving effect to this: https://github.com/rustsec/rustsec/pull/631
And this: https://github.com/rustsec/advisory-db/pull/1355
Cheers
> Bump rustsec-admin to deprecate `yanked`

- .github/workflows/validate.yml
- crates/directories/RUSTSEC-2020-0054.md
- crates/dirs/RUSTSEC-2020-0053.md
- crates/libpulse-binding/RUSTSEC-2020-0055.md
- crates/spin/RUSTSEC-2019-0031.md
- crates/tower-http/RUSTSEC-2021-0135.md
EDIT: Cache was the problem but there was different problem when I re-tested without cache - needs bump: https://github.com/rustsec/rustsec/pull/642
Some weird GH action cache thing / feature with pending / paraller PRs so Re-created this.
Following-Up from:
https://github.com/rustsec/advisory-db/pull/1362
After:
```
$ grep -R yanked *
crates/crossbeam-utils/RUSTSEC-2022-0041.md:Affected 0.8.x releases have been yanked.
crates/reorder/RUSTSEC-2021-0050.md:Previous versions have also been yanked from crates.io.
crates/spin/RUSTSEC-2019-0031.md:unaffected = [">= 0"] # workaround for `yanked = true` not removing the advisory
crates/sha2/RUSTSEC-2021-0100.md:The crate has since been yanked, but any users who upgraded to v0.9.7 should …
```
> Remove `yanked` 2

- crates/iana-time-zone/RUSTSEC-0000-0000.md
In iana-time-zone v0.1.43 a use-after-free bug in the MacOS / iOS implementation was introduced.
The copied system time zone was released before its name was copied.
If the system time zone was changed between the call of `CFRelease` and `str::to_owned()`,
random memory would be copied.
> iana-time-zone v0.1.{43,44}: Use after free in MacOS / iOS implementation

- crates/iana-time-zone/RUSTSEC-2022-0049.md
Because of the bug random data was read, but still written into a sane buffer.
> RUSTSEC-2022-0049: recategorize as memory-exposure

- crates/ansi_term/RUSTSEC-2021-0139.md
I got a notification for this and noticed that I can replace a use with `console` here.
> Added console to RUSTSEC-2021-0139

- crates/memmap/RUSTSEC-2020-0077.md
With the merge of https://github.com/RazrFalcon/memmap2-rs/pull/52 into `memmap2`,
all changes from `mapr` are ported upstream. Hence `memmap2` is now the single best
alternative.
> Remove mapr as alternativ from RUSTSEC-2020-0077

- crates/lz4-sys/RUSTSEC-0000-0000.md
Forwarding CVE-2021-3520. lz4-sys 1.9.4 has not yet been released.
> lz4-sys: Forward CVE-2021-3520

- crates/mapr/RUSTSEC-0000-0000.md
Follow-up from: https://github.com/rustsec/advisory-db/pull/1381
> Add unmaintained `mapr`

- crates/time/RUSTSEC-2020-0071.md
It is already the url of the advisory metadata, and the internal github link does not render outside of github.
> Remove reference mention from description

- CONTRIBUTING.md
To be able to [render it on rustsec.org](https://github.com/rustsec/rustsec/issues/669).
> Change CONTRIBUTING.md wording to make it usable outside of the repo

- crates/ansi_term/RUSTSEC-2021-0139.md
Linking structopt/clap2 specific actionable advice: https://github.com/clap-rs/clap/discussions/4172 under `ansi_term`
Not sure if this is feasible but see what others think :woman_shrugging: 
As seen here:
- https://github.com/clap-rs/clap/discussions/4172
- https://github.com/TeXitoi/structopt/issues/525
- https://github.com/mrl5/vulner/issues/59#issuecomment-1221388712
- https://docs.rs/structopt/latest/structopt/#maintenance
I've asked @epage and @TeXitoi whether it would be also feasible to advice informational under `structopt` to optionally move to `clap` v3 but it will be @TeXitoi's sole decision if they wish to do that - the crate should be still fine to use as-is I think though.
> Mention `structopt` advice under `ansi_term`

- README.md
This is / was creating confusion.
Informational is a security advisory as any advisory in this database.
However it is just different type and intepretation depends on individual / project circumstances / needs which we don't dictate on.
Advisories are not issues and it is important not to use confusing convoluted footnotes / adjectives like "non-security".
We need to put more public education around unmaintained, perhaps into the website.
> Fix informational footnote wording

- crates/clipboard/RUSTSEC-0000-0000.md
This PR adds an maintenance warning about the `rust-clipboard` crate. It has not been updated in years and, at this point, two forks of it are the most viable alternatives. Due to its age, it also depends on several unsound crate versions too. As a disclaimer, I am the primary maintainer of the `arboard` crate.
I also included platform-specific alternatives in case users are only developing for a single platform. Please let me know if I should remove them.
> Add unmaintained `clipboard`

- crates/badge/RUSTSEC-0000-0000.md
Closes #1401
The `badge` crate is unmaintained and depends on the deprecated `rusttype` crate.
I created a fork `badgers` that replaced `rusttype` with `ab_glyph` and keeps the same public API.
> Add unmaintained `badge`

- crates/inconceivable/RUSTSEC-0000-0000.md
This is similar to [plutonium](https://github.com/rustsec/advisory-db/tree/main/crates/plutonium).
> add inconceivable

- crates/orbtk/RUSTSEC-0000-0000.md
As per their ["OrbTk is Sunsetting"](https://github.com/redox-os/orbtk/blob/eba9e77821551076bbf1d9f7ab44d788150e3446/README.md#orbtk-is-sunsetting) announcement.
CC @jackpot51, @rzerres, @FloVanGH to confirm this.
> Add unmaintained `orbtk`

- crates/parity-wasm/RUSTSEC-0000-0000.md
The crate was explicitly deprecated by the author. The repo is archived and there is a note on top of the readme: https://github.com/paritytech/parity-wasm
> Add unmaintained `parity-wasm`

- crates/rustsec-example-crate/RUSTSEC-2019-0024.md
Needed for writing an automated test for https://github.com/rustsec/rustsec/issues/747
> Make rustsec-example-crate v0.0.0 unaffected to allow testing yanked checks

- crates/atty/RUSTSEC-0000-0000.md
See issue #1457.
@pinkforest Something like this?
> Add `atty` potential unsoundness (unaligned read) advisory

- crates/slock/RUSTSEC-2020-0135.md
The [slock](https://crates.io/crates/slock) crate no longer has the issue described in the advisory
> Patched slock

- crates/hyper-staticfile/RUSTSEC-0000-0000.md
This adds an advisory for https://github.com/stephank/hyper-staticfile/issues/35.
The contents are heavily based on an existing `tower-http` advisory: https://github.com/rustsec/advisory-db/blob/a66a3049c98395410a2afadf0382882b0a04d8b1/crates/tower-http/RUSTSEC-2022-0043.md
> Add hyper-staticfile file disclosure on Windows

- crates/secp256k1/RUSTSEC-0000-0000.md
Summary: Unsound API in `secp256k1` allows use-after-free and invalid deallocation from safe code. This was fixed and backported to multiple versions.
I'm not sure whether the `date` field should have todays date, will change if it needs something else.
Cc @apoelstra @tcharding
> Add soundness bug in `secp256k1` API

- crates/rusoto_credential/RUSTSEC-0000-0000.md
Hi. I'm ostensibly one of the maintainers of Rusoto, here to report its lack of maintenance.
[Rusoto has been deprecated for a while](https://github.com/rusoto/rusoto/issues/1651#issuecomment-1108012975); this is a more formalized notice of such to help churn downstream automation to make it clear that users need to migrate to aws-sdk-rust.
This is a somewhat unique case for the RustSec advisory DB, I think. The Rusoto project is made up of a little over 200 separate crates, but every crate in the tree either is or depends on `rusoto_credential`. Most users don't directly depend on `rusoto_credential` though, so I feel that listing an advisory for only that crate is a bit confusing, but hopefully downstream systems show the full description for context.
> Add unmaintained `rusoto_credential`

- crates/hyper-staticfile/RUSTSEC-0000-0000.md
This adds an advisory for an open redirect issue discovered in `hyper-staticfile`. Hopefully it's okay that this doesn't have a URL attached. There's no issue for this in the issue tracker; it was reported to us directly by a security partner analyzing an application using this crate.
> Add open redirect issue in hyper-staticfile

- .github/workflows/assign-ids.yml
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> update GHA syntax for deprecation

- crates/alloc-cortex-m/RUSTSEC-0000-0000.md
Has been renamed to `embedded-alloc`.
> Add unmaintained crate advisory for `alloc-cortex-m`

- LICENSE.txt
Allows importing advisories with attribution from GHSA
EDIT: This is so that it will be ready for the tooling https://github.com/rustsec/rustsec/pull/682
> Add License CC-BY 4.0 Import exemption

- crates/git2/RUSTSEC-0000-0000.md
When I read the Rust upstream reports about the cargo vuln, I was surprised and investigated what the underlying bug is.  It appears to me to be in `git2-rs`, and I think other callers will be affected.
> Make a RUSTSEC advisory for CVE-2022-46176 (git2-rs, cargo)

- crates/claim/RUSTSEC-0000-0000.md
As discussed in https://github.com/svartalf/rust-claim/issues/12, and originally requested in #1479. See also the discussion in https://github.com/svartalf/rust-claim/issues/9, which led to the eventual forking of the crate.
I wrote a bit here about the issue surrounding the crate's dependency issues which have needed fixing, as well as the maintained fork, `claims`.
> Report claim as unmaintained.

- crates/bumpalo/RUSTSEC-0000-0000.md
This adds an informational advisory regarding a soundness bug that was fixed in the most recent version of `bumpalo`.
> Add informational advisory for bumpalo Vec iterator unsoundness

- crates/twoway/RUSTSEC-0000-0000.md
The author deprecated the crate himself, but it's part of many web related crates, mostly related to `form/multipart` handling.
> Add unmaintained `twoway`

- crates/elf_rs/RUSTSEC-2022-0079.md
The issue was confirmed to be fixed in v0.3.0 by the person who reported the issue: https://github.com/vincenthouyi/elf_rs/issues/11#issuecomment-1384624749
> Add patched info for RUSTSEC-2022-0079 (elf_rs)

- crates/json/RUSTSEC-0000-0000.md
A thread on Reddit yesterday led me to investigate a few different JSON crates in the ecosystem. One of the most popular ones beyond serde-json that reported fast benchmarks is [`json`](https://crates.io/crates/json). I investigated it and discovered [users have asked](https://github.com/maciejhirsz/json-rust/issues/205) if the project is abandoned without reponse. Given how popular this crate appears to be given the recent downloads, I felt an unmaintained advisory was warranted.
Scanning the issues list, I also found [this issue](https://github.com/maciejhirsz/json-rust/issues/196) that may introduce undefined behavior. This triggers a Miri error under the stacked borrows model, but I'm not sure if that's enough to warrant a mention in the advisory or not.
> Report json as unmaintained

- crates/warp/RUSTSEC-0000-0000.md
Fixes #1524. I put the date as 2023, since that is the creation date of this advisory. However, this security issue was filed back in 2022. Let me know if I should change the dates.
> Add advisory for warp#937

- crates/daemonize/RUSTSEC-0000-0000.md
Closes #1543
Adds a unmaintained advisory for `daemonize`.
When looking for possible alternatives there are not really any suitable options that immediately jump out at me. Most of them have comparably much lower usage or also seem to be unmaintained.
> Add unmaintained `daemonize`

- crates/personnummer/RUSTSEC-0000-0000.md
Closes #1491 
I've added it as `informational = "notice"` since it's low impact
Cc/ @Johannestegner
> Add `personnummer`

- crates/tokio/RUSTSEC-0000-0000.md
Closes #1532 
Cc/ @zachs18 @carllerche - this `informational = "unsound"`
So not a full advisory but anyways
> Add tokio `io::ReadHalf<T>::unsplit` unsound

- crates/claim/RUSTSEC-2022-0077.md
Added in the missing letter. Also added a period at the end of the sentence :)
> Fix typo in `claim` advisory.

- crates/tauri/RUSTSEC-0000-0000.md
Addresses CVE-2022-39215 of #1485.
> Add advisory for Tauri readDir

- crates/aliyun-oss-client/RUSTSEC-0000-0000.md
Closes #1486 
I can't find an original issue that identifies the bug on the package's [GitHub issues](https://github.com/tu6ge/oss-rs/issues?q=) so I linked to the CVE in the `url` attribute and used the date on the CVE.
> Add advisory aliyun-oss-client

- crates/pnet_packet/RUSTSEC-0000-0000.md
Closes #1473 
I took many of the metadata details from [RUSTSEC-2019-0037](https://github.com/rustsec/advisory-db/blob/main/crates/pnet/RUSTSEC-2019-0037.md) as #1473 (and the original [issue](https://github.com/libpnet/libpnet/issues/449)) indicates that this is its root cause.
> Add advisory for pnet_packet

- crates/libsqlite3-sys/RUSTSEC-0000-0000.md
Closes #1446 
One thing I noticed is that the NIST link to the CVE does not exist (see [here](https://nvd.nist.gov/vuln/detail/CVE-2022-35737)), but I could find it on the Wayback machine (see [here](https://web.archive.org/web/20221027155821/https://nvd.nist.gov/vuln/detail/CVE-2022-35737)). So not sure if the CVE is still valid.
> Add sqlite advisory

- crates/tauri/RUSTSEC-0000-0000.md
Closes #1485 
This advisory affects multiple ranges of versions (>= 1.0.0, < 1.0.7 and >= 1.1.0, < 1.1.2) so was not sure of the correct representation in the advisory format.
There is not an official cvss number on the CVE so I took liberties with the [Calculator](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:C/C:L/I:N/A:N). I feel that it was a bit of guesswork on my part.
> Add advisory Tauri filesystem scope bypass

- crates/partial_sort/RUSTSEC-0000-0000.md
Should not really be a vulnerability, because callers would have to validate the parameter anyway to avoid panics, but I figured I'd file an informational advisory regarding https://github.com/sundy-li/partial_sort/issues/7 anyway, now that a fixed version is released.
cc @sundy-li
> Add informational advisory for partial_sort out-of-bounds read

- crates/maligned/RUSTSEC-0000-0000.md
> `maligned::align_first` causes incorrect deallocation

- crates/nphysics2d/RUSTSEC-0000-0000.md
- crates/nphysics3d/RUSTSEC-0000-0000.md
There is no activity since July 2021 and the maintainer has advised that this crate is passively-maintained since January 2021.
> Add unmaintained advisory for nphysics

- crates/ncollide2d/RUSTSEC-0000-0000.md
- crates/ncollide3d/RUSTSEC-0000-0000.md
There is no activity since March 2022 and the maintainer has advised that this crate is passively-maintained since January 2021.
> Add unmaintained advisory for ncollide

- crates/out-reference/RUSTSEC-0000-0000.md
> `out_reference::Out::from_raw` should be `unsafe`

- crates/const-cstr/RUSTSEC-0000-0000.md
const-cstr is crate by @abonander who has archived bunch of his Rust crates in GitHub.
See communication attempts on other crates:
* https://github.com/rustsec/advisory-db/issues/1602
* https://github.com/rustsec/advisory-db/issues/1438
> Add unsound `const-cstr`

- crates/wasmtime/RUSTSEC-2022-0076.md
The details page at https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-44mr-8vmm-wjhg says the v1 also has a patched release.
> Update RUSTSEC-2022-0076.md with v1 patch

- crates/wasmtime/RUSTSEC-2022-0076.md
This is technically required for correctness, as v1 doesn't have this fn at all.
> A follow-up after #1645

- crates/stb_image/RUSTSEC-0000-0000.md
A bug in error handling in the `stb_image` C library could cause a NULL pointer dereference when attempting to load an invalid or unsupported image file.  This is fixed in version 0.2.5 and later of the `stb_image` Rust crate, by patching the C code to correctly handle NULL pointers.
See https://github.com/servo/rust-stb-image/pull/102 for more details.
> NULL pointer dereference in stb_image

- crates/rmp-serde/RUSTSEC-0000-0000.md
Closes #1426 
Adds advisory for unsound behaviour of `rmp-serde < 1.1.1`.
> Add unsound `rmp-serde`

- crates/async-nats/RUSTSEC-0000-0000.md
The following vulnerability has been reported by me to https://advisories.nats.io/ and fixed in `async-nats` 0.29. Once this is merged I'll copy-paste the vulnerability and also apply it to the `nats` crate, which presents the exact same issue.
~~I'm opening this as draft because there are some things I'd like to cleanup in the report which I don't have the time to do right now. For now I simply copy-pasted part of the report I also sent to Synadia.~~
~~I wasn't sure **which category to put this in**, as none seemed to apply.~~
All versions of `async-nats` are affected, while very early versions of the `nats` crate aren't because they don't support TLS.
If a CVE is requested by the Synadia Security Team I'll update the advisory with the CVE ID.
> async-nats MitM vulnerability

- crates/buf_redux/RUSTSEC-0000-0000.md
buf_redux is crate by @abonander who has archived bunch of his Rust crates in GitHub including this one.
No reaction to any open pull request or issues since 2019 in the repository. Last crates.io release also from 2019.
My question about maintenance status has been unanswered so far https://github.com/abonander/buf_redux/issues/22
And there's also future incompatibility warning https://github.com/abonander/buf_redux/issues/23.
Fixes #1602
> Add unmaintained `buf_redux`

- nats/RUSTSEC-0000-0000.md
copy-pasted from #1661.
~~No fixes have been released since the crate is considered deprecated (see https://github.com/nats-io/nats.rs#nats)~~
> nats MitM vulnerability

- crates/versionize/RUSTSEC-0000-0000.md
Hello, 
please consider adding this advisory about the `versionize` crate to the Rust advisory database.
Thank you, 
Patrick Roy
> Advisory for versionize crate

- crates/spin/RUSTSEC-0000-0000.md
This should only be merged when the fix in https://github.com/mvdnes/spin-rs/pull/149 has merged and a new version (`0.9.8`) is released.
> Added unsound `spin`

- crates/ntru/RUSTSEC-0000-0000.md
I suspect that this unsoundness can also result in a crypto-fail with just the right kind of wrong parameters, but that'd kind of be the users fault.
It also [seems like](https://github.com/FrinkGlobal/ntru-rs/issues/7) ntru is unmaintained. Should I submit a separate advisory / separate PR for that?
> Add ntru unsoundness advisory

- crates/daemonize/RUSTSEC-2021-0147.md
Withdraw the unmaintained advisory for `daemonize` requested in #1543.
On Feb 19 2023, the author started to maintain the `daemonize` crate again.
Version 0.5.0 has been released on Feb 25 2023.
Therefore, this crate in no longer unmaintained and advisory `RUSTSEC-2021-0147` should be withdrawn.
> Withdraw RUSTSEC-2021-0147

- crates/h2/RUSTSEC-0000-0000.md
(should not be merged as is at writing this comment, see following comment)
> Add advisory for h2: resource exhaustion vulnerability may lead to DoS

- crates/kuchiki/RUSTSEC-2023-0019.md
The `kuchiki` crate has been marked unmaintained. We're continuing to support a fork under then name `kuchikiki` which we intend to remain semver-compatible with our former upstream.
Suggest this as an alternative in RUSTSEC-2023-0019 since it is a direct replacement; the other alternatives involve significant porting effort.
> Suggest kuchikiki as an alternative to kuchiki

- crates/sequoia-openpgp/RUSTSEC-0000-0000.md
Attacker-controlled input can lead to an out-of-bounds index, which causes sequoia-openpgp to panic.  This has been fixed in versions 1.16.0, 1.8.1, and 1.1.1 of sequoia-openpgp.
> Add advisory for sequoia-openpgp

- crates/buffered-reader/RUSTSEC-0000-0000.md
Attacker-controlled input can lead to an out-of-bounds index, which causes buffered-reader to panic.  This has been fixed in versions 1.2.0, 1.1.5, and 1.0.2 of buffered-reader.
> Add advisory for buffered-reader

- crates/users/RUSTSEC-0000-0000.md
The `users` crate hasn't seen any action since 2020-10-08. The developer seems [MIA] since.
I failed to find a direct replacement that's maintained but [`sysinfo`] crate provides the same
functionality since the last release.
[MIA]: https://github.com/ogham/rust-users/issues/54
[`sysinfo`]: https://crates.io/crates/sysinfo
> 🦺 Advisory for unmaintained crate, `users`

- crates/trust-dns-server/RUSTSEC-0000-0000.md
An attacker can form packet loops between vulnerable instances, leading to a denial-of-service for both network and CPU resources.
My supervisor (@crossow) and I found and reported the issue. @bluejekyll and @djc have acknowledged and resolved the issue.
Questions:
1. The same advisory should apply to both `trust-dns` and `trust-dns-server`. Is there a way to have a single advisory (i.e., single identifier) target multiple crates?
2. Affected is the type `trust_dns_server::server::ServerFuture`, not a specific public function. It seems that cannot be encoded via `[affected]`.
> Vulnerability in trust-dns and trust-dns-server

- crates/ftp/RUSTSEC-0000-0000.md
Report for unmaintained `ftp` crate. Use `suppaftp` instead
> Add unmaintained ftp crate

- crates/atty/RUSTSEC-2021-0145.md
Since `IsTerminal` is now stable, this CVE can recommend that first. It should at least not lie about it being nightly only any longer.
> Update RUSTSEC-2021-0145.md with stable IsTerminal

- crates/dlopen_derive/RUSTSEC-0000-0000.md
`dlopen_derive` hasn't been updated since June 9, 2019.
`dlopen_derive` depends on [`quote = "0.6.12"`] and [`syn = "0.15.34"`]. Versions `1.0.0` of these dependencies were published on August 13, 2019. The `0.*` versions haven't received updates since.
- [`dlopen2_derive`]
[`dlopen2_derive`]: https://github.com/OpenByteDev/dlopen2
[`quote = "0.6.12"`]: https://github.com/dtolnay/quote/releases/tag/0.6.12
[`syn = "0.15.34"`]: https://github.com/dtolnay/syn/releases/tag/0.15.34
> Add unmaintained `dlopen_derive` advisory

- crates/users/RUSTSEC-2023-0040.md
Following up on #1701
We use `users` in https://github.com/eza-community/eza so I decided to fork `users` to https://github.com/gierens/uzers-rs . I reviewed merged existing pull requests and plan to maintain it there. It's also on crates.io in version v0.11.1, see https://crates.io/crates/uzers 
This change adds `uzers` to the recommended alternatives for `users`.
> Add uzers as alternative recommendation for users

- crates/mail-internals/RUSTSEC-0000-0000.md
I published [mail-internals-ng](https://git.sr.ht/~nabijaczleweli/mail-internals.crate/log), [mail-headers-ng](https://git.sr.ht/~nabijaczleweli/mail-headers.crate/log), and [mail-core-ng](https://git.sr.ht/~nabijaczleweli/mail-core.crate/log), and using those fixes the [libc SIGABRTs](https://101010.pl/@nabijaczleweli/110848198894141586) in feembox.
> mail-internals memory corruption

- crates/json/RUSTSEC-2022-0081.md
Following up on #1536
I'm currently gathering people in a community that should specialize on adopting abandoned Rust projects and so `json` was brought to my attention. We forked it to https://github.com/rustadopt/jzon-rs/ and plan to maintain it there. We already reviewed and merged pull requests, polished things like the CI and are currently checking out reported issues. It is now also available in version v0.12.5 on crates.io, see https://crates.io/crates/jzon .
This change adds `jzon` to the recommended alternatives for `json`.
> Add jzon as alternative recommendation for json

- crates/ed25519-dalek/RUSTSEC-2022-0093.md
- crates/mail-internals/RUSTSEC-2023-0054.md
- crates/rustdecimal/RUSTSEC-2022-0042.md
- crates/rustls-webpki/RUSTSEC-2023-0053.md
- crates/webpki/RUSTSEC-2023-0052.md
Side note: advisories parsing is currently broken in the [sync command](https://github.com/rustsec/rustsec/pull/656) due to https://github.com/github/advisory-database/issues/2665 (added local workarounds to get it working though.
> Sync advisories ids from GitHub

- crates/webpki/RUSTSEC-2023-0052.md
* Indicate release version that the fix landed in.
* Remove unnecessary noise from the text.
> Update webpki RUSTSEC-2023-0052 advisory.

- crates/lexical/RUSTSEC-0000-0000.md
> Add an advisory for lexical

- crates/vm-memory/RUSTSEC-0000-0000.md
Hello,
please consider adding this advisory about the `vm_memory` crate to the Rust advisory database.
Thank you,
Patrick Roy
> Import CVE-2023-41051 as RustSec advisory

- crates/ansi_term/RUSTSEC-2021-0139.md
add [rustadopt](https://github.com/rustadopt/ansiterm-rs) fork ( crates.io/crates/ansiterm ) as an alternative to ansi_term crate.
This is in use by us over at [Eza](https://github.com/eza-community/eza) and maintained by a few of the same people.
> add additional replacement for ansi_term

- crates/inventory/RUSTSEC-0000-0000.md
I am reporting this against `inventory` even though the affected unsafe code lives in the `ctor` crate. I believe the majority of usages of `ctor` use it soundly. In fact inventory 0.2, which uses the same version of ctor as inventory 0.1, uses it in a manner that is not affected by this bug.
- Relevant standard library issue: https://github.com/rust-lang/rust/issues/110708
- Relevant inventory PR: https://github.com/dtolnay/inventory/pull/43
> Inventory 0.1 is unsound (allows std access before init of Rust runtime)

- crates/inventory/RUSTSEC-0000-0000.md
- https://github.com/dtolnay/inventory/pull/42
> Inventory 0.1 is unsound (exposure of non-Sync reference)

- crates/users/RUSTSEC-0000-0000.md
Closes https://github.com/rustsec/advisory-db/issues/1731.
I looked for an `unaffected` version. As far as I can tell, this bug has been present since the initial commit and initial version of this crate. The buggy code is introduced here:
- https://github.com/ogham/rust-users/commit/336223239a407069533b00c329ffe34454efa882#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R221-R245
and only slightly refactored by https://github.com/ogham/rust-users/commit/4c966938db5eb1528e8c26a0c1d5ac9747a6a67b.
The existing `unmaintained` advisory for this crate mentions `uzers` as an alternative:
https://github.com/rustsec/advisory-db/blob/d30ca831602ec928feaba99d7a04bb2a17643f73/crates/users/RUSTSEC-2023-0040.md#L17-L23
but I have not included that crate in this advisory because it …
> Unaligned read in `users`

- crates/users/RUSTSEC-2023-0059.md
see https://github.com/rustsec/advisory-db/pull/1778#issuecomment-1716122937
`uzers` was already listed as an alternative on the slightly older "unmaintained" advisory (RUSTSEC-2023-0040), but it is missing from the new one (unaligned pointer reads).
> RUSTSEC-2023-0059: add "uzers" fork as alternative for "users"

- crates/libwebp-sys/RUSTSEC-0000-0000.md
- crates/libwebp-sys2/RUSTSEC-0000-0000.md
libwebp has an exploitable heap buffer overflow. There are two Rust sys crate that have bundled the vulnerable version of libwebp. Both sys crates are patched now.
> CVE-2023-4863 in vendored libwebp

- crates/bcder/RUSTSEC-0000-0000.md
The bcder crate has a number of issues resulting in panics when decoding invalid BER/CER/DER encoded data which may result in denial-of-service in applications using the crate.
> CVE-2023-39914 in bcder.

- crates/gix-transport/RUSTSEC-0000-0000.md
Reproducer with `gix` (CLI) v0.29
* `gix clone 'ssh://-oProxyCommand=open$IFS-aCalculator/foo'`
- This will launch a calculator on OSX.
Fixed in `gix` (CLI) v0.30.
See https://secure.phabricator.com/T12961 for more details.
This issue was discovered by @vin01 whom I thank for their diligence!
> Add notice to gix-transport crate

- crates/libwebp-sys/RUSTSEC-2023-0061.md
- crates/libwebp-sys2/RUSTSEC-2023-0060.md
There is finally a CVE specifically for libwebp that doesn't suggest it's a Chrome-only problem.
> Update info about CVE-2023-5129

- crates/tungstenite/RUSTSEC-0000-0000.md
@daniel-abramov @agalakhov please have a look. I noticed this via GitHub's vulnerability reporting system, but would be nice to have this in the RustSec advisory database, too (because it triggers tools like cargo-audit and cargo-deny).
> Create advisory for tungstenite DoS

- crates/pleaser/RUSTSEC-0000-0000.md
Note that the reproducer doesn't work out of the box on a modern kernel, as the ioctl TIOCSTI is disabled by default nowadays.
> Document the privilege-escalation vulnerability in pleaser.

- crates/owning_ref/RUSTSEC-2022-0040.md
I've just taken my original fix and pull request for `owning_Ref` and made it into a crate,
So now people using `owning_ref` can be directed to that as a possible replacement.
> Updating information about replacements for owning_ref

- crates/streebog/RUSTSEC-2019-0030.md
RUSTSEC-2019-0030 lists CVE-2020-25575 & GHSA-jq66-xh47-j9f3 as aliases, but they don't seem to be related.
CC: https://github.com/github/advisory-database/pull/2907
> Remove CVE-2020-25575 from RUSTSEC-2019-0030 aliases

- crates/nats/RUSTSEC-2023-0029.md
Depends on the release of https://github.com/nats-io/nats.rs/pull/1157
> Add patched version to RUSTSEC-2023-0029

- crates/rsa/RUSTSEC-0000-0000.md
See: https://github.com/RustCrypto/RSA/issues/19#issuecomment-1822995643
https://people.redhat.com/~hkario/marvin/
> Add Marvin Attack on `rsa` crate

- crates/rsa/RUSTSEC-2023-0071.md
The `##` headers are huge when rendered on rustsec.org
> RUSTSEC-2023-0071.md: use `###` section headers

- crates/candid/RUSTSEC-0000-0000.md
Add security advisory for a denial-of-service vulnerability in candid crate
> Add advisory for candid library decoding DoS vulnerability

- crates/rsa/RUSTSEC-2023-0071.md
CVSS score has been updated by the package maintainer:
- https://github.com/github/advisory-database/pull/3030
- https://github.com/advisories/GHSA-c38w-74pg-36hr
Moreover, there is a duplicate [GHSA-4grx-2x9w-596c](https://github.com/advisories/GHSA-4grx-2x9w-596c) which should be mentioned as alias.
> Update CVSS score and aliases of RUSTSEC-2023-0071

- crates/unsafe-libyaml/RUSTSEC-0000-0000.md
https://github.com/dtolnay/unsafe-libyaml/issues/21
> Unaligned write in `unsafe-libyaml`

- crates/cpython/RUSTSEC-0000-0000.md
The developer recently documented that the crate is not actively maintained: https://github.com/dgrunwald/rust-cpython/commit/e815555
I added links to two possible security / safety issues that are present in all recent versions, and a link to the recommended replacement.
> Add unmaintained advisory for cpython

- crates/ferris-says/RUSTSEC-0000-0000.md
https://github.com/rust-lang/ferris-says/pull/21
> Unsound use of str::from_utf8_unchecked in ferris-says

- crates/vmm-sys-util/RUSTSEC-0000-0000.md
Hello there,
Could you please consider accepting this advisory about the rust-vmm `vmm-sys-util` crate?
Cheers,
Babis
> Import CVE-2023-50711 as RustSec advisory

- crates/tracing/RUSTSEC-0000-0000.md
This PR adds an advisory for unsoundness in the
`tracing::instrument::Instrumented::into_inner` method in versions 0.1.38 and 0.1.39. This issue was corrected in v0.1.40.
> Add soundness advisory for `tracing` 0.1.38 and 0.1.39

- crates/cosmwasm/RUSTSEC-0000-0000.md
Hi! I'm one of the original maintainers of the cosmwasm crate. This is unmaintained for a long time for for some reason, it is still downloaded. Would be great to be able to mark it as unmaintained.
> Mark crate `cosmwasm` as unmaintained

- crates/rust-i18n-support/RUSTSEC-0000-0000.md
- crates/rust-i18n/RUSTSEC-0000-0000.md
Version 3.0.0 introduced an `AtomicStr` type, that is used to store the current locale. It stores the locale as a raw pointer to an `Arc<String>`. The locale can be read with `AtomicStr::as_str()`. `AtomicStr::as_str()` does not increment the usage counter of the `Arc`.
If the locale is changed in one thread, another thread can have a stale -- possibly already freed -- reference to the stored string.
> rust-i18n-support: Use-after-free when setting the locale

- crates/pqc_kyber/RUSTSEC-0000-0000.md
The CVSS score was a guess from me, as I couldn't find anyone else that had done a CVSS evaluation.
The crate have a security policy where they ask that issues should be privately reported to them, but this is already public information.
> Add advisory for the kyberslash timing attack

- crates/snow/RUSTSEC-0000-0000.md
Main report: https://github.com/mcginty/snow/security/advisories/GHSA-7g9j-g5jg-3vv3
In short: A logic bug was missed that allowed an internal nonce to be incremented even when a received payload was not successfully decrypted, opening up the possibility of an easy denial-of-service attack for those who have the ability to inject data into the channel that is used for Noise.
> snow: Unauthenticated Nonce Increment

- crates/generational-arena/RUSTSEC-0000-0000.md
Closes #1883
I included the url for the unanswered maintenance issue, even though this advisory is prompted by the archival of that repository. Let me know if I should just omit that field or if I need to be more descriptive.
> Add unmaintained advisory for `generational-arena`

- crates/filesystem/RUSTSEC-0000-0000.md
The `filesystem` crate (repo URL <https://github.com/iredelmeier/filesystem-rs>) appears to be implicitly unmaintained. The main branch has not been updated for 4+ years, and [this pull request](<https://github.com/iredelmeier/filesystem-rs/pull/29>) from 10 months ago to fix unmaintained dependencies has not been addressed; [this comment](<https://github.com/iredelmeier/filesystem-rs/pull/29#issuecomment-1493898927>) within that PR poses the question of maintenance.
> Add unmaintained advisory report for filesystem-rs

- crates/safemem/RUSTSEC-0000-0000.md
safemem is crate by @abonander who has archived bunch of his Rust crates in GitHub.
See communication attempts on other crates:
* https://github.com/rustsec/advisory-db/issues/1602
* https://github.com/rustsec/advisory-db/issues/1438
> Add unmaintained advisory for safemem

- crates/cassandra-cpp/RUSTSEC-0000-0000.md
Hi - raising a RUSTSEC for an issue reported and fixed in cassandra-cpp crate. I am the maintainer of this crate. I've raised a GHSA and requested a CVE via GitHub but it hasn't yet been assigned.
> cassandra-cpp: non-idiomatic use of iterators leads to use after free

- crates/crayon/RUSTSEC-0000-0000.md
The crate already has an informational advisory, and this is clearly a separate issue despite affecting the same code.
Discovered via https://asan.saethlin.dev/ub?crate=crayon&version=0.7.1 . I considered removing `informational=unsound` on the previous advisory, but the issue it describes can be worked around with careful usage, while this issue is unconditional UB in extremely basic usage of the crate.
The crate does not appear to have any reverse dependents on crates.io except its own libraries, so the utility of this advisory is questionable, but clearly someone attempted to use it or else the previous advisory would not have been created.
> Add non-informational crayon advisory

- crates/safemem/RUSTSEC-2023-0081.md
- as suggested in <https://github.com/rustsec/advisory-db/pull/1615#issuecomment-1977169576>
> add migration instructions for safemem

- crates/whoami/RUSTSEC-0000-0000.md
See:
* https://github.com/ardaku/whoami/issues/91
* https://github.com/ardaku/whoami/issues/97
Questions:
* Some other Unix platforms may also be affected. It's hard to enumerate a full list here, but happy to add them as they come to mind for people.
> Add advisory for stack buffer overflow with whoami

- crates/whoami/RUSTSEC-2024-0020.md
Add information about more platforms affected, per https://github.com/rustsec/advisory-db/pull/1911#issuecomment-1978963801.
> update RUSTSEC-2024-0020 with additional information

- crates/yaml-rust/RUSTSEC-2024-0320.md
> Add an unmaintained crate advisory for yaml-rust

- crates/rsa-export/RUSTSEC-0000-0000.md
I am the original author and sole owner of this crate on crates.io.  
The source code is available on GitLab, as linked from the crate page.
I formally deprecated this crate 3-or-so years ago but there are surprisingly still users for it.
Considering the crate is unmaintained *and* the encoding is still done using variable time encodings, exposing the users to risks such as [Util::Lookup](https://arxiv.org/pdf/2108.04600.pdf), I've decided to finally file a RustSec advisory to hopefully get them to move.
> File unmaintained advisory for `rsa-export`

- crates/libp2p-tokio-socks5/RUSTSEC-0000-0000.md
I was the original author and am still the crate owner (on crates.io), I do not, however have write access to the source repository because I no longer work for the company that controls it.
I stopped maintaining this crate in 2021 but did not know about the RustSec Advisory process then.
> Add unmaintained advisory for libp2p-tokio-socks5

- crates/tor-circmgr/RUSTSEC-0000-0000.md
There are going to be two advisories.  There are in fact two bugs due to entirely different code paths, with similar impact.
I am making these as separate MRs since doing otherwise would probably break some tooling.
> Add advisory for tor-circmgr TROVE-2024-003

- crates/nano-id/RUSTSEC-0000-0000.md
This patch adds an advisory for [nano-id](https://crates.io/crates/nano-id) crate. I reported this vulnerability to the maintainer of the crate (@fundon) and got permission to disclose this.
> Add advisory for nano-id crate

- crates/time/RUSTSEC-2020-0071.md
> Clarify that RUSTSEC-2020-0071 is about `time` setting env vars

- crates/nano-id/RUSTSEC-2024-0343.md
Added following aliases to RUSTSEC-2024-0343.
- https://github.com/advisories/GHSA-2hfw-w739-p7x5
- https://github.com/advisories/GHSA-9hc7-6w9r-wj94
- https://nvd.nist.gov/vuln/detail/CVE-2024-36400
> Add aliases to RUSTSEC-2024-0343

- crates/curve25519-dalek/RUSTSEC-0000-0000.md
This impacts scalar types which represent private keys and other secrets. This vulnerability could potentially result in leakage of these values by observing the variability.
> Add advisory for curve25519-dalek timing variability

- crates/curve25519-dalek/RUSTSEC-2024-0344.md
Adds angle brackets to all links so they render properly on rustsec.org
> RUSTSEC-2024-0344: fix links

- crates/sequoia-openpgp/RUSTSEC-0000-0000.md
There is a denial-of-service vulnerability in sequoia-openpgp, our crate providing a low-level interface to our OpenPGP implementation. When triggered, the process will enter an infinite loop.
The RawCertParser does not advance the input stream when encountering unsupported cert (primary key) versions, resulting in an infinite loop.
> Add advisory for sequoia-openpgp DoS vulnerability.

- crates/zerovec-derive/RUSTSEC-0000-0000.md
- crates/zerovec/RUSTSEC-0000-0000.md
> `zerovec` vulnerability

- crates/gix-fs/RUSTSEC-0000-0000.md
- crates/gix-index/RUSTSEC-0000-0000.md
- crates/gix-worktree/RUSTSEC-0000-0000.md
This adds notices for the directory traversal vulnerability CVE-2024-35186 (https://github.com/Byron/gitoxide/security/advisories/GHSA-7w47-3wg8-547c), as discussed in https://github.com/Byron/gitoxide/discussions/1437 (cc @Byron). The gitoxide project is divided into a substantial number of crates, and multiple crates are affected, in the sense of containing code that needed to be changed to fix the vulnerability.
This PR proposes notices for only three of the seven crates listed as affected in https://github.com/Byron/gitoxide/security/advisories/GHSA-7w47-3wg8-547c. I believe these to be the primary affected crates, such that the other crates are mainly affected due to their use of the primary affected crates (though their code also had to be changed to fit the new API). This is in …
> Advisory for CVE-2024-35186 (traversal) in gix-fs, gix-index, gix-worktree

- crates/gix-index/RUSTSEC-0000-0000.md
- crates/gix-ref/RUSTSEC-0000-0000.md
- crates/gix-worktree/RUSTSEC-0000-0000.md
This adds notices for the [Windows device name handling](https://cwe.mitre.org/data/definitions/67.html) vulnerability CVE-2024-35197 (https://github.com/Byron/gitoxide/security/advisories/GHSA-49jc-r788-3fc9). This is a separate vulnerability from the one that #1996 is about—and I cannot open a single PR for both because they both have `RUSTSEC-0000-0000.md` files in two of the same locations until IDs are assigned—but it is likewise discussed in https://github.com/Byron/gitoxide/discussions/1437 (cc @Byron).
The advisory text (long description) is what I wrote for https://github.com/Byron/gitoxide/security/advisories/GHSA-49jc-r788-3fc9 and is essentially the same as in [the global advisory](https://github.com/advisories/GHSA-49jc-r788-3fc9). This is analogous to the situation in #1996, …
> Advisory for CVE-2024-35197 (device names) in gix-ref, gix-index, gix-worktree

- crates/zerovec-derive/RUSTSEC-2024-0346.md
We accidentally proposed the wrong version here in #1990
zerovec 0.10.4 and zerovec-derive 0.10.3 are patched.
> Fix patched zerovec-derive version

- CONTRIBUTING.md
Hi! 
We recently created a security policy page for crates.io at https://crates.io/policies/security (which, incidentally, links to rustsec-- if you'd like anything changed about that section, please send us a PR! ❤️ )
I'm on a mission to make sure as many crate authors as possible know, before there's a major security incident, that the Rust Foundation can help handling security problems that happen in the ecosystem, so in addition to adding a more general FAQ linking to the crates.io security policy, I've added a question that links to the ecosystem security help section directly.
I also noticed the Rust security policy wasn't linked in the FAQs here at all, so I added one for that too.
I'm open to changing the wording on any of these new FAQ entries, and if there are other places …
> Add some FAQ entries linking to security policies

- crates/gix-path/RUSTSEC-0000-0000.md
This adds a notice for the [uncontrolled search path element](https://cwe.mitre.org/data/definitions/427.html) vulnerability CVE-2024-40644 (https://github.com/Byron/gitoxide/security/advisories/GHSA-mgvv-9p9g-3jv4) in `gix-path`.
cc @Byron
> Advisory for CVE-2024-40644 (program files) in gix-path

- crates/gix-attributes/RUSTSEC-0000-0000.md
gix-attributes was found by @ssbr to be unsound, as reported in https://github.com/Byron/gitoxide/issues/1460. This adds an informational notice for that, as discussed in comments there (cc @Byron).
The text of the notice is taken from that issue (083656c), with slight modification (1a50df1).
It looks like the affected code, having been introduced in https://github.com/Byron/gitoxide/pull/400, was most likely present in all published versions of the crate prior to the fix in 0.22.3 (which was one of the bugs fixed in https://github.com/Byron/gitoxide/pull/1462). So I have not specified a minimum affected version.
> Unsoundness notice for gix-attributes (kstring integration)

- crates/cosmwasm-vm/RUSTSEC-2024-0361.md
We noticed a problem with our previous patch that leads to consensus problem because of a missing cache invalidation.
This bumps the versions in the advisory to the ones where this was fixed.
> Update versions for RUSTSEC-2024-0361

- crates/sqlx/RUSTSEC-0000-0000.md
https://github.com/launchbadge/sqlx/issues/3440
I'm not sure whether to open separate advisories for each affected `sqlx-*` crate. Ultimately, only `sqlx` is meant to be used directly.
> Advisory for sqlx <= 0.8.0

- crates/gitoxide-core/RUSTSEC-0000-0000.md
This adds a notice for CVE-2024-43785 (https://github.com/Byron/gitoxide/security/advisories/GHSA-88g2-r9rw-g55h) in `gitoxide-core`. See also https://github.com/Byron/gitoxide/issues/1534.
This low-risk [CWE-150](https://cwe.mitre.org/data/definitions/150.html) vulnerability is currently unpatched, but following coordination, it was decided to disclose it to the public with an advisory, as described in https://github.com/Byron/gitoxide/issues/1534.
Having a RUSTSEC advisory (as well as the existing GHSA) further serves the purpose of informing users, and should help avoid unnecessary skew between the information available in different advisory databases.
I will make sure to open another PR to update the RUSTSEC advisory when a fix, or other substantially changed information, is available …
> Advisory for CVE-2024-43785 (terminal sanitization) in gitoxide-core

- crates/sqlx/RUSTSEC-2024-0363.md
There's no instructions in https://github.com/rustsec/advisory-db/blob/main/CONTRIBUTING.md on what should be done to update an advisory, or if updating an advisory is allowed.
Also, in the process of addressing the issue, I was able to demonstrate a possible exploit for Postgres. Does this mean I should file a CVE as well?
> update resolution for RUSTSEC-2024-0363 (sqlx)

- crates/gix-path/RUSTSEC-2024-0367.md
This adds CVE-2024-45305 to `aliases` for RUSTSEC-2024-0367.
No CVE had been issued for that vulnerability when it was added to the RUSTSEC database in #2055, but it has been assigned since. (This CVE number can, if desired, be confirmed at https://github.com/Byron/gitoxide/security/advisories/GHSA-v26r-4c9c-h3j6, under "CVE ID" on the sidebar.)
Although I suspect an entry in the GitHub Advisory Database will be created, and as GHSA-v26r-4c9c-h3j6 is the repo-level GHSA that URL will likely be https://github.com/advisories/GHSA-v26r-4c9c-h3j6, I have refrained from adding that here because the page does not yet exist and I don't want to add inaccurate information. I'll open another PR if/when there is more to add.
cc @Byron
> Add CVE number for RUSTSEC-2024-0367 (config scopes)

- crates/olm-sys/RUSTSEC-0000-0000.md
I have been the almost sole maintainer of `olm-sys` for several years now. For about two years nothing has happened, as the successor effort `vodozemac` has taken off. However, a recent high-profile blog post has publicly disclosed crypto failures in `libolm`, the library that `olm-sys` wraps, and as a result the library has been [officially declared as deprecated](https://matrix.org/blog/2024/08/libolm-deprecation/).
The advisory in this PR is filled to reflect the unmaintained and simultaneously vulnerable status. Let me know if anything needs changing. Thanks.
> Add advisory for olm-sys (unmaintained, crypto failure)

- crates/gix-path/RUSTSEC-2024-0367.md
This adds a link to [the GitHub Advisory Database entry](https://github.com/advisories/GHSA-v26r-4c9c-h3j6) for [RUSTSEC-2024-0367](https://rustsec.org/advisories/RUSTSEC-2024-0367.html)/CVE-2024-45305/https://github.com/Byron/gitoxide/security/advisories/GHSA-v26r-4c9c-h3j6.
This entry was added to the GitHub Advisory Database since this RUSTSEC entry was created in #2055 and updated in #2061.
This also adds a reference to NVD entry, which has a useful summary and appears as a reference in the global GHSA's reference section, and fixes two bare URLs that are intended to be hyperlinks (and that are hyperlinks automatically in the global GHSA).
cc @Byron
> Add global GHSA reference for RUSTSEC-2024-0367 (config scopes)

- crates/gix-transport/RUSTSEC-2023-0064.md
[RUSTSEC-2023-0064](https://rustsec.org/advisories/RUSTSEC-2023-0064.html) was introduced in #1789 and does not have any major problems, but I noticed:
- A bare URL that seems intended to be linkified is not, because in the Markdown dialect used here. This is linkified automatically in https://github.com/advisories/GHSA-rrjw-j4m2-mf34.
- The wording in the acknowledgement is slightly cumbersome to read, since the object after "Thanks for" is usually an item or action that one is thankful to have received, rather than the person being thanked.
This does the minor fixes for both.
cc @Byron
> Make small readability improvements in RUSTSEC-2023-0064

- crates/phonenumber/RUSTSEC-0000-0000.md
[CVE-2024-39697/GHSA-mjw4-jj88-v687](https://github.com/whisperfish/rust-phonenumber/security/advisories/GHSA-mjw4-jj88-v687).
>  rust-phonenumber: panic-on-parse

- crates/proc-macro-error/RUSTSEC-0000-0000.md
> Add unmaintained advisory for proc-macro-error

- crates/gix-path/RUSTSEC-0000-0000.md
This adds a notice for CVE-2024-45405 (https://github.com/Byron/gitoxide/security/advisories/GHSA-m8rp-vv92-46c7) in `gix-path`.
When first opened, this PR didn't include the CVE number or link to the global GHSA, since those had not yet been created. But I have since edited this PR to include them.
(Although they involve the same crate and the same public functions, this `gix-path` vulnerability is a separate vulnerability from [RUSTSEC-2024-0367](https://rustsec.org/advisories/RUSTSEC-2024-0367.html)/CVE-2024-45305/https://github.com/Byron/gitoxide/security/advisories/GHSA-v26r-4c9c-h3j6.)
cc @Byron
> Advisory for CVE-2024-45405 (incomplete unescaping) in gix-path

- crates/ic-cdk/RUSTSEC-0000-0000.md
Creating a RUSTSEC advisory for [Github advisory](https://github.com/advisories/GHSA-rwq6-crjg-9cpw) due to a memory leak bug in `ic-cdk` crate
> Advisory for `GHSA-rwq6-crjg-9cpw` in `ic-cdk`

- crates/ic-cdk/RUSTSEC-2024-0372.md
> fix typo in latest patched version of `ic-cdk` : RUSTSEC-2024-0372

- crates/proc-macro-error/RUSTSEC-2024-0370.md
Adds [manyhow](https://crates.io/crates/manyhow) & [proc-macro2-diagnostics](https://github.com/SergioBenitez/proc-macro2-diagnostics), which are actively being used as alternatives
e.g. https://github.com/TeXitoi/structopt/pull/536 and https://github.com/nvksv/maybe-async-cfg/pull/9
> Add more alternatives to proc-macro-error

- crates/lexical-core/RUSTSEC-0000-0000.md
- crates/lexical-core/RUSTSEC-2024-0377.md
This adds in an additional security advisory for `lexical` and adds in the same for `lexical-core`.
Closes #2080 2081
> Add lexical-core advisory.

- crates/borsh/RUSTSEC-2023-0033.md
fix has been backported https://github.com/near/borsh-rs/pull/310
and published with 0.10.4 https://crates.io/crates/borsh/0.10.4
> Update RUSTSEC-2023-0033.md : add borsh v0.10.4 to list of patched versions

- crates/atty/RUSTSEC-0000-0000.md
Should be fairly uncontroversial as it explicitly meets the [unmaintained policy's](https://github.com/rustsec/advisory-db/blob/main/HOWTO_UNMAINTAINED.md#definition-of-an-unmaintained-crate) of explicit:
> Explicitly unmaintained: a crate's author has declared that they are no longer maintaining a particular crate.
The author of `atty` published [this README update](https://github.com/softprops/atty/commit/5bfdbe9e48c6ca6a4909e8d5b04f5e843a257e93#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5) making the maintenance status official:
>  This is crate is no longer maintained and users are encouraged to prefer the equivalant functionality of [std.io.IsTerminal]...
Since the previous maintainer was clear about alternatives, I made them more explicit in the advisory …
> Mark atty as officially unmaintained

- crates/tonic/RUSTSEC-2024-0376.md
Update the security advisory for tonic related https://github.com/rustsec/advisory-db/issues/2093, it was previously missing an additional unaffected field.
> Update RUSTSEC-2024-0376 affected versions

- crates/dbn/RUSTSEC-0000-0000.md
The `heap-buffer-overflow` is triggered in the `strlen()` function when handling the `c_chars_to_str` function in the dbn crate. This vulnerability occurs because the `CStr::from_ptr()` function in Rust assumes that the provided C string is null-terminated. However, there is no guarantee that the input chars array passed to the c_chars_to_str function is properly null-terminated.
If the chars array does not contain a null byte (\0), strlen() will continue to read beyond the bounds of the buffer in search of a null terminator. This results in an out-of-bounds memory read and can lead to a heap-buffer-overflow, potentially causing memory corruption or exposing sensitive information.
Related Git Issue : https://github.com/databento/dbn/issues/67#issue-2570042142
> Dbn heap buffer overflow

- crates/pyo3/RUSTSEC-0000-0000.md
PyO3 0.22 added bindings to work with Python weak references. Sadly a subset of this API was unsound as it allowed borrowing from weak references. These borrows could dangle at any time if the last strong reference was cleared.
> risk of use-after-free in PyO3 borrowing from weak refrences

- crates/may_queue/RUSTSEC-2020-0111.md
According to https://github.com/Xudong-Huang/may/issues/88, this has been fixed since a long time. Add the missing `patched`
> Add missing information about fixed versions

- crates/may_queue/RUSTSEC-2020-0111.md
According to https://github.com/Xudong-Huang/may/issues/88, this was fixed in 0.3.19, but that refers to the main "may" crate. The correct version for the "may_queue" sub crate is 0.1.8 (based on manual checking the bounds for the affected type on docs.rs)
My bad in the previous PR (#2105) for trusting the number written in the relevant bug report.
> Fix incorrect fixed version for may_queue

- crates/fast-float/RUSTSEC-0000-0000.md
[fast-float](https://github.com/aldanor/fast-float-rust) is currently unmaintained and contains undefined behavior in checking the length of the input https://github.com/aldanor/fast-float-rust/issues/28. Although a patch was implemented and [merged](https://github.com/aldanor/fast-float-rust/pull/29), no release was published and there has been no communication by the author in over 3 years.
In addition, there's also potential unsoundness, due to the use of many functions that are non-local safety [guarantees](https://github.com/aldanor/fast-float-rust/issues/37) marked as safe, assuming the necessary safety guarantees have been met by the caller. The simplest example is in [AsciiStr::first](https://github.com/aldanor/fast-float-rust/blob/83a49b8b5a530d8e950a6dbfdc11089d213b9ac9/src/commo …
> Add security advistory for fast-float.

- crates/pqcrypto-dilithium/RUSTSEC-0000-0000.md
- crates/pqcrypto-kyber/RUSTSEC-0000-0000.md
Since the official standards of these draft algorithms were released, they are replaced by crates that track the standards versions.
> Mark two pqcrypto- crates as unmaintained

- crates/hwloc/RUSTSEC-0000-0000.md
hwloc will no longer be maintained as declared by the developer. For more information, see: [hwloc-rs/issues](https://github.com/daschl/hwloc-rs/issues).
> Add unmaintained advisory for hwloc

- crates/bcc/RUSTSEC-0000-0000.md
bcc will no longer be maintained as declared by the developer. For more information, see: [rust-bcc/issues/200](https://github.com/rust-bpf/rust-bcc/issues/200).
> Add unmaintained advisory for bcc

- crates/instant/RUSTSEC-0000-0000.md
The author has stated in the project's README and [crates.io page](https://crates.io/crates/instant/0.1.13) that the crate is unmaintained, and links to `web-time` as an alternative.
See also https://github.com/sebcrozet/instant/issues/52.
CC @sebcrozet @daxpedda
> `instant` is unmaintained

- crates/cw0/RUSTSEC-0000-0000.md
I'm one of the CosmWasm maintainers.
> `cw0` unmaintained

- crates/strason/RUSTSEC-0000-0000.md
strason will no longer be maintained as declared by the developer. For more information, see: [strason/issues/4](https://github.com/apoelstra/strason/issues/4).
> Add unmaintained advisory for strason

- crates/mmap/RUSTSEC-0000-0000.md
Note: Did not ask the author about the status explicitly but the repository is archived for over two years so it should be a good indication
> Create `mmap` unmaintained advisory

- crates/chrono-english/RUSTSEC-0000-0000.md
Add advisory for `chrono-english`, which fails to build with the newest chrono versions.
https://github.com/stevedonovan/chrono-english/issues/29
The maintainer is unresponsive since three years, effectively making the repository unmaintained.
https://github.com/stevedonovan/chrono-english/issues/22
I propose [`interim`](https://github.com/conradludgate/interim) as a replacement, as its code is a lot cleaner and as it fixed several issues that still exist on chrono-english. The maintainer is active and notified me of this alternative when I ran into the compilation issues in one of my projects.
https://github.com/Nukesor/pueue/issues/534
> add: Unmaintained advisory for chrono-english

- crates/conrod/RUSTSEC-0000-0000.md
- crates/conrod_core/RUSTSEC-0000-0000.md
The `conrod` crate is explicitly unmaintained. Core functionality was transferred to `conrod_core` and backend functionality split across a number of separate crates such as `conrod_wgpu` around December 2018.
The entire conrod project became explicitly unmaintained in January 2022 when the developer stepped away from the project (https://github.com/PistonDevelopers/conrod/issues/1454).
> Add unmaintained advisory report for conrod and conrod_core

- crates/mimalloc/RUSTSEC-0000-0000.md
The [`mimalloc`](https://github.com/purpleprotocol/mimalloc_rust) crate had a soundness issue with returning unaligned memory a while back, and I think it deserves an advisory.
> Add unsound advisory for `mimalloc`

- crates/hashbrown/RUSTSEC-0000-0000.md
I wrote this as fixed in 0.16 due to that being the plan documented here: https://github.com/rust-lang/hashbrown/pull/570#issuecomment-2406017398
Until that PR is merged and 0.16 is released, this cannot be merged/must be edited to be described as unpatched.
> Add disclosure for hasbrown's borsh encoding

- crates/anstream/RUSTSEC-0000-0000.md
found here: https://github.com/rust-cli/anstyle/issues/156
> add information about unsoundness issue in anstream

- crates/linkme/RUSTSEC-0000-0000.md
https://github.com/dtolnay/linkme/issues/82
> `linkme` is unsound (coercion fools typecheck)

- crates/multi_mut/RUSTSEC-0000-0000.md
Fixes #1531 
It has no dependants so I think unmaintained can do it ?
Ping: https://github.com/rust-lang/rust/issues/39155
> Add unmaintained `multi_mut`

- crates/hashbrown/RUSTSEC-2024-0402.md
see https://github.com/rustsec/advisory-db/pull/2100#discussion_r1869452789
> RUSTSEC-2024-0402: Fix `unaffected` declaration

- crates/pyo3/RUSTSEC-0000-0000.md
See https://github.com/PyO3/pyo3/issues/4757 and https://github.com/PyO3/pyo3/releases/tag/v0.23.3
> report build corruption in PyO3 0.23

- crates/gtk-layer-shell-sys/RUSTSEC-0000-0000.md
- crates/gtk-layer-shell/RUSTSEC-0000-0000.md
I am the maintainer of the `gtk-layer-shell` and `gtk-layer-shell-sys` crates. The foundation of `gtk-layer-shell` are the `gtk` crates. It does not make sense to continue maintaining the crates if the foundation is unmaintained (https://github.com/rustsec/advisory-db/pull/2164), so I also stopped the development of them and marked them as unmaintained. Users should use GTK4 and the `gtk4-layer-shell` crate instead.
> Add advisories for unmaintained gtk-layer-shell GTK3 bindings

- crates/kvm-ioctls/RUSTSEC-0000-0000.md
An issue was identified in the `VmFd::create_device function`, leading to undefined behavior and miscompilations on rustc 1.82.0 and newer due to the function's violation of Rust's pointer safety rules.
The function downcasted a mutable reference to its `struct kvm_create_device` argument to an immutable pointer, and then proceeded to pass this pointer to a mutating system call. Rustc 1.82.0 and newer elides subsequent reads of this structure's fields, meaning code will not see the value written by the kernel into the `fd` member. Instead, the code will observe the value that this field was initialized to prior to calling `VmFd::create_device` (usually, 0).
The issue started in kvm-ioctls 0.1.0 and was fixed in 0.19.1 by correctly using
a mutable pointer.
> Add advisory for unsound problems in `kvm-ioctls`

- crates/glib/RUSTSEC-0000-0000.md
reported / fixed here: https://github.com/gtk-rs/gtk-rs-core/pull/1343
This PR was merged as https://github.com/gtk-rs/gtk-rs-core/commit/05dff0e , part of glib `>=0.20.0`, but it was not backported to earlier release branches (so it still affects any project that uses the latest version of the gtk3 bindings, which are [unmaintained](https://github.com/rustsec/advisory-db/pull/2164)).
> Report UB in glib::VariantStrIter::impl_get in glib < 0.20.0

- crates/gix-worktree-state/RUSTSEC-0000-0000.md
This adds a notice for CVE-2025-22620 (GHSA-fqmf-w4xh-33rh) in `gix-worktree-state`.
When a global GHSA is published, I can open another PR to add a reference to that.
I wasn't sure what to do here for affected operating systems. Only Unix-like operating systems are affected, which seems like something that could be valuable to express in the advisory metadata. But if I understand correctly, no value like `"unix"` is recognized for `affected.os`. Currently, I have not specified `affected.os` in the metadata. But would it be better to list all target operating systems that are Unix-like individually? (If so, I could use the technique in https://github.com/rustsec/advisory-db/pull/1911#discussion_r1512022858, which still works, to produce the list.)
cc @Byron
> Advisory for CVE-2025-22620 (chmod 777) in gix-worktree-state

- crates/gix-worktree-state/RUSTSEC-0000-0000.md
I clicked "merge" too quickly, oops
But it's okay since the advisory is not yet live
> Fix [affected.functions] in gix-worktree-state advisory

- crates/gix-worktree-state/RUSTSEC-0000-0000.md
This builds on #2193 by listing all Unix-like target operating systems as affected (since a category of OSes like "unix" cannot currently be represented in RUSTSEC advisory metadata).
The list was obtained by running the command given in https://github.com/rustsec/advisory-db/pull/1911#discussion_r1512022858.
The vulnerability is specific to Unix-like operating systems because:
- The vulnerable code runs only in the `unix` build configuration.
- 0777 permissions are meaningful on such systems and (due to containing 0002) allow any user account on the system to write.
Therefore, if there are any Unix-like systems where Unix-style filesystem permissions are not used, or that are *truly* single user (i.e. do not use multiple user accounts, not even for running daemons with limited …
> List Unix-like target OSes as affected by CVE-2025-22620

- crates/gix-attributes/RUSTSEC-2024-0359.md
This improves credit and adds a missing GHSA alias in [RUSTSEC-2024-0359](https://rustsec.org/advisories/RUSTSEC-2024-0359.html) (which is based on https://github.com/GitoxideLabs/gitoxide/issues/1460 and originally added in #2027). See commit messages for details, including rationale.
cc @Byron @ssbr
> Improve references in RUSTSEC-2024-0359

- crates/gix-worktree-state/RUSTSEC-2025-0001.md
Keeps causing issues on old cargo-audit versions, see https://github.com/rustsec/advisory-db/pull/2201#issuecomment-2606804520
> Remove listing of unix-likes from advisory

- crates/gix-worktree-state/RUSTSEC-2025-0001.md
[RUSTSEC-2025-0001](https://rustsec.org/advisories/RUSTSEC-2025-0001.html) (CVE-2025-22620) now has an entry in the GitHub Advisory Database. This adds that as a reference, also adds the NVD link as a reference, and adds GHSA-fqmf-w4xh-33rh as another alias (after the CVE number).
> Add global GHSA and references to RUSTSEC-2025-0001

- crates/columnar/RUSTSEC-2021-0087.md
This issue was closed with version 0.1.0:
https://github.com/frankmcsherry/columnar/issues/6
Commit:
https://github.com/frankmcsherry/columnar/commit/a9335e6f018731b5d434fb7703ec92e35d716ed0
Let me know if you need anything else. I work with the maintainer and will advise them to yank old versions of this crate. Thanks!
> Add patch version for RUSTSEC-2021-0087.md

- crates/ring/RUSTSEC-2025-0007.md
Remove unmaintained advisory RUSTSEC-2025-0007.
@ctz and the rustls maintainers now have access to the crates.io entry for ring.
> *ring* is maintained again

- crates/paste/RUSTSEC-0000-0000.md
> Create advisory for unmaintained `paste` crate

- crates/protobuf/RUSTSEC-0000-0000.md
This (public) advisory follows two emails sent on August 9 and October 3rd.
The crate is affected by the same vulnerability as described in https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-735f-pc8j-v9w8
> Protobuf DoS

- crates/protobuf/RUSTSEC-2024-0437.md
Update RUSTSEC-2024-0437 with the released patched version. The is on crates.io and per the [changelog] contains a fix for the recursion issue.
[changelog]: https://github.com/stepancheg/rust-protobuf/blob/330b78658ead005aebc7698a7af7cba185ad9702/CHANGELOG.md#372---2025-03-10-to-be-released
> List patched version for protobuf crate

- crates/humantime/RUSTSEC-0000-0000.md
Last crates.io release 2021-01-13 and no GitHub commits since 2021-12-28.
Question about maintenance status posted 2022-08-04 with no answer from maintainer: https://github.com/tailhook/humantime/issues/31
This crate has some [big dependents](https://crates.io/crates/humantime/reverse_dependencies) like [`clap`](https://crates.io/crates/clap) (with 20309 dependents) and [`env_logger`](https://crates.io/crates/env_logger) (with 8090 dependents).
Update 2025-03-10: `env_logger` 0.11.7 dropped `humantime` dependency in favor of `jiff`.
> Unmaintained advisory for humantime

- crates/pared/RUSTSEC-0000-0000.md
Affected versions of this crate didn't provide sufficient lifetime constraints to conversion
functions from `alloc::sync::Arc` and `alloc::rc::Rc`, which made it possible to create
projections of these reference counted pointers. Unlike the original reference counted pointers,
these projections could outlive original data's lifetimes.
This projected pointer could cause the original `Arc`'s or `Rc`'s `Drop::drop` to get called at
a point where the original data was no longer valid, leading to a potential use after free.
The affected functions were
- `pared::prc::Prc::from_rc`
- `pared::prc::Prc::project`
- `pared::prc::Prc::try_from_rc`
- `pared::sync::Parc::from_arc`
- `pared::sync::Parc::project`
- `pared::sync::Parc::try_from_arc`
This flaw was fixed in …
> Add advisory for use after free in `pared` <=0.3.0

- crates/web-push/RUSTSEC-0000-0000.md
Reported privately via e-mail, fixed via https://github.com/pimeys/rust-web-push/pull/68 and published in v0.10.3
> Report denial-of-service in web-push via malicious Web Push endpoint

- crates/trust-dns-proto/RUSTSEC-0000-0000.md
> Add notices for `trust-dns`

- crates/gix-features/RUSTSEC-0000-0000.md
This adds a notice for CVE-2025-31130 (GHSA-2frx-2596-x5r6) in `gix-features`.
Although `gix-features` is usually used as a "knob" for adjusting features across `gix-*` crates, as well as being used internally:
- The functionality replaced to fix the vulnerability was in `gix-features`.
- All vulnerable crates depend directly or indirectly on `gix-features`.
My understanding is that the usual practice for RUSTSEC advisories in such a situation is to have only an advisory for that one crate, as in https://github.com/rustsec/advisory-db/pull/1705#issuecomment-1575170900. So this adds a RUSTSEC notice only for `gix-features`. (The published repository-local GHSA, and forthcoming global GHSA, are not limited to one affected crate per advisory, and accordingly list more crates.)
 
As in some …
> Advisory for CVE-2025-31130 (weak SHA-1) in gix-features

- HOWTO_UNMAINTAINED.md
But, in the event a vulnerability is reported, we'll consider a crate unmaintainted after a shorter 60 days
> [RFC] Change our policy from 90 days to 270 days for unmaintained

- crates/tokio/RUSTSEC-0000-0000.md
Thanks to @abonander for reporting this issue. See https://github.com/tokio-rs/tokio/pull/7232 for more.
cc @carllerche
> Add advisory for Tokio broadcast channel issue

- crates/gix-features/RUSTSEC-2025-0021.md
Since it was added in #2268, [RUSTSEC-2025-0021](https://rustsec.org/advisories/RUSTSEC-2025-0021.html) (CVE-2025-31130) has an entry in the GitHub Advisory Database. As planned in #2268, this adds the link to that global GHSA, as well as to the National Vulnerability Database entry for the CVE.
Some additional information may end up being posted in the pull request or issue, in which case one or both of those may make sense to add as references, but I am not sure yet. If so, I can add those separately. But I didn't want to add these references as planned.
> Add references to RUSTSEC-2025-0021

- crates/tokio/RUSTSEC-2025-0023.md
We backported this fix to one more minor release series.
> Update patched version list for RUSTSEC-2025-0023

- crates/crossbeam-channel/RUSTSEC-0000-0000.md
https://github.com/crossbeam-rs/crossbeam/pull/1187
At the Tor Project we've assigned this [TROVE-2025-013](https://gitlab.torproject.org/tpo/core/team/-/wikis/NetworkTeam/TROVE). Our ticket https://gitlab.torproject.org/tpo/core/arti/-/issues/1942
Thanks for your attention.
> Add crossbeam-channel advisory re upstream MR #1187

- crates/wasmtime/RUSTSEC-0000-0000.0.md
- crates/wasmtime/RUSTSEC-0000-0000.1.md
- crates/wasmtime/RUSTSEC-0000-0000.10.md
- crates/wasmtime/RUSTSEC-0000-0000.11.md
- crates/wasmtime/RUSTSEC-0000-0000.12.md
- crates/wasmtime/RUSTSEC-0000-0000.13.md
- crates/wasmtime/RUSTSEC-0000-0000.14.md
- crates/wasmtime/RUSTSEC-0000-0000.15.md
- crates/wasmtime/RUSTSEC-0000-0000.2.md
- crates/wasmtime/RUSTSEC-0000-0000.3.md
- crates/wasmtime/RUSTSEC-0000-0000.4.md
- crates/wasmtime/RUSTSEC-0000-0000.5.md
- crates/wasmtime/RUSTSEC-0000-0000.6.md
- crates/wasmtime/RUSTSEC-0000-0000.7.md
- crates/wasmtime/RUSTSEC-0000-0000.8.md
- crates/wasmtime/RUSTSEC-0000-0000.md
[Wasmtime] recently got a [request] to have our security advisories
published on the RustSec database as well. We've got a few old
advisories on here but we haven't been keeping up-to-date with later
advisories. In lieu of automatic imports from GitHub to RustSec we
figured we'd in the interim manually fill in some fields.
In this PR I'm back-filling security advisories we've had in Wasmtime
into the RustSec database here. The oldest advisory here is 3 years old
and the goal is to have this serve as a template for importing future
advisories that Wasmtime gets. It's not expected for this to cause any
churn or undue warnings but instead is intended to bring RustSec
up-to-date with the advisories we have for this crate.
[Wasmtime]: https://crates.io/crates/wasmtime
[request]: …
> Import old Wasmtime security advisories 

- crates/cve-rs/RUSTSEC-0000-0000.md
- crates/totally-safe-transmute/RUSTSEC-0000-0000.md
- crates/totally-safe/RUSTSEC-0000-0000.md
We are using `cargo audit -D warnings` to avoid problematic dependencies.
To prevent anyone from using these crates in the dependency tree (accidentally?), I think it is meaningful to include them in advisories.
+ https://github.com/meithecatte/fake-static ([RUSTSEC-2020-0013](https://rustsec.org/advisories/RUSTSEC-2020-0013.html))
+ https://github.com/Speykious/cve-rs
+ https://github.com/ben0x539/totally-safe-transmute
+ https://github.com/viktorlott/totally-safe
Reverse dependencies
+ https://crates.io/crates/cve-rs/reverse_dependencies (0 dependents)
+ https://crates.io/crates/totally-safe-transmute/reverse_dependencies (1 dependent)
+ https://crates.io/crates/totally-safe/reverse_dependencies (0 dependents)
resolves #826
> Report unsoundness in `cve-rs`, `totally-safe-transmute` and `totally-safe`

- crates/tanton_engine/RUSTSEC-0000-0000.md
The original github repo seems like got deleted, not sure how to create the PR/issue at the upstream project
> tanton_engine: possible public unsound api

- crates/redox_uefi_std/RUSTSEC-0000-0000.md
I tried to report issue at https://gitlab.redox-os.org/redox-os/uefi however I have not heard back yet(request to join, no update yet).  I will create a issue there as soon as I get approval.
> potential OOB in redux_uefi_std

- crates/totally-safe-transmute/RUSTSEC-2025-0030.md
per #2221. Disclaimer: I'm the author of totally-safe-transmute.
People should know that totally-safe-transmute is a toy that's intentionally doing broken things, so that
a) they don't come after me
b) they know not to expect it to get patched
c) they question why someone is pulling toy code into their dependencies
> RUSTSEC-2025-0030: Indicate 'totally-safe-transmute' is a toy.

- crates/cve-rs/RUSTSEC-2025-0028.md
Per #2221, following the footsteps of #2309.
The description is now slightly better - the sarcastic description is funny, but describing the implementation as "memory safe" would be categorically incorrect (I think).
> RUSTSEC-2025-0028: Indicate 'cve-rs' is a joke

- crates/pingora-core/RUSTSEC-0000-0000.md
- crates/pingora/RUSTSEC-0000-0000.md
Pingora has a request smuggling and cache poisoning vulnerability affecting versions 0.5.0 and older, as documented here: https://blog.cloudflare.com/resolving-a-request-smuggling-vulnerability-in-pingora/
> pingora request smuggling and cache poisoning

- crates/slice-ring-buffer/RUSTSEC-0000-0000.md
Four new memory safety bugs have been discovered in `slice-ring-buffer` (a fork of the unmaintained `slice-deque` crate). 
All four bugs can lead to double-free violations, when only safe APIs are used. No patches for these vulnerabilities have been developed yet. 
We have contacted the maintainers of the crate (@LiquidityC), and they have granted us permission to request a security advisory for these issues.
> DFs in slice-ring-buffer

- crates/static_cell/RUSTSEC-0000-0000.md
I am not the owner of `static_cell`, but [the owner has manifested their intention not to file an advisory themself](https://github.com/embassy-rs/static-cell/issues/19#issuecomment-3073545476).
> static_cell: report unsoundness in `ConstStaticCell`

- crates/wasmtime/RUSTSEC-0000-0000.md
Adding an entry for wasmtime CVE-2025-53901 https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-fm79-3f68-h2fc
> wasmtime: `fd_renumber` panic

- crates/scratchpad/RUSTSEC-0000-0000.md
The public trait `scratchpad::Tracking` in the `scratchpad` crate is not marked as unsafe, even though its methods interact with unsafe code within the crate and influence the computation of raw pointers. As a result, even safe user-defined implementations of the trait—written without using any unsafe code—can still result in ill-formed raw pointers being dereferenced, leading to heap buffer overflows.
This issue was reported to the crate's GitHub repository ([issue #2](https://github.com/okready/scratchpad/issues/2)) 11 days ago, but there has been no response from the maintainers as of yet.
> Buffer overflow due to user-defined implementations of scratchpad::Tracking

- crates/xcb/RUSTSEC-0000-0000.md
Identifies a flaw in `xcb::Connection::connect_to_fd` and `xcb::Connection::connect_to_fd_with_extensions` which allows file descriptors to be used after close and/or double closed. An [issue was raised back in 2022](https://github.com/rust-x-bindings/rust-xcb/issues/167) to mark these functions as unsafe with no additional context. I discovered this unsoundness causing problems working on a different project and [reported my findings to xcb](https://github.com/rust-x-bindings/rust-xcb/issues/282).
It is unclear as to whether the project is maintained, though previously there was an issue raised as to its maintained status (see #653).
I did not put any categories or keywords. I just did not know what to put for them.
> `xcb` `connect_to_fd*` constructors unsound

- crates/arenavec/RUSTSEC-0000-0000.md
Multiple memory corruption vulnerabilities have been discovered in the crate `arenavec`. These include arbitrary memory access due to user-defined implementations of safe traits that return raw pointers, as well as heap buffer overflows and double free violations.
The issues were reported to the crate's GitHub repository ([issue #4](https://github.com/ibabushkin/arenavec/issues/4), [issue #5](https://github.com/ibabushkin/arenavec/issues/5), [issue #6](https://github.com/ibabushkin/arenavec/issues/6)) 12 days ago, but there has been no response from the maintainers as of yet.
> Multiple memory corruption vulnerabilities in arenavec

- crates/pingora-core/RUSTSEC-0000-0000.md
Adding advisory for pre 0.6.0 pingora-core versions specific to [MadeYouReset](https://nvd.nist.gov/vuln/detail/CVE-2025-8671) as a potential denial-of-service attack.
More details in the [GitHub advisory](https://github.com/cloudflare/pingora/security/advisories/GHSA-393w-9x6h-8gc7) and note in the [CF blog](https://blog.cloudflare.com/madeyoureset-an-http-2-vulnerability-thwarted-by-rapid-reset-mitigations/), as well as the [general CVE](https://nvd.nist.gov/vuln/detail/CVE-2025-8671).
> Add advisory for pingora-core MadeYouReset http/2 vuln
