README.md

Should indicate date of disclosure of the vulnerability

Add a "date" field to advisories

---

crates/cookie/RUSTSEC-0000-0000.toml

cc @SergioBenitez and @alexcrichton

Advisory: cookie denial of service

---

README.md

Addresses #27 using the approach suggested in https://github.com/RustSec/rustsec-client/pull/12

README.md: Add a 'maintained' shield from shields.io

---

Cargo.toml
src/lib.rs

Testing the alpha crate on the live repository prior to a final release

Update to 'rustsec' crate v0.7.0-alpha3

---

README.md

Add `id` field, cleanup comments, mandatory/optional notes, and ordering

README.md: Fixups for TOML template

---

crates/openssl/RUSTSEC-0000-0000.toml
crates/openssl/RUSTSEC-2016-0001.toml

Advisory: rust-openssl hostname verification

---

crates/hyper/RUSTSEC-0000-0000.toml
crates/hyper/RUSTSEC-2016-0002.toml

Advisory: hyper HTTPS MitM due to lack of hostname verification

---

CONTRIBUTING.md
README.md

* `CONTRIBUTING.md`: Fix link to GitHub issues
* `README.md`: Move title/description up in advisory example

Documentation cleanups

---

README.md
crates/hyper/RUSTSEC-2016-0002.toml

Documents the use of the `affected_platforms` attribute in advisories, and adds it to a relevant advisory.

Affected Platforms

---

CONTRIBUTING.md

CONTRIBUTING.md: Fix link to template

---

README.md

Add new affected functions attribute to template

---

crates/libp2p-core/RUSTSEC-0000-0000.toml

cc @kirushik, our infosec guy.

Add libp2p ed25519 signature verification failure

---

crates/libp2p-core/RUSTSEC-2019-0004.toml

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9b307213710a1332e2cd30a767ebdbf2

[libp2p-core] fix patched versions

---

crates/protobuf/RUSTSEC-2019-0003.toml

Fixes https://github.com/RustSec/cargo-audit/issues/76.

[protobuf] fix patched versions

---

crates/pancurses/RUSTSEC-0000-0000.toml

Add advisory for pancurses

---

crates/ncurses/RUSTSEC-0000-0000.toml

Add advisory for ncurses

---

crates/asn1_der/RUSTSEC-0000-0000.toml

Filing issue for [DOS-vulnerability](https://github.com/KizzyCode/asn1_der/issues/1) in `asn1_der`

Filing issue for `asn1_der`

---

CONTRIBUTING.md

This seems like the best advice we can give for now

CONTRIBUTING.md: Recommend yanking affected versions (closes #74)

---

crates/libflate/RUSTSEC-0000-0000.toml

https://github.com/sile/libflate/issues/35

Add advisory for libflate

---

crates/portaudio-rs/RUSTSEC-2019-0022.toml

RUSTSEC-2019-0022: Fix date

---

.travis.yml

https://github.com/RustSec/rustsec-admin

.travis.yml: Lint with the `rustsec-admin` crate

---

crates/hyper/RUSTSEC-2017-0002.toml

Fix escapes in hyper advisory

---

.github/workflows/validate.yml
README.md

README.md: Update build badge

---

crates/chacha20/RUSTSEC-0000-0000.toml
crates/chacha20/RUSTSEC-2019-0029.toml

Upstream issue: https://github.com/RustCrypto/stream-ciphers/pull/64

chacha20: Add counter overflow advisory

---

crates/streebog/RUSTSEC-0000-0000.toml

Add an advisory for streebog bug

---

crates/spin/RUSTSEC-2019-0031.toml

Unmaintained per its author:
https://github.com/mvdnes/spin-rs/commit/7516c80

Assign RUSTSEC-2019-0031 to spin

---

crates/prost/RUSTSEC-0000-0000.toml

See https://github.com/danburkert/prost/issues/267 and https://github.com/danburkert/prost/releases/tag/v0.6.1.
CC @tarcieri @danburkert

Add advisory for prost stack overflow

---

crates/bitvec/RUSTSEC-0000-0000.toml

Report memory management error in `bitvec`

---

crates/tiberius/RUSTSEC-0000-0000.toml

See: https://github.com/RustSec/advisory-db/issues/261

Add tiberius unmaintained advisory

---

crates/fake-static/RUSTSEC-0000-0000.toml

Closes https://github.com/RustSec/advisory-db/issues/207

Add advisory for fake-static

---

crates/plutonium/RUSTSEC-2020-0011.toml

See discussion on https://github.com/RustSec/advisory-db/issues/275#issuecomment-619241211

RUSTSEC-2020-0011: mark as informational

---

CONTRIBUTING.md

I took a go at this, but I am not sure if this is the right place.

CONTRIBUTING: mention soundness issues

---

crates/tokio-rustls/RUSTSEC-0000-0000.toml

Add tokio-rustls DoS advisory

---

crates/linked-hash-map/RUSTSEC-0000-0000.toml

Fixes https://github.com/RustSec/advisory-db/issues/298

add linked-hash-map unsoundness

---

.github/workflows/assign-ids.yml

a) Won't work until there's a release on rustsec-admin
b) Untested, but I feel like there's a decent chance it works!

Fixes #334 -- give the assignment PRs a useful commit message

---

crates/rand_core/RUSTSEC-2019-0035.toml

Add alias for GHSA

---

CONTRIBUTING.md

Add some minimal guideline about GHSA

---

crates/rand_core/RUSTSEC-2019-0035.toml

http://cve.mitre.org/cgi-bin/cvename.cgi?name=2020-25576

Added CVE number

---

crates/http/RUSTSEC-2019-0033.toml

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25574

added CVE number CVE-2020-25574

---

crates/sized-chunks/RUSTSEC-2020-0041.toml

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25791
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25792
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25793
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25794
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25795
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25796

added CVE numbers

---

crates/actix-codec/RUSTSEC-0000-0000.toml

Advisory for unsound pinning in actix-codec

---

crates/stdweb/RUSTSEC-0000-0000.md

Add unmaintained crate advisory for stdweb

---

.github/workflows/assign-ids.yml
.github/workflows/validate.yml

Trying to fix an `assign-id` bug

CI: bump rustsec-admin to v0.3.0-pre3

---

.github/workflows/assign-ids.yml
.github/workflows/validate.yml

Release notes: https://github.com/RustSec/rustsec-admin/pull/86

Bump `rustsec-admin` to v0.3.0

---

crates/directories/RUSTSEC-2020-0054.md

fix: s/directoriess/directories

---

crates/futures-intrusive/RUSTSEC-2020-0072.md

See https://github.com/Matthias247/futures-intrusive/issues/53#issuecomment-730881991

Add patched version for futures-intrusive's RUSTSEC-2020-0072

---

CONTRIBUTING.md
README.md

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Correct typo and URL

---

crates/branca/RUSTSEC-0000-0000.md

A couple of days ago, I informed the maintainer of this crate  about this security issue. A fix has now been released.

Add advisory for branca

---

crates/safe_app/RUSTSEC-0000-0000.md
crates/safe_authenticator/RUSTSEC-0000-0000.md
crates/safe_core/RUSTSEC-0000-0000.md
crates/safe_vault/RUSTSEC-0000-0000.md

safe_core --> sn_client
safe_app --> sn_client
safe_authenticator --> sn_client
safe_vault --> sn_node

Renamed crates

---

crates/arc-swap/RUSTSEC-0000-0000.md

Please tell me if I should add some more info or if the wording is unclear or anything. Thanks.

Dangling reference in arc_swap::access::Map

---

crates/async-h1/RUSTSEC-0000-0000.md

Hi there and thanks for running this database! Here's my first attempt at filing an advisory, please let me know if I should make any changes. I'm not certain on a few fields of the CVSS so I didn't fill that in at all.

File an http request smuggling advisory for async-h1 < 2.3.0

---

crates/difference/RUSTSEC-0000-0000.md

Create advisory for difference

---

.github/workflows/publish-web.yml

Automatically rebuilds the contents of the `gh-pages` branch on merge

Add "Publish Web" GitHub Action

---

crates/fake-static/RUSTSEC-2020-0013.md

Typo in RUSTSEC-2020-0013

---

crates/http/RUSTSEC-2019-0034.md

Fix typo in http CVE number

---

crates/conquer-once/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/oliver-giersch/conquer-once/issues/3

[patched] Add advisory for data race in conquer-once

---

crates/late-static/RUSTSEC-0000-0000.md

Original issue report: https://github.com/Richard-W/late-static/issues/1

late-static: LateStatic

---

crates/abi_stable/RUSTSEC-0000-0000.md

Original issue report: https://github.com/rodrimati1992/abi_stable_crates/issues/44

abi_stable: Update unsound DrainFilter and RString::retain

---

crates/hashconsing/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/AdrienChampion/hashconsing/issues/1
Fix commit: https://github.com/AdrienChampion/hashconsing/commit/4b2903c9f91e0d81732174def757ac23a218e07a

Add advisory for data race in hashconsing

---

crates/may_queue/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/Xudong-Huang/may/issues/88

Add advisory for data race in may_queue

---

crates/rand_core/RUSTSEC-2019-0035.md

Update RUSTSEC-2019-0035.md with more patched versions

---

crates/difference/RUSTSEC-2020-0095.md

Adds similar as suggestion to the difference.rs unmaintained warning. Follow up to #534

Add similar suggestion to difference.rs

---

crates/raw-cpuid/RUSTSEC-0000-0000.md

Draft. To be updated soon with solutions.

raw-cpuid: Multiple soundness issues

---

crates/tiny_future/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/KizzyCode/tiny_future/issues/1

[patched] Add advisory for data race in tiny_future

---

.github/workflows/assign-ids.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

Includes support for `thread-safety` category
cc @Qwaz

Bump `rustsec-admin` to v0.3.4

---

crates/convec/RUSTSEC-0000-0000.md

Original issue report: https://github.com/krl/convec/issues/2

convec::ConVec<T> unconditionally implements Send/Sync

---

crates/rcu_cell/RUSTSEC-0000-0000.md

Original issue report: https://github.com/Xudong-Huang/rcu_cell/issues/3

rcu_cell: Send/Sync bound needed on T  for Send/Sync impl of RcuCell<T>

---

crates/toolshed/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/ratel-rust/toolshed/issues/12
Has been open for 2 months with no response.

Add advisory for data race in toolshed

---

crates/dces/RUSTSEC-0000-0000.md

Upstream issue: https://gitlab.redox-os.org/redox-os/dces-rust/-/issues/8
Been open for a month with no response from the author.

Add advisory for data race in dces

---

.github/workflows/publish-web.yml

Have `publish-web` GH Action auto-publish changes

---

crates/comrak/RUSTSEC-0000-0000.md

Add an advisory for comrak XSS. https://github.com/kivikakk/comrak/releases/tag/0.9.1

Add advisory on comrak XSS

---

crates/heapless/RUSTSEC-2020-0145.md

Heapless soundness fix since 0.6.1

---

crates/nano_arena/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/bennetthardwick/nano-arena/issues/1

[patched] Add advisory for aliasing violation in nano_arena

---

crates/stack_dst/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/thepowersgang/stack_dst-rs/issues/5

[patched] Add advisory for double-free in stack_dst

---

crates/fltk/RUSTSEC-0000-0000.md

Hello
This is a PR with known issues with fltk. Please feel free to improve.

add known issues with fltk

---

.github/workflows/assign-ids.yml
.github/workflows/mirror-main-to-master.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml
README.md

Rename `master` branch to `main`

---

.github/workflows/mirror-main-to-master.yml

Not sure quote what the problem is, but it's erroring:
https://github.com/RustSec/advisory-db/runs/2051631730?check_suite_focus=true

Have master-to-main mirror force push

---

crates/bam/RUSTSEC-2021-0027.md
crates/byte_struct/RUSTSEC-2021-0032.md
crates/diesel/RUSTSEC-2021-0037.md
crates/fltk/RUSTSEC-2021-0038.md
crates/internment/RUSTSEC-2021-0036.md
crates/nano_arena/RUSTSEC-2021-0031.md
crates/quinn/RUSTSEC-2021-0035.md
crates/scratchpad/RUSTSEC-2021-0030.md
crates/stack_dst/RUSTSEC-2021-0033.md
crates/toodee/RUSTSEC-2021-0028.md
crates/truetype/RUSTSEC-2021-0029.md

Update CVE numbers

---

crates/cgc/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/playXE/cgc/issues/5
Been open now for around 4 months without a response from the author.

Add advisory for multiple issues in cgc

---

crates/telemetry/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/Yoric/telemetry.rs/issues/45
Been open now for a month and a half with no response from the author.

Report uninitialized memory drop on panic in telemetry

---

crates/slice-deque/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/gnzlbg/slice_deque/issues/90
Been open for longer than a month with no response from the author.

Report double-free in slice-deque

---

crates/appendix/RUSTSEC-0000-0000.md

Upstream issues:
* https://github.com/krl/appendix/issues/6
* https://github.com/krl/appendix/issues/7
They've been open now for 5 months with no response.

Report data race and memory safety issue in appendix

---

crates/through/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/gretchenfrage/through/issues/1
Been open for over a month without response from the author.

Report double-free in through crate

---

crates/disrustor/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/sklose/disrustor/issues/1
Been open for 4 months without a response from the author.

Report aliasing violation and data race in disrustor

---

crates/generator/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/Xudong-Huang/generator-rs/issues/27

[patched] Add advisory for data race in generator

---

crates/max7301/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/edarc/max7301/issues/1
Been open now for 4 months without any response from the crate author.

Add advisory for data race in max7301

---

crates/id-map/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/andrewhickman/id-map/issues/3
Open for a month without any response from the crate author.

Add advisory for double-free issues in id-map

---

crates/rkyv/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/djkoloski/rkyv/issues/113

Report rkyv vulnerability (issue rkyv#113)

---

.github/workflows/assign-ids.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

This includes improvements to the web site generator:
https://github.com/RustSec/rustsec-admin/pull/133

Bump `rustsec-admin` to v0.4.1

---

.github/workflows/assign-ids.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

This includes an atom feed generator:
https://github.com/RustSec/rustsec-admin/pull/142

Bump `rustsec-admin` to v0.4.2

---

crates/comrak/RUSTSEC-0000-0000.md

Thanks to Sam Sanoop (snoopysecurity) for reporting.

Add advisory for another comrak XSS

---

.github/workflows/assign-ids.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

Changelog: https://github.com/RustSec/rustsec/pull/389

Bump `rustsec-admin` to v0.5.0

---

.github/workflows/assign-ids.yml
.github/workflows/export-osv.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

Includes changes from https://github.com/RustSec/rustsec/pull/393

Bump `rustsec-admin` to v0.5.1

---

rust/std/CVE-2017-20004.md
rust/std/CVE-2018-25008.md
rust/std/CVE-2019-1010299.md
rust/std/CVE-2020-36323.md
rust/std/CVE-2021-31162.md

Update five std CVEs

---

crates/prost-types/RUSTSEC-0000-0000.md

Ref https://github.com/tokio-rs/prost/issues/438
cc @Shnatsel

prost-types: Timestamp conversion overflow

---

crates/prost-types/RUSTSEC-2021-0073.md

Hotfix #957 until we figure out what to do with it

---

rust/std/CVE-2021-29922.md

Added CVE-2021-29922 like described [here](https://sick.codes/sick-2021-015).
@sickcodes Are you okay with reusing your explanation?

added CVE-2021-29922

---

crates/hyper/RUSTSEC-0000-0000.md

Add advisory for hyper Content-Length header parsing

---

crates/hyper/RUSTSEC-0000-0000.md

Add advisory for hyper Transfer-Encoding header parsing

---

rust/std/CVE-2021-29922.md

I don't know why it shows older commits from the previous PR (#971) but it should be fine.

added specific affected functions to CVE-2021-29922

---

crates/sha2/RUSTSEC-0000-0000.md

Add sha2 v0.9.7 AVX2 bug

---

crates/zeroize_derive/RUSTSEC-0000-0000.md

See https://github.com/iqlusioninc/crates/issues/876.
I would appreciate anybody confirming this.

`#[zeroize(drop)]` not working for `enum`s

---

crates/arrow/RUSTSEC-0000-0000.md

Similar to  #1057
Upstream issue: https://github.com/apache/arrow-rs/issues/774

arrow DecimalArray advisory

---

crates/shamir/RUSTSEC-0000-0000.md

Closes https://github.com/rustsec/advisory-db/issues/235

Turn the issue about shamir into an advisory

---

crates/rental/RUSTSEC-0000-0000.md

Closes https://github.com/rustsec/advisory-db/issues/305

Rental is unmaintained

---

crates/pty/RUSTSEC-0000-0000.md

Add unmaintained advisory for pty

---

crates/fruity/RUSTSEC-2021-0123.md

This issue has been resolved: https://github.com/nvzqz/fruity/issues/14#issuecomment-1092732913

Add patch version for fruity

---

crates/openssl-src/RUSTSEC-2022-0025.md
crates/openssl-src/RUSTSEC-2022-0026.md
crates/openssl-src/RUSTSEC-2022-0027.md

Reverts rustsec/advisory-db#1263, see that thread for discussion
cc @pinkforest @amousset

Revert "Fix RUSTSEC-2022-0025,26,27 openssl-src for the 111 stream"

---

crates/websocket/RUSTSEC-2022-0035.md

fix typo in advisory date

---

crates/r2d2-odbc/RUSTSEC-0000-0000.md

Add unmaintained advisory for r2d2-odbc

---

crates/async-graphql/RUSTSEC-0000-0000.md
crates/juniper/RUSTSEC-0000-0000.md

Add advisories for async-graphql/juniper denial of service issues

---

crates/odbc/RUSTSEC-0000-0000.md

Add unmaintained advisory for odbc

---

MAINTAINERS_GUIDE.md

Motivated by https://github.com/rustsec/advisory-db/pull/1176#issuecomment-1200317335

Explicitly mention soundness in the maintainers guide

---

crates/crossbeam-utils/RUSTSEC-0000-0000.md

Add Crossbeam AtomicCell<*64> Soundness #1203

---

crates/rustdecimal/RUSTSEC-0000-0000.md

Following #1234 
I did not want messing with rebasing the old branch so replacing the PR
Thanks @Shnatsel

Add Malicious crate rustdecimal

---

MAINTAINERS_GUIDE.md

Adds guide to use labels for triaging PRs

Add Triage Labels Guide

---

.github/workflows/assign-ids.yml

Addresses https://github.com/rustsec/rustsec/issues/630

Fix "ghost" ID assignment PRs

---

.github/workflows/publish-web.yml

Required for the changes from https://github.com/rustsec/rustsec/pull/633 to propagate

bump rustsec-admin in publish-web workflow

---

crates/sodiumoxide/RUSTSEC-0000-0000.md

Closes #1090 
We will need to tune the alternatives and put some more wording around probably

Add sodiumoxide unmaintained

---

README.md

Document the Markdown in README example

---

README.md

Document `references` field

---

crates/xml-rs/RUSTSEC-0000-0000.md

Closes https://github.com/rustsec/advisory-db/issues/1121

Add unmaintained ` xml-rs` 

---

README.md

Document `withdrawn`

---

README.md

Document empty `versions` field use

---

crates/ansi_term/RUSTSEC-0000-0000.md

Add unmaintained `ansi_term`

---

.github/workflows/publish-web.yml

Adds a search field and a mention of GHSA to rustsec.org

bump rustsec-admin to 0.8.2 in web workflow

---

crates/rusttype/RUSTSEC-0000-0000.md

Add unmaintained `rusttype`

---

crates/ansi_term/RUSTSEC-2021-0139.md

Add `owo-colors` as `ansi_term` alternative

---

crates/wee_alloc/RUSTSEC-0000-0000.md

Add unmaintained `wee_alloc`

---

crates/kamadak-exif/RUSTSEC-0000-0000.md

Add `kamadak-exif` DoS

---

crates/traitobject/RUSTSEC-0000-0000.md

Fixes #1088 
Mind reviewing @ranweiler & @philip-peterson
traitobject has 8,110,280 total downloads ~7k a day..
Cheers

Add unmaintained `traitobject`

---

crates/matrix-sdk/RUSTSEC-0000-0000.md

Upstream issue: https://github.com/matrix-org/matrix-rust-sdk/issues/1110

Add advisory for logging of access tokens in matrix-sdk

---

crates/conduit-hyper/RUSTSEC-0000-0000.md

Add conduit-hyper CVE-2022-39294

---

.github/workflows/assign-ids.yml
.github/workflows/export-osv.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

- Sort advisories by publication date in the atom feed and on the website
- Make home page style more responsive

Update to cargo-admin 0.8.4

---

crates/tokio/RUSTSEC-0000-0000.md

Add `tokio` CVE-2023-22466

---

.github/workflows/assign-ids.yml
.github/workflows/export-osv.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

- Escape search term to prevent reflected XSS ([#787])
- Add a CI check to ensure the website builds correctly ([#787])
- Update `comrak` to v0.15.0 ([#760])
[#787]: https://github.com/rustsec/rustsec/pull/787
[#760]: https://github.com/rustsec/rustsec/pull/760

Update to rustsec-admin 0.8.5

---

crates/wasmtime/RUSTSEC-0000-0000.md

Re: https://github.com/rustsec/advisory-db/issues/1483
https://nvd.nist.gov/vuln/detail/CVE-2022-39393

Add `wasmtime` CVE-2022-39393

---

crates/elf_rs/RUSTSEC-0000-0000.md

This adds an advisory for the elf_rs crate.

Add advisory for elf_rs crate

---

crates/parity-util-mem/RUSTSEC-0000-0000.md

Add parity-util-mem unmaintained

---

crates/libgit2-sys/RUSTSEC-0000-0000.md

https://github.com/rust-lang/git2-rs/security/advisories/GHSA-m4ch-rfv5-x5g3

Add advisory for libgit2-sys

---

crates/markdown/RUSTSEC-2022-0044.md

Remove unmaintained status of `markdown`

---

crates/libp2p/RUSTSEC-0000-0000.md

Add `libp2p` DoS

---

crates/slack-morphism/RUSTSEC-0000-0000.md

Add `slack-morphism` CVE-2022-31162

---

crates/slack-morphism/RUSTSEC-0000-0000.md

Fixes #1488 together with #1556

Add `slack-morphism` CVE-2022-39292

---

crates/bzip2/RUSTSEC-0000-0000.md

Add `bzip2` DoS

---

crates/bzip2/RUSTSEC-2023-0004.md

Changed publish date from September 1st to January 9th

Changed Publish Date Of `RUSTSEC-2023-0004`  from September 1st  (future) to January 9th

---

README.md

Drop mentions of `iwantacve.org`

---

crates/cortex-m-rt/RUSTSEC-0000-0000.md

See <https://github.com/rust-embedded/cortex-m/discussions/469>

Add soundness advisory for cortex-m-rt

---

crates/ascii/RUSTSEC-0000-0000.md

related: https://github.com/tomprogrammer/rust-ascii/issues/64

Add ascii advisory

---

crates/remove_dir_all/RUSTSEC-0000-0000.md

reported in GHSA-mc8h-8q98-g5hr ( https://github.com/advisories/GHSA-mc8h-8q98-g5hr )

remove_dir_all have TOCTOU race condition

---

crates/kuchiki/RUSTSEC-0000-0000.md

Add unmaintained advisory kuchiki

---

crates/mach/RUSTSEC-0000-0000.md

Add unmaintained advisory for mach

---

crates/boxfnonce/RUSTSEC-0000-0000.md

Add boxfnonce unmaintained advisory

---

crates/encoding/RUSTSEC-0000-0000.md

Add unmaintained advisory encoding

---

.github/workflows/assign-ids.yml
.github/workflows/export-osv.yml
.github/workflows/publish-web.yml
.github/workflows/validate.yml

Fix CI always using an outdated version of rustsec-admin

---

crates/borsh/RUSTSEC-2023-0033.md

Sorry, I should have let the spell checker run before merging :)

Fix typos in RUSTSEC-2023-0033

---

crates/xsalsa20poly1305/RUSTSEC-0000-0000.md

See https://github.com/RustCrypto/AEADs/pull/525

xsalsa20poly1305 is unmaintained

---

crates/memoffset/RUSTSEC-0000-0000.md

Prior discussions:
* https://github.com/Gilnaa/memoffset/issues/9
* https://github.com/Gilnaa/memoffset/issues/24

Add advisory to `memoffset`

---

crates/lmdb-rs/RUSTSEC-0000-0000.md

https://github.com/vhbit/lmdb-rs/issues/67

report unsoundness of lmdb-rs

---

crates/intaglio/RUSTSEC-0000-0000.md

See:
- https://github.com/artichoke/intaglio/issues/235
- https://github.com/artichoke/intaglio/pull/236
- https://github.com/artichoke/intaglio/releases/tag/v1.9.0

Add advisory for unsoundness in intaglio symbol interners

---

crates/tui/RUSTSEC-0000-0000.md

Add unmaintained `tui` advisory

---

crates/ed25519-dalek/RUSTSEC-0000-0000.md

Add Double Public Key Signing Function Oracle Attack on `ed25519-dalek`

---

crates/quinn-proto/RUSTSEC-0000-0000.md

Add advisory for quinn-proto DoS issue

---

crates/openssl/RUSTSEC-2023-0072.md

Make the interior mutability issue more clear

Update the wording of RUSTSEC-2023-0072

---

crates/h2/RUSTSEC-0000-0000.md

Add Reset Flood advisory for older versions of h2.

h2: Reset Flood vulnerability may lead to resource exhaustion and DOS

---

crates/shlex/RUSTSEC-0000-0000.md

[GHSA-r7qv-8r2h-pg27](https://github.com/comex/rust-shlex/security/advisories/GHSA-r7qv-8r2h-pg27)

shlex: multiple issues involving quote API

---

README.md

README.md: update maintained image

---

crates/trillium-client/RUSTSEC-2024-0008.md
crates/trillium-http/RUSTSEC-2024-0009.md

Following up on #1864 now that GitHub has assigned a CVE

Add CVE alias for RUSTSEC-2024-000{8,9}

---

.github/workflows/sync-ids.yml

Fix commit message for ID sync action

---

crates/transpose/RUSTSEC-0000-0000.md

Add advisory for buffer overflow in transpose

---

crates/transpose/RUSTSEC-2023-0080.md

https://github.com/ejmahler/transpose/issues/11#issuecomment-1953451202

Add patched version for `transpose` advisory

---

crates/phonenumber/RUSTSEC-0000-0000.md

https://github.com/whisperfish/rust-phonenumber/security/advisories/GHSA-whhr-7f2w-qqj2

rust-phonenumber: panic-on-parse

---

crates/blurhash/RUSTSEC-0000-0000.md

https://github.com/whisperfish/blurhash-rs/security/advisories/GHSA-cxvp-82cq-57h2

blurhash-rs panic-on-parse

---

crates/hpack/RUSTSEC-0000-0000.md

Add security advisory for unmaintained hpack crate

---

crates/puccinier/RUSTSEC-2024-0331.md

As per https://github.com/catppuccin/toolbox/issues/155

Add an unmaintained crate advisory for puccinier

---

crates/h2/RUSTSEC-0000-0000.md

h2: continuation flood cause degradation of service

---

crates/gix-transport/RUSTSEC-0000-0000.md

Importing https://github.com/Byron/gitoxide/security/advisories/GHSA-98p4-xjmm-8mfh with the maintainer's permission

Advisory for gix-transport

---

crates/tor-circmgr/RUSTSEC-0000-0000.md

This is the 2nd of two advisories, for which we have applied for two CVEs.  The other one is MR #1957

Add advisory for tor-circmgr TROVE-2024-004

---

crates/cosmwasm-vm/RUSTSEC-0000-0000.md

Add cosmwasm-vm advisory CWA-2024-004

---

crates/cosmwasm-vm/RUSTSEC-0000-0000.md

Maintainer here. This one is a bit older, but we never created a RustSec advisory. Since this is a pretty big vulnerability, I'd like to do that now.

Add cosmwasm-vm advisory CWA-2023-004

---

crates/gix-path/RUSTSEC-0000-0000.md

This adds a notice for GHSA-v26r-4c9c-h3j6 in `gix-path`.
cc @Byron

Advisory for GHSA-v26r-4c9c-h3j6 (config scopes) in gix-path

---

crates/quinn-proto/RUSTSEC-0000-0000.md

[GHSA-vr26-jcq5-fjj8](https://github.com/quinn-rs/quinn/security/advisories/GHSA-vr26-jcq5-fjj8)

Add advisory for quinn-proto denial of service

---

crates/lexical/RUSTSEC-2023-0055.md

Announcement: https://redd.it/1fgyopo

Lexical is maintained again, unsoundness is fixed

---

crates/tonic/RUSTSEC-0000-0000.md

I give permission for you to use the advisory text under CC0-1.0.

Add advisory for CVE-2024-47609 in tonic

---

crates/opentelemetry_api/RUSTSEC-0000-0000.md

Closes https://github.com/rustsec/advisory-db/issues/1994

opentelemetry_api merged into opentelemetry crate

---

crates/openslide/RUSTSEC-0000-0000.md

Closes https://github.com/rustsec/advisory-db/issues/1937

openslide is unmaintained

---

crates/minitrace/RUSTSEC-0000-0000.md

For more information: https://github.com/tikv/minitrace-rust/issues/229

minitrace is unmaintained

---

crates/get-size-derive/RUSTSEC-0000-0000.md
crates/get-size/RUSTSEC-0000-0000.md

Add unmaintained advisories

---

crates/ring/RUSTSEC-0000-0000.md

See https://github.com/rustsec/advisory-db/issues/2227

Add unmaintained advisory for *ring*

---

crates/backoff/RUSTSEC-0000-0000.md

List `backoff` as unmaintained

---

crates/pyo3/RUSTSEC-0000-0000.md

See https://github.com/PyO3/pyo3/issues/5005

report memory exposure in PyO3's `PyString::from_object`

---

crates/markdown/RUSTSEC-2022-0044.md

Withdraw RUSTSEC-2022-0044

---

crates/registry/RUSTSEC-0000-0000.md

Advisory for unmaintained registry

---

crates/atomic-polyfill/RUSTSEC-0000-0000.md

Advisory for unmaintained atomic-polyfill

---

.github/workflows/assign-ids.yml
.github/workflows/export-osv.yml
.github/workflows/publish-web.yml
.github/workflows/sync-ids.yml
.github/workflows/validate.yml

As suggested by @Shnatsel in https://github.com/rustsec/rustsec/pull/1356#issuecomment-2838409170.

Install rustsec-admin from git

---

crates/fast_id_map/RUSTSEC-0000-0000.md

@Bruce0203 Hi author of this crate, could you please verify that this crate is unmaintained? If the crate is still maintained, I can remove the unmaintance information

fast_id_map has unsound API and unmaintained

---

crates/tsify-next/RUSTSEC-0000-0000.md

See https://github.com/siefkenj/tsify/issues/57#issuecomment-3132840632 .

Add unmaintained advisory for tsify-next

---

crates/adler/RUSTSEC-0000-0000.md

Closes https://github.com/rustsec/advisory-db/issues/1992

Add unmaintained advisory for adler

---

crates/fxhash/RUSTSEC-0000-0000.md

Add advisory for unmaintained fxhash crate

---

crates/servo-fontconfig/RUSTSEC-0000-0000.md

Add unmaintained advisory for servo-fontconfig
